
package com.moptra.go4wealth.prs.payment.tempuri;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2018-05-31T13:58:30.806+05:30
 * Generated source version: 2.7.5
 * 
 */
public final class IStarMFPaymentGatewayService_WSHttpBindingIStarMFPaymentGatewayService1_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "StarMFPaymentGatewayService");

    private IStarMFPaymentGatewayService_WSHttpBindingIStarMFPaymentGatewayService1_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = StarMFPaymentGatewayService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        StarMFPaymentGatewayService ss = new StarMFPaymentGatewayService(wsdlURL, SERVICE_NAME);
        IStarMFPaymentGatewayService port = ss.getWSHttpBindingIStarMFPaymentGatewayService1();  
        
        {
        System.out.println("Invoking paymentGatewayAPI...");
        com.moptra.go4wealth.prs.payment.starmfpaymentgatewayservice.RequestParam _paymentGatewayAPI_param = null;
        com.moptra.go4wealth.prs.payment.starmfpaymentgatewayservice.Response _paymentGatewayAPI__return = port.paymentGatewayAPI(_paymentGatewayAPI_param);
        System.out.println("paymentGatewayAPI.result=" + _paymentGatewayAPI__return);


        }
        {
        System.out.println("Invoking getPassword...");
        com.moptra.go4wealth.prs.payment.starmfpaymentgatewayservice.PasswordRequest _getPassword_param = null;
        com.moptra.go4wealth.prs.payment.starmfpaymentgatewayservice.Response _getPassword__return = port.getPassword(_getPassword_param);
        System.out.println("getPassword.result=" + _getPassword__return);


        }

        System.exit(0);
    }

}
