package com.moptra.go4wealth.prs.payment.tempuri;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2018-05-31T13:58:30.827+05:30
 * Generated source version: 2.7.5
 * 
 */
@WebServiceClient(name = "StarMFPaymentGatewayService", 
                  wsdlLocation = "classpath:wsdl/StarMFPaymentGatewayService.xml",
                  targetNamespace = "http://tempuri.org/") 
public class StarMFPaymentGatewayService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "StarMFPaymentGatewayService");
    public final static QName WSHttpBindingIStarMFPaymentGatewayService = new QName("http://tempuri.org/", "WSHttpBinding_IStarMFPaymentGatewayService");
    public final static QName WSHttpBindingIStarMFPaymentGatewayService1 = new QName("http://tempuri.org/", "WSHttpBinding_IStarMFPaymentGatewayService1");
    static {
        URL url = StarMFPaymentGatewayService.class.getClassLoader().getResource("wsdl/StarMFPaymentGatewayService.xml");
        if (url == null) {
            java.util.logging.Logger.getLogger(StarMFPaymentGatewayService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/StarMFPaymentGatewayService.xml");
        }       
        WSDL_LOCATION = url;   
    }

    public StarMFPaymentGatewayService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public StarMFPaymentGatewayService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StarMFPaymentGatewayService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public StarMFPaymentGatewayService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public StarMFPaymentGatewayService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public StarMFPaymentGatewayService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IStarMFPaymentGatewayService
     */
    @WebEndpoint(name = "WSHttpBinding_IStarMFPaymentGatewayService")
    public IStarMFPaymentGatewayService getWSHttpBindingIStarMFPaymentGatewayService() {
        return super.getPort(WSHttpBindingIStarMFPaymentGatewayService, IStarMFPaymentGatewayService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IStarMFPaymentGatewayService
     */
    @WebEndpoint(name = "WSHttpBinding_IStarMFPaymentGatewayService")
    public IStarMFPaymentGatewayService getWSHttpBindingIStarMFPaymentGatewayService(WebServiceFeature... features) {
        return super.getPort(WSHttpBindingIStarMFPaymentGatewayService, IStarMFPaymentGatewayService.class, features);
    }
    /**
     *
     * @return
     *     returns IStarMFPaymentGatewayService
     */
    @WebEndpoint(name = "WSHttpBinding_IStarMFPaymentGatewayService1")
    public IStarMFPaymentGatewayService getWSHttpBindingIStarMFPaymentGatewayService1() {
        return super.getPort(WSHttpBindingIStarMFPaymentGatewayService1, IStarMFPaymentGatewayService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IStarMFPaymentGatewayService
     */
    @WebEndpoint(name = "WSHttpBinding_IStarMFPaymentGatewayService1")
    public IStarMFPaymentGatewayService getWSHttpBindingIStarMFPaymentGatewayService1(WebServiceFeature... features) {
        return super.getPort(WSHttpBindingIStarMFPaymentGatewayService1, IStarMFPaymentGatewayService.class, features);
    }

}
