package com.moptra.go4wealth.prs.mfuploadapi.com.bseindia.bsestarmfdemo._2016._01;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2018-07-24T18:47:26.048+05:30
 * Generated source version: 2.7.5
 * 
 */
@WebService(targetNamespace = "http://www.bsestarmf.in/2016/01/", name = "IStarMFWebService")
@XmlSeeAlso({com.moptra.go4wealth.prs.mfuploadapi.com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, ObjectFactory.class})
public interface IStarMFWebService {

    @WebMethod(operationName = "EMandateAuthURL", action = "http://www.bsestarmf.in/2016/01/IStarMFWebService/EMandateAuthURL")
    @Action(input = "http://www.bsestarmf.in/2016/01/IStarMFWebService/EMandateAuthURL", output = "http://www.bsestarmf.in/2016/01/IStarMFWebService/EMandateAuthURLResponse")
    @RequestWrapper(localName = "EMandateAuthURL", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "in.bsestarmf._2016._01.EMandateAuthURL")
    @ResponseWrapper(localName = "EMandateAuthURLResponse", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "in.bsestarmf._2016._01.EMandateAuthURLResponse")
    @WebResult(name = "EMandateAuthURLResult", targetNamespace = "http://www.bsestarmf.in/2016/01/")
    public com.moptra.go4wealth.prs.mfuploadapi.org.datacontract.schemas._2004._07.starmfwebservice.EMandateAuthURLResponse eMandateAuthURL(
        @WebParam(name = "Param", targetNamespace = "http://www.bsestarmf.in/2016/01/")
        com.moptra.go4wealth.prs.mfuploadapi.org.datacontract.schemas._2004._07.starmfwebservice.EMandateAuthURLRequest param
    );

    @WebMethod(operationName = "ProvOrderStatus", action = "http://www.bsestarmf.in/2016/01/IStarMFWebService/ProvOrderStatus")
    @Action(input = "http://www.bsestarmf.in/2016/01/IStarMFWebService/ProvOrderStatus", output = "http://www.bsestarmf.in/2016/01/IStarMFWebService/ProvOrderStatusResponse")
    @RequestWrapper(localName = "ProvOrderStatus", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "in.bsestarmf._2016._01.ProvOrderStatus")
    @ResponseWrapper(localName = "ProvOrderStatusResponse", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "in.bsestarmf._2016._01.ProvOrderStatusResponse")
    @WebResult(name = "ProvOrderStatusResult", targetNamespace = "http://www.bsestarmf.in/2016/01/")
    public com.moptra.go4wealth.prs.mfuploadapi.org.datacontract.schemas._2004._07.starmfwebservice.ProvOrderResponse provOrderStatus(
        @WebParam(name = "Param", targetNamespace = "http://www.bsestarmf.in/2016/01/")
        com.moptra.go4wealth.prs.mfuploadapi.org.datacontract.schemas._2004._07.starmfwebservice.OrderRequest param
    );

    @WebMethod(operationName = "GetAccessToken", action = "http://www.bsestarmf.in/2016/01/IStarMFWebService/GetAccessToken")
    @Action(input = "http://www.bsestarmf.in/2016/01/IStarMFWebService/GetAccessToken", output = "http://www.bsestarmf.in/2016/01/IStarMFWebService/GetAccessTokenResponse")
    @RequestWrapper(localName = "GetAccessToken", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "in.bsestarmf._2016._01.GetAccessToken")
    @ResponseWrapper(localName = "GetAccessTokenResponse", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "in.bsestarmf._2016._01.GetAccessTokenResponse")
    @WebResult(name = "GetAccessTokenResult", targetNamespace = "http://www.bsestarmf.in/2016/01/")
    public com.moptra.go4wealth.prs.mfuploadapi.org.datacontract.schemas._2004._07.starmfwebservice.Response getAccessToken(
        @WebParam(name = "Param", targetNamespace = "http://www.bsestarmf.in/2016/01/")
        com.moptra.go4wealth.prs.mfuploadapi.org.datacontract.schemas._2004._07.starmfwebservice.PasswordRequest param
    );

    @WebMethod(operationName = "GetPasswordMobile", action = "http://www.bsestarmf.in/2016/01/IStarMFWebService/GetPasswordMobile")
    @Action(input = "http://www.bsestarmf.in/2016/01/IStarMFWebService/GetPasswordMobile", output = "http://www.bsestarmf.in/2016/01/IStarMFWebService/GetPasswordMobileResponse")
    @RequestWrapper(localName = "GetPasswordMobile", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "in.bsestarmf._2016._01.GetPasswordMobile")
    @ResponseWrapper(localName = "GetPasswordMobileResponse", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "in.bsestarmf._2016._01.GetPasswordMobileResponse")
    @WebResult(name = "GetPasswordMobileResult", targetNamespace = "http://www.bsestarmf.in/2016/01/")
    public com.moptra.go4wealth.prs.mfuploadapi.org.datacontract.schemas._2004._07.starmfwebservice.Response getPasswordMobile(
        @WebParam(name = "Param", targetNamespace = "http://www.bsestarmf.in/2016/01/")
        com.moptra.go4wealth.prs.mfuploadapi.org.datacontract.schemas._2004._07.starmfwebservice.PasswordRequest param
    );

    @WebMethod(operationName = "GetPasswordForChildOrder", action = "http://www.bsestarmf.in/2016/01/IStarMFWebService/GetPasswordForChildOrder")
    @Action(input = "http://www.bsestarmf.in/2016/01/IStarMFWebService/GetPasswordForChildOrder", output = "http://www.bsestarmf.in/2016/01/IStarMFWebService/GetPasswordForChildOrderResponse")
    @RequestWrapper(localName = "GetPasswordForChildOrder", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "in.bsestarmf._2016._01.GetPasswordForChildOrder")
    @ResponseWrapper(localName = "GetPasswordForChildOrderResponse", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "in.bsestarmf._2016._01.GetPasswordForChildOrderResponse")
    @WebResult(name = "GetPasswordForChildOrderResult", targetNamespace = "http://www.bsestarmf.in/2016/01/")
    public com.moptra.go4wealth.prs.mfuploadapi.org.datacontract.schemas._2004._07.starmfwebservice.Response getPasswordForChildOrder(
        @WebParam(name = "Param", targetNamespace = "http://www.bsestarmf.in/2016/01/")
        com.moptra.go4wealth.prs.mfuploadapi.org.datacontract.schemas._2004._07.starmfwebservice.PasswordRequest param
    );

    @WebMethod(operationName = "ChildOrderDetails", action = "http://www.bsestarmf.in/2016/01/IStarMFWebService/ChildOrderDetails")
    @Action(input = "http://www.bsestarmf.in/2016/01/IStarMFWebService/ChildOrderDetails", output = "http://www.bsestarmf.in/2016/01/IStarMFWebService/ChildOrderDetailsResponse")
    @RequestWrapper(localName = "ChildOrderDetails", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "in.bsestarmf._2016._01.ChildOrderDetails")
    @ResponseWrapper(localName = "ChildOrderDetailsResponse", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "in.bsestarmf._2016._01.ChildOrderDetailsResponse")
    @WebResult(name = "ChildOrderDetailsResult", targetNamespace = "http://www.bsestarmf.in/2016/01/")
    public com.moptra.go4wealth.prs.mfuploadapi.org.datacontract.schemas._2004._07.starmfwebservice.ChildOrderResponse childOrderDetails(
        @WebParam(name = "Param", targetNamespace = "http://www.bsestarmf.in/2016/01/")
        com.moptra.go4wealth.prs.mfuploadapi.org.datacontract.schemas._2004._07.starmfwebservice.ChildOrderRequest param
    );

    @WebMethod(operationName = "MFAPIMobile", action = "http://www.bsestarmf.in/2016/01/IStarMFWebService/MFAPIMobile")
    @Action(input = "http://www.bsestarmf.in/2016/01/IStarMFWebService/MFAPIMobile", output = "http://www.bsestarmf.in/2016/01/IStarMFWebService/MFAPIMobileResponse")
    @RequestWrapper(localName = "MFAPIMobile", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "in.bsestarmf._2016._01.MFAPIMobile")
    @ResponseWrapper(localName = "MFAPIMobileResponse", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "in.bsestarmf._2016._01.MFAPIMobileResponse")
    @WebResult(name = "MFAPIMobileResult", targetNamespace = "http://www.bsestarmf.in/2016/01/")
    public com.moptra.go4wealth.prs.mfuploadapi.org.datacontract.schemas._2004._07.starmfwebservice.Response mfapiMobile(
        @WebParam(name = "Param", targetNamespace = "http://www.bsestarmf.in/2016/01/")
        com.moptra.go4wealth.prs.mfuploadapi.org.datacontract.schemas._2004._07.starmfwebservice.MFAPIRequest param
    );

    @WebMethod(action = "http://www.bsestarmf.in/2016/01/IStarMFWebService/getPassword")
    @Action(input = "http://www.bsestarmf.in/2016/01/IStarMFWebService/getPassword", output = "http://www.bsestarmf.in/2016/01/IStarMFWebService/getPasswordResponse")
    @RequestWrapper(localName = "getPassword", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "in.bsestarmf._2016._01.GetPassword")
    @ResponseWrapper(localName = "getPasswordResponse", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "in.bsestarmf._2016._01.GetPasswordResponse")
    @WebResult(name = "getPasswordResult", targetNamespace = "http://www.bsestarmf.in/2016/01/")
    public java.lang.String getPassword(
        @WebParam(name = "UserId", targetNamespace = "http://www.bsestarmf.in/2016/01/")
        java.lang.String userId,
        @WebParam(name = "MemberId", targetNamespace = "http://www.bsestarmf.in/2016/01/")
        java.lang.String memberId,
        @WebParam(name = "Password", targetNamespace = "http://www.bsestarmf.in/2016/01/")
        java.lang.String password,
        @WebParam(name = "PassKey", targetNamespace = "http://www.bsestarmf.in/2016/01/")
        java.lang.String passKey
    );

    @WebMethod(operationName = "OrderStatus", action = "http://www.bsestarmf.in/2016/01/IStarMFWebService/OrderStatus")
    @Action(input = "http://www.bsestarmf.in/2016/01/IStarMFWebService/OrderStatus", output = "http://www.bsestarmf.in/2016/01/IStarMFWebService/OrderStatusResponse")
    @RequestWrapper(localName = "OrderStatus", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "in.bsestarmf._2016._01.OrderStatus")
    @ResponseWrapper(localName = "OrderStatusResponse", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "in.bsestarmf._2016._01.OrderStatusResponse")
    @WebResult(name = "OrderStatusResult", targetNamespace = "http://www.bsestarmf.in/2016/01/")
    public com.moptra.go4wealth.prs.mfuploadapi.org.datacontract.schemas._2004._07.starmfwebservice.OrderResponse orderStatus(
        @WebParam(name = "Param", targetNamespace = "http://www.bsestarmf.in/2016/01/")
        com.moptra.go4wealth.prs.mfuploadapi.org.datacontract.schemas._2004._07.starmfwebservice.OrderRequest param
    );

    @WebMethod(operationName = "MFAPI", action = "http://www.bsestarmf.in/2016/01/IStarMFWebService/MFAPI")
    @Action(input = "http://www.bsestarmf.in/2016/01/IStarMFWebService/MFAPI", output = "http://www.bsestarmf.in/2016/01/IStarMFWebService/MFAPIResponse")
    @RequestWrapper(localName = "MFAPI", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "in.bsestarmf._2016._01.MFAPI")
    @ResponseWrapper(localName = "MFAPIResponse", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "in.bsestarmf._2016._01.MFAPIResponse")
    @WebResult(name = "MFAPIResult", targetNamespace = "http://www.bsestarmf.in/2016/01/")
    public java.lang.String mfapi(
        @WebParam(name = "Flag", targetNamespace = "http://www.bsestarmf.in/2016/01/")
        java.lang.String flag,
        @WebParam(name = "UserId", targetNamespace = "http://www.bsestarmf.in/2016/01/")
        java.lang.String userId,
        @WebParam(name = "EncryptedPassword", targetNamespace = "http://www.bsestarmf.in/2016/01/")
        java.lang.String encryptedPassword,
        @WebParam(name = "param", targetNamespace = "http://www.bsestarmf.in/2016/01/")
        java.lang.String param
    );

    @WebMethod(operationName = "MandateDetails", action = "http://www.bsestarmf.in/2016/01/IStarMFWebService/MandateDetails")
    @Action(input = "http://www.bsestarmf.in/2016/01/IStarMFWebService/MandateDetails", output = "http://www.bsestarmf.in/2016/01/IStarMFWebService/MandateDetailsResponse")
    @RequestWrapper(localName = "MandateDetails", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "in.bsestarmf._2016._01.MandateDetails")
    @ResponseWrapper(localName = "MandateDetailsResponse", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "in.bsestarmf._2016._01.MandateDetailsResponse")
    @WebResult(name = "MandateDetailsResult", targetNamespace = "http://www.bsestarmf.in/2016/01/")
    public com.moptra.go4wealth.prs.mfuploadapi.org.datacontract.schemas._2004._07.starmfwebservice.MandateDetailsResponse mandateDetails(
        @WebParam(name = "Param", targetNamespace = "http://www.bsestarmf.in/2016/01/")
        com.moptra.go4wealth.prs.mfuploadapi.org.datacontract.schemas._2004._07.starmfwebservice.MandateDetailsRequest param
    );

    @WebMethod(operationName = "AllotmentStatement", action = "http://www.bsestarmf.in/2016/01/IStarMFWebService/AllotmentStatement")
    @Action(input = "http://www.bsestarmf.in/2016/01/IStarMFWebService/AllotmentStatement", output = "http://www.bsestarmf.in/2016/01/IStarMFWebService/AllotmentStatementResponse")
    @RequestWrapper(localName = "AllotmentStatement", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "in.bsestarmf._2016._01.AllotmentStatement")
    @ResponseWrapper(localName = "AllotmentStatementResponse", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "in.bsestarmf._2016._01.AllotmentStatementResponse")
    @WebResult(name = "AllotmentStatementResult", targetNamespace = "http://www.bsestarmf.in/2016/01/")
    public com.moptra.go4wealth.prs.mfuploadapi.org.datacontract.schemas._2004._07.starmfwebservice.AllotmentStatementResponse allotmentStatement(
        @WebParam(name = "Param", targetNamespace = "http://www.bsestarmf.in/2016/01/")
        com.moptra.go4wealth.prs.mfuploadapi.org.datacontract.schemas._2004._07.starmfwebservice.AllotmentStatementRequest param
    );

    @WebMethod(operationName = "RedemptionStatement", action = "http://www.bsestarmf.in/2016/01/IStarMFWebService/RedemptionStatement")
    @Action(input = "http://www.bsestarmf.in/2016/01/IStarMFWebService/RedemptionStatement", output = "http://www.bsestarmf.in/2016/01/IStarMFWebService/RedemptionStatementResponse")
    @RequestWrapper(localName = "RedemptionStatement", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "in.bsestarmf._2016._01.RedemptionStatement")
    @ResponseWrapper(localName = "RedemptionStatementResponse", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "in.bsestarmf._2016._01.RedemptionStatementResponse")
    @WebResult(name = "RedemptionStatementResult", targetNamespace = "http://www.bsestarmf.in/2016/01/")
    public com.moptra.go4wealth.prs.mfuploadapi.org.datacontract.schemas._2004._07.starmfwebservice.RedemptionStatementResponse redemptionStatement(
        @WebParam(name = "Param", targetNamespace = "http://www.bsestarmf.in/2016/01/")
        com.moptra.go4wealth.prs.mfuploadapi.org.datacontract.schemas._2004._07.starmfwebservice.RedemptionStatementRequest param
    );
}
