
package com.moptra.go4wealth.prs.orderapi.in.bsestarmf;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.moptra.go4wealth.prs.orderapi.tempuri.MFOrder;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2018-07-24T18:38:41.835+05:30
 * Generated source version: 2.7.5
 * 
 */
public final class MFOrderEntry_WSHttpBindingMFOrderEntry_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "MFOrder");

    private MFOrderEntry_WSHttpBindingMFOrderEntry_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = MFOrder.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        MFOrder ss = new MFOrder(wsdlURL, SERVICE_NAME);
        MFOrderEntry port = ss.getWSHttpBindingMFOrderEntry();  
        
        {
        System.out.println("Invoking getPassword...");
        java.lang.String _getPassword_userId = "";
        java.lang.String _getPassword_password = "";
        java.lang.String _getPassword_passKey = "";
        java.lang.String _getPassword__return = port.getPassword(_getPassword_userId, _getPassword_password, _getPassword_passKey);
        System.out.println("getPassword.result=" + _getPassword__return);


        }
        {
        System.out.println("Invoking switchOrderEntryParam...");
        java.lang.String _switchOrderEntryParam_transCode = "";
        java.lang.String _switchOrderEntryParam_transNo = "";
        java.lang.String _switchOrderEntryParam_orderId = "";
        java.lang.String _switchOrderEntryParam_userId = "";
        java.lang.String _switchOrderEntryParam_memberId = "";
        java.lang.String _switchOrderEntryParam_clientCode = "";
        java.lang.String _switchOrderEntryParam_fromSchemeCd = "";
        java.lang.String _switchOrderEntryParam_toSchemeCd = "";
        java.lang.String _switchOrderEntryParam_buySell = "";
        java.lang.String _switchOrderEntryParam_buySellType = "";
        java.lang.String _switchOrderEntryParam_dpTxn = "";
        java.lang.String _switchOrderEntryParam_orderVal = "";
        java.lang.String _switchOrderEntryParam_switchUnits = "";
        java.lang.String _switchOrderEntryParam_allUnitsFlag = "";
        java.lang.String _switchOrderEntryParam_folioNo = "";
        java.lang.String _switchOrderEntryParam_remarks = "";
        java.lang.String _switchOrderEntryParam_kycStatus = "";
        java.lang.String _switchOrderEntryParam_subBrCode = "";
        java.lang.String _switchOrderEntryParam_euin = "";
        java.lang.String _switchOrderEntryParam_euinVal = "";
        java.lang.String _switchOrderEntryParam_minRedeem = "";
        java.lang.String _switchOrderEntryParam_ipAdd = "";
        java.lang.String _switchOrderEntryParam_password = "";
        java.lang.String _switchOrderEntryParam_passKey = "";
        java.lang.String _switchOrderEntryParam_parma1 = "";
        java.lang.String _switchOrderEntryParam_param2 = "";
        java.lang.String _switchOrderEntryParam_param3 = "";
        java.lang.String _switchOrderEntryParam__return = port.switchOrderEntryParam(_switchOrderEntryParam_transCode, _switchOrderEntryParam_transNo, _switchOrderEntryParam_orderId, _switchOrderEntryParam_userId, _switchOrderEntryParam_memberId, _switchOrderEntryParam_clientCode, _switchOrderEntryParam_fromSchemeCd, _switchOrderEntryParam_toSchemeCd, _switchOrderEntryParam_buySell, _switchOrderEntryParam_buySellType, _switchOrderEntryParam_dpTxn, _switchOrderEntryParam_orderVal, _switchOrderEntryParam_switchUnits, _switchOrderEntryParam_allUnitsFlag, _switchOrderEntryParam_folioNo, _switchOrderEntryParam_remarks, _switchOrderEntryParam_kycStatus, _switchOrderEntryParam_subBrCode, _switchOrderEntryParam_euin, _switchOrderEntryParam_euinVal, _switchOrderEntryParam_minRedeem, _switchOrderEntryParam_ipAdd, _switchOrderEntryParam_password, _switchOrderEntryParam_passKey, _switchOrderEntryParam_parma1, _switchOrderEntryParam_param2, _switchOrderEntryParam_param3);
        System.out.println("switchOrderEntryParam.result=" + _switchOrderEntryParam__return);


        }
        {
        System.out.println("Invoking sipOrderEntryParam...");
        java.lang.String _sipOrderEntryParam_transactionCode = "";
        java.lang.String _sipOrderEntryParam_uniqueRefNo = "";
        java.lang.String _sipOrderEntryParam_schemeCode = "";
        java.lang.String _sipOrderEntryParam_memberCode = "";
        java.lang.String _sipOrderEntryParam_clientCode = "";
        java.lang.String _sipOrderEntryParam_userID = "";
        java.lang.String _sipOrderEntryParam_internalRefNo = "";
        java.lang.String _sipOrderEntryParam_transMode = "";
        java.lang.String _sipOrderEntryParam_dpTxnMode = "";
        java.lang.String _sipOrderEntryParam_startDate = "";
        java.lang.String _sipOrderEntryParam_frequencyType = "";
        java.lang.String _sipOrderEntryParam_frequencyAllowed = "";
        java.lang.String _sipOrderEntryParam_installmentAmount = "";
        java.lang.String _sipOrderEntryParam_noOfInstallment = "";
        java.lang.String _sipOrderEntryParam_remarks = "";
        java.lang.String _sipOrderEntryParam_folioNo = "";
        java.lang.String _sipOrderEntryParam_firstOrderFlag = "";
        java.lang.String _sipOrderEntryParam_subberCode = "";
        java.lang.String _sipOrderEntryParam_euin = "";
        java.lang.String _sipOrderEntryParam_euinVal = "";
        java.lang.String _sipOrderEntryParam_dpc = "";
        java.lang.String _sipOrderEntryParam_regId = "";
        java.lang.String _sipOrderEntryParam_ipAdd = "";
        java.lang.String _sipOrderEntryParam_password = "";
        java.lang.String _sipOrderEntryParam_passKey = "";
        java.lang.String _sipOrderEntryParam_param1 = "";
        java.lang.String _sipOrderEntryParam_param2 = "";
        java.lang.String _sipOrderEntryParam_param3 = "";
        java.lang.String _sipOrderEntryParam__return = port.sipOrderEntryParam(_sipOrderEntryParam_transactionCode, _sipOrderEntryParam_uniqueRefNo, _sipOrderEntryParam_schemeCode, _sipOrderEntryParam_memberCode, _sipOrderEntryParam_clientCode, _sipOrderEntryParam_userID, _sipOrderEntryParam_internalRefNo, _sipOrderEntryParam_transMode, _sipOrderEntryParam_dpTxnMode, _sipOrderEntryParam_startDate, _sipOrderEntryParam_frequencyType, _sipOrderEntryParam_frequencyAllowed, _sipOrderEntryParam_installmentAmount, _sipOrderEntryParam_noOfInstallment, _sipOrderEntryParam_remarks, _sipOrderEntryParam_folioNo, _sipOrderEntryParam_firstOrderFlag, _sipOrderEntryParam_subberCode, _sipOrderEntryParam_euin, _sipOrderEntryParam_euinVal, _sipOrderEntryParam_dpc, _sipOrderEntryParam_regId, _sipOrderEntryParam_ipAdd, _sipOrderEntryParam_password, _sipOrderEntryParam_passKey, _sipOrderEntryParam_param1, _sipOrderEntryParam_param2, _sipOrderEntryParam_param3);
        System.out.println("sipOrderEntryParam.result=" + _sipOrderEntryParam__return);


        }
        {
        System.out.println("Invoking spreadOrderEntryParam...");
        java.lang.String _spreadOrderEntryParam_transactionCode = "";
        java.lang.String _spreadOrderEntryParam_uniqueRefNo = "";
        java.lang.String _spreadOrderEntryParam_orderID = "";
        java.lang.String _spreadOrderEntryParam_userID = "";
        java.lang.String _spreadOrderEntryParam_memberId = "";
        java.lang.String _spreadOrderEntryParam_clientCode = "";
        java.lang.String _spreadOrderEntryParam_schemeCode = "";
        java.lang.String _spreadOrderEntryParam_buySell = "";
        java.lang.String _spreadOrderEntryParam_buySellType = "";
        java.lang.String _spreadOrderEntryParam_dpTxn = "";
        java.lang.String _spreadOrderEntryParam_orderValue = "";
        java.lang.String _spreadOrderEntryParam_redemptionAmt = "";
        java.lang.String _spreadOrderEntryParam_allUnitFlag = "";
        java.lang.String _spreadOrderEntryParam_redeemDate = "";
        java.lang.String _spreadOrderEntryParam_folioNo = "";
        java.lang.String _spreadOrderEntryParam_remarks = "";
        java.lang.String _spreadOrderEntryParam_kycStatus = "";
        java.lang.String _spreadOrderEntryParam_refNo = "";
        java.lang.String _spreadOrderEntryParam_subBroCode = "";
        java.lang.String _spreadOrderEntryParam_euin = "";
        java.lang.String _spreadOrderEntryParam_euinVal = "";
        java.lang.String _spreadOrderEntryParam_minRedeem = "";
        java.lang.String _spreadOrderEntryParam_dpc = "";
        java.lang.String _spreadOrderEntryParam_ipAddress = "";
        java.lang.String _spreadOrderEntryParam_password = "";
        java.lang.String _spreadOrderEntryParam_passKey = "";
        java.lang.String _spreadOrderEntryParam_param1 = "";
        java.lang.String _spreadOrderEntryParam_param2 = "";
        java.lang.String _spreadOrderEntryParam_param3 = "";
        java.lang.String _spreadOrderEntryParam__return = port.spreadOrderEntryParam(_spreadOrderEntryParam_transactionCode, _spreadOrderEntryParam_uniqueRefNo, _spreadOrderEntryParam_orderID, _spreadOrderEntryParam_userID, _spreadOrderEntryParam_memberId, _spreadOrderEntryParam_clientCode, _spreadOrderEntryParam_schemeCode, _spreadOrderEntryParam_buySell, _spreadOrderEntryParam_buySellType, _spreadOrderEntryParam_dpTxn, _spreadOrderEntryParam_orderValue, _spreadOrderEntryParam_redemptionAmt, _spreadOrderEntryParam_allUnitFlag, _spreadOrderEntryParam_redeemDate, _spreadOrderEntryParam_folioNo, _spreadOrderEntryParam_remarks, _spreadOrderEntryParam_kycStatus, _spreadOrderEntryParam_refNo, _spreadOrderEntryParam_subBroCode, _spreadOrderEntryParam_euin, _spreadOrderEntryParam_euinVal, _spreadOrderEntryParam_minRedeem, _spreadOrderEntryParam_dpc, _spreadOrderEntryParam_ipAddress, _spreadOrderEntryParam_password, _spreadOrderEntryParam_passKey, _spreadOrderEntryParam_param1, _spreadOrderEntryParam_param2, _spreadOrderEntryParam_param3);
        System.out.println("spreadOrderEntryParam.result=" + _spreadOrderEntryParam__return);


        }
        {
        System.out.println("Invoking orderEntryParam...");
        java.lang.String _orderEntryParam_transCode = "";
        java.lang.String _orderEntryParam_transNo = "";
        java.lang.String _orderEntryParam_orderId = "";
        java.lang.String _orderEntryParam_userID = "";
        java.lang.String _orderEntryParam_memberId = "";
        java.lang.String _orderEntryParam_clientCode = "";
        java.lang.String _orderEntryParam_schemeCd = "";
        java.lang.String _orderEntryParam_buySell = "";
        java.lang.String _orderEntryParam_buySellType = "";
        java.lang.String _orderEntryParam_dpTxn = "";
        java.lang.String _orderEntryParam_orderVal = "";
        java.lang.String _orderEntryParam_qty = "";
        java.lang.String _orderEntryParam_allRedeem = "";
        java.lang.String _orderEntryParam_folioNo = "";
        java.lang.String _orderEntryParam_remarks = "";
        java.lang.String _orderEntryParam_kycStatus = "";
        java.lang.String _orderEntryParam_refNo = "";
        java.lang.String _orderEntryParam_subBrCode = "";
        java.lang.String _orderEntryParam_euin = "";
        java.lang.String _orderEntryParam_euinVal = "";
        java.lang.String _orderEntryParam_minRedeem = "";
        java.lang.String _orderEntryParam_dpc = "";
        java.lang.String _orderEntryParam_ipAdd = "";
        java.lang.String _orderEntryParam_password = "";
        java.lang.String _orderEntryParam_passKey = "";
        java.lang.String _orderEntryParam_parma1 = "";
        java.lang.String _orderEntryParam_param2 = "";
        java.lang.String _orderEntryParam_param3 = "";
        java.lang.String _orderEntryParam__return = port.orderEntryParam(_orderEntryParam_transCode, _orderEntryParam_transNo, _orderEntryParam_orderId, _orderEntryParam_userID, _orderEntryParam_memberId, _orderEntryParam_clientCode, _orderEntryParam_schemeCd, _orderEntryParam_buySell, _orderEntryParam_buySellType, _orderEntryParam_dpTxn, _orderEntryParam_orderVal, _orderEntryParam_qty, _orderEntryParam_allRedeem, _orderEntryParam_folioNo, _orderEntryParam_remarks, _orderEntryParam_kycStatus, _orderEntryParam_refNo, _orderEntryParam_subBrCode, _orderEntryParam_euin, _orderEntryParam_euinVal, _orderEntryParam_minRedeem, _orderEntryParam_dpc, _orderEntryParam_ipAdd, _orderEntryParam_password, _orderEntryParam_passKey, _orderEntryParam_parma1, _orderEntryParam_param2, _orderEntryParam_param3);
        System.out.println("orderEntryParam.result=" + _orderEntryParam__return);


        }
        {
        System.out.println("Invoking xsipOrderEntryParam...");
        java.lang.String _xsipOrderEntryParam_transactionCode = "";
        java.lang.String _xsipOrderEntryParam_uniqueRefNo = "";
        java.lang.String _xsipOrderEntryParam_schemeCode = "";
        java.lang.String _xsipOrderEntryParam_memberCode = "";
        java.lang.String _xsipOrderEntryParam_clientCode = "";
        java.lang.String _xsipOrderEntryParam_userId = "";
        java.lang.String _xsipOrderEntryParam_internalRefNo = "";
        java.lang.String _xsipOrderEntryParam_transMode = "";
        java.lang.String _xsipOrderEntryParam_dpTxnMode = "";
        java.lang.String _xsipOrderEntryParam_startDate = "";
        java.lang.String _xsipOrderEntryParam_frequencyType = "";
        java.lang.String _xsipOrderEntryParam_frequencyAllowed = "";
        java.lang.String _xsipOrderEntryParam_installmentAmount = "";
        java.lang.String _xsipOrderEntryParam_noOfInstallment = "";
        java.lang.String _xsipOrderEntryParam_remarks = "";
        java.lang.String _xsipOrderEntryParam_folioNo = "";
        java.lang.String _xsipOrderEntryParam_firstOrderFlag = "";
        java.lang.String _xsipOrderEntryParam_brokerage = "";
        java.lang.String _xsipOrderEntryParam_mandateID = "";
        java.lang.String _xsipOrderEntryParam_subberCode = "";
        java.lang.String _xsipOrderEntryParam_euin = "";
        java.lang.String _xsipOrderEntryParam_euinVal = "";
        java.lang.String _xsipOrderEntryParam_dpc = "";
        java.lang.String _xsipOrderEntryParam_xsipRegID = "";
        java.lang.String _xsipOrderEntryParam_ipAdd = "";
        java.lang.String _xsipOrderEntryParam_password = "";
        java.lang.String _xsipOrderEntryParam_passKey = "";
        java.lang.String _xsipOrderEntryParam_param1 = "";
        java.lang.String _xsipOrderEntryParam_param2 = "";
        java.lang.String _xsipOrderEntryParam_param3 = "";
        java.lang.String _xsipOrderEntryParam__return = port.xsipOrderEntryParam(_xsipOrderEntryParam_transactionCode, _xsipOrderEntryParam_uniqueRefNo, _xsipOrderEntryParam_schemeCode, _xsipOrderEntryParam_memberCode, _xsipOrderEntryParam_clientCode, _xsipOrderEntryParam_userId, _xsipOrderEntryParam_internalRefNo, _xsipOrderEntryParam_transMode, _xsipOrderEntryParam_dpTxnMode, _xsipOrderEntryParam_startDate, _xsipOrderEntryParam_frequencyType, _xsipOrderEntryParam_frequencyAllowed, _xsipOrderEntryParam_installmentAmount, _xsipOrderEntryParam_noOfInstallment, _xsipOrderEntryParam_remarks, _xsipOrderEntryParam_folioNo, _xsipOrderEntryParam_firstOrderFlag, _xsipOrderEntryParam_brokerage, _xsipOrderEntryParam_mandateID, _xsipOrderEntryParam_subberCode, _xsipOrderEntryParam_euin, _xsipOrderEntryParam_euinVal, _xsipOrderEntryParam_dpc, _xsipOrderEntryParam_xsipRegID, _xsipOrderEntryParam_ipAdd, _xsipOrderEntryParam_password, _xsipOrderEntryParam_passKey, _xsipOrderEntryParam_param1, _xsipOrderEntryParam_param2, _xsipOrderEntryParam_param3);
        System.out.println("xsipOrderEntryParam.result=" + _xsipOrderEntryParam__return);


        }

        System.exit(0);
    }

}
