package com.moptra.go4wealth.prs.orderapi.in.bsestarmf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2018-07-24T18:38:41.903+05:30
 * Generated source version: 2.7.5
 * 
 */
@WebService(targetNamespace = "http://bsestarmf.in/", name = "MFOrderEntry")
@XmlSeeAlso({ObjectFactory.class, ObjectFactory.class})
public interface MFOrderEntry {

    @WebMethod(action = "http://bsestarmf.in/MFOrderEntry/getPassword")
    @Action(input = "http://bsestarmf.in/MFOrderEntry/getPassword", output = "http://bsestarmf.in/MFOrderEntry/getPasswordResponse")
    @RequestWrapper(localName = "getPassword", targetNamespace = "http://bsestarmf.in/", className = "in.bsestarmf.GetPassword")
    @ResponseWrapper(localName = "getPasswordResponse", targetNamespace = "http://bsestarmf.in/", className = "in.bsestarmf.GetPasswordResponse")
    @WebResult(name = "getPasswordResult", targetNamespace = "http://bsestarmf.in/")
    public java.lang.String getPassword(
        @WebParam(name = "UserId", targetNamespace = "http://bsestarmf.in/")
        java.lang.String userId,
        @WebParam(name = "Password", targetNamespace = "http://bsestarmf.in/")
        java.lang.String password,
        @WebParam(name = "PassKey", targetNamespace = "http://bsestarmf.in/")
        java.lang.String passKey
    );

    @WebMethod(action = "http://bsestarmf.in/MFOrderEntry/switchOrderEntryParam")
    @Action(input = "http://bsestarmf.in/MFOrderEntry/switchOrderEntryParam", output = "http://bsestarmf.in/MFOrderEntry/switchOrderEntryParamResponse")
    @RequestWrapper(localName = "switchOrderEntryParam", targetNamespace = "http://bsestarmf.in/", className = "in.bsestarmf.SwitchOrderEntryParam")
    @ResponseWrapper(localName = "switchOrderEntryParamResponse", targetNamespace = "http://bsestarmf.in/", className = "in.bsestarmf.SwitchOrderEntryParamResponse")
    @WebResult(name = "switchOrderEntryParamResult", targetNamespace = "http://bsestarmf.in/")
    public java.lang.String switchOrderEntryParam(
        @WebParam(name = "TransCode", targetNamespace = "http://bsestarmf.in/")
        java.lang.String transCode,
        @WebParam(name = "TransNo", targetNamespace = "http://bsestarmf.in/")
        java.lang.String transNo,
        @WebParam(name = "OrderId", targetNamespace = "http://bsestarmf.in/")
        java.lang.String orderId,
        @WebParam(name = "UserId", targetNamespace = "http://bsestarmf.in/")
        java.lang.String userId,
        @WebParam(name = "MemberId", targetNamespace = "http://bsestarmf.in/")
        java.lang.String memberId,
        @WebParam(name = "ClientCode", targetNamespace = "http://bsestarmf.in/")
        java.lang.String clientCode,
        @WebParam(name = "FromSchemeCd", targetNamespace = "http://bsestarmf.in/")
        java.lang.String fromSchemeCd,
        @WebParam(name = "ToSchemeCd", targetNamespace = "http://bsestarmf.in/")
        java.lang.String toSchemeCd,
        @WebParam(name = "BuySell", targetNamespace = "http://bsestarmf.in/")
        java.lang.String buySell,
        @WebParam(name = "BuySellType", targetNamespace = "http://bsestarmf.in/")
        java.lang.String buySellType,
        @WebParam(name = "DPTxn", targetNamespace = "http://bsestarmf.in/")
        java.lang.String dpTxn,
        @WebParam(name = "OrderVal", targetNamespace = "http://bsestarmf.in/")
        java.lang.String orderVal,
        @WebParam(name = "SwitchUnits", targetNamespace = "http://bsestarmf.in/")
        java.lang.String switchUnits,
        @WebParam(name = "AllUnitsFlag", targetNamespace = "http://bsestarmf.in/")
        java.lang.String allUnitsFlag,
        @WebParam(name = "FolioNo", targetNamespace = "http://bsestarmf.in/")
        java.lang.String folioNo,
        @WebParam(name = "Remarks", targetNamespace = "http://bsestarmf.in/")
        java.lang.String remarks,
        @WebParam(name = "KYCStatus", targetNamespace = "http://bsestarmf.in/")
        java.lang.String kycStatus,
        @WebParam(name = "SubBrCode", targetNamespace = "http://bsestarmf.in/")
        java.lang.String subBrCode,
        @WebParam(name = "EUIN", targetNamespace = "http://bsestarmf.in/")
        java.lang.String euin,
        @WebParam(name = "EUINVal", targetNamespace = "http://bsestarmf.in/")
        java.lang.String euinVal,
        @WebParam(name = "MinRedeem", targetNamespace = "http://bsestarmf.in/")
        java.lang.String minRedeem,
        @WebParam(name = "IPAdd", targetNamespace = "http://bsestarmf.in/")
        java.lang.String ipAdd,
        @WebParam(name = "Password", targetNamespace = "http://bsestarmf.in/")
        java.lang.String password,
        @WebParam(name = "PassKey", targetNamespace = "http://bsestarmf.in/")
        java.lang.String passKey,
        @WebParam(name = "Parma1", targetNamespace = "http://bsestarmf.in/")
        java.lang.String parma1,
        @WebParam(name = "Param2", targetNamespace = "http://bsestarmf.in/")
        java.lang.String param2,
        @WebParam(name = "Param3", targetNamespace = "http://bsestarmf.in/")
        java.lang.String param3
    );

    @WebMethod(action = "http://bsestarmf.in/MFOrderEntry/sipOrderEntryParam")
    @Action(input = "http://bsestarmf.in/MFOrderEntry/sipOrderEntryParam", output = "http://bsestarmf.in/MFOrderEntry/sipOrderEntryParamResponse")
    @RequestWrapper(localName = "sipOrderEntryParam", targetNamespace = "http://bsestarmf.in/", className = "in.bsestarmf.SipOrderEntryParam")
    @ResponseWrapper(localName = "sipOrderEntryParamResponse", targetNamespace = "http://bsestarmf.in/", className = "in.bsestarmf.SipOrderEntryParamResponse")
    @WebResult(name = "sipOrderEntryParamResult", targetNamespace = "http://bsestarmf.in/")
    public java.lang.String sipOrderEntryParam(
        @WebParam(name = "TransactionCode", targetNamespace = "http://bsestarmf.in/")
        java.lang.String transactionCode,
        @WebParam(name = "UniqueRefNo", targetNamespace = "http://bsestarmf.in/")
        java.lang.String uniqueRefNo,
        @WebParam(name = "SchemeCode", targetNamespace = "http://bsestarmf.in/")
        java.lang.String schemeCode,
        @WebParam(name = "MemberCode", targetNamespace = "http://bsestarmf.in/")
        java.lang.String memberCode,
        @WebParam(name = "ClientCode", targetNamespace = "http://bsestarmf.in/")
        java.lang.String clientCode,
        @WebParam(name = "UserID", targetNamespace = "http://bsestarmf.in/")
        java.lang.String userID,
        @WebParam(name = "InternalRefNo", targetNamespace = "http://bsestarmf.in/")
        java.lang.String internalRefNo,
        @WebParam(name = "TransMode", targetNamespace = "http://bsestarmf.in/")
        java.lang.String transMode,
        @WebParam(name = "DpTxnMode", targetNamespace = "http://bsestarmf.in/")
        java.lang.String dpTxnMode,
        @WebParam(name = "StartDate", targetNamespace = "http://bsestarmf.in/")
        java.lang.String startDate,
        @WebParam(name = "FrequencyType", targetNamespace = "http://bsestarmf.in/")
        java.lang.String frequencyType,
        @WebParam(name = "FrequencyAllowed", targetNamespace = "http://bsestarmf.in/")
        java.lang.String frequencyAllowed,
        @WebParam(name = "InstallmentAmount", targetNamespace = "http://bsestarmf.in/")
        java.lang.String installmentAmount,
        @WebParam(name = "NoOfInstallment", targetNamespace = "http://bsestarmf.in/")
        java.lang.String noOfInstallment,
        @WebParam(name = "Remarks", targetNamespace = "http://bsestarmf.in/")
        java.lang.String remarks,
        @WebParam(name = "FolioNo", targetNamespace = "http://bsestarmf.in/")
        java.lang.String folioNo,
        @WebParam(name = "FirstOrderFlag", targetNamespace = "http://bsestarmf.in/")
        java.lang.String firstOrderFlag,
        @WebParam(name = "SubberCode", targetNamespace = "http://bsestarmf.in/")
        java.lang.String subberCode,
        @WebParam(name = "Euin", targetNamespace = "http://bsestarmf.in/")
        java.lang.String euin,
        @WebParam(name = "EuinVal", targetNamespace = "http://bsestarmf.in/")
        java.lang.String euinVal,
        @WebParam(name = "DPC", targetNamespace = "http://bsestarmf.in/")
        java.lang.String dpc,
        @WebParam(name = "RegId", targetNamespace = "http://bsestarmf.in/")
        java.lang.String regId,
        @WebParam(name = "IPAdd", targetNamespace = "http://bsestarmf.in/")
        java.lang.String ipAdd,
        @WebParam(name = "Password", targetNamespace = "http://bsestarmf.in/")
        java.lang.String password,
        @WebParam(name = "PassKey", targetNamespace = "http://bsestarmf.in/")
        java.lang.String passKey,
        @WebParam(name = "Param1", targetNamespace = "http://bsestarmf.in/")
        java.lang.String param1,
        @WebParam(name = "Param2", targetNamespace = "http://bsestarmf.in/")
        java.lang.String param2,
        @WebParam(name = "Param3", targetNamespace = "http://bsestarmf.in/")
        java.lang.String param3
    );

    @WebMethod(action = "http://bsestarmf.in/MFOrderEntry/spreadOrderEntryParam")
    @Action(input = "http://bsestarmf.in/MFOrderEntry/spreadOrderEntryParam", output = "http://bsestarmf.in/MFOrderEntry/spreadOrderEntryParamResponse")
    @RequestWrapper(localName = "spreadOrderEntryParam", targetNamespace = "http://bsestarmf.in/", className = "in.bsestarmf.SpreadOrderEntryParam")
    @ResponseWrapper(localName = "spreadOrderEntryParamResponse", targetNamespace = "http://bsestarmf.in/", className = "in.bsestarmf.SpreadOrderEntryParamResponse")
    @WebResult(name = "spreadOrderEntryParamResult", targetNamespace = "http://bsestarmf.in/")
    public java.lang.String spreadOrderEntryParam(
        @WebParam(name = "TransactionCode", targetNamespace = "http://bsestarmf.in/")
        java.lang.String transactionCode,
        @WebParam(name = "UniqueRefNo", targetNamespace = "http://bsestarmf.in/")
        java.lang.String uniqueRefNo,
        @WebParam(name = "OrderID", targetNamespace = "http://bsestarmf.in/")
        java.lang.String orderID,
        @WebParam(name = "UserID", targetNamespace = "http://bsestarmf.in/")
        java.lang.String userID,
        @WebParam(name = "MemberId", targetNamespace = "http://bsestarmf.in/")
        java.lang.String memberId,
        @WebParam(name = "ClientCode", targetNamespace = "http://bsestarmf.in/")
        java.lang.String clientCode,
        @WebParam(name = "SchemeCode", targetNamespace = "http://bsestarmf.in/")
        java.lang.String schemeCode,
        @WebParam(name = "BuySell", targetNamespace = "http://bsestarmf.in/")
        java.lang.String buySell,
        @WebParam(name = "BuySellType", targetNamespace = "http://bsestarmf.in/")
        java.lang.String buySellType,
        @WebParam(name = "DPTxn", targetNamespace = "http://bsestarmf.in/")
        java.lang.String dpTxn,
        @WebParam(name = "OrderValue", targetNamespace = "http://bsestarmf.in/")
        java.lang.String orderValue,
        @WebParam(name = "RedemptionAmt", targetNamespace = "http://bsestarmf.in/")
        java.lang.String redemptionAmt,
        @WebParam(name = "AllUnitFlag", targetNamespace = "http://bsestarmf.in/")
        java.lang.String allUnitFlag,
        @WebParam(name = "RedeemDate", targetNamespace = "http://bsestarmf.in/")
        java.lang.String redeemDate,
        @WebParam(name = "FolioNo", targetNamespace = "http://bsestarmf.in/")
        java.lang.String folioNo,
        @WebParam(name = "Remarks", targetNamespace = "http://bsestarmf.in/")
        java.lang.String remarks,
        @WebParam(name = "KYCStatus", targetNamespace = "http://bsestarmf.in/")
        java.lang.String kycStatus,
        @WebParam(name = "RefNo", targetNamespace = "http://bsestarmf.in/")
        java.lang.String refNo,
        @WebParam(name = "SubBroCode", targetNamespace = "http://bsestarmf.in/")
        java.lang.String subBroCode,
        @WebParam(name = "EUIN", targetNamespace = "http://bsestarmf.in/")
        java.lang.String euin,
        @WebParam(name = "EUINVal", targetNamespace = "http://bsestarmf.in/")
        java.lang.String euinVal,
        @WebParam(name = "MinRedeem", targetNamespace = "http://bsestarmf.in/")
        java.lang.String minRedeem,
        @WebParam(name = "DPC", targetNamespace = "http://bsestarmf.in/")
        java.lang.String dpc,
        @WebParam(name = "IPAddress", targetNamespace = "http://bsestarmf.in/")
        java.lang.String ipAddress,
        @WebParam(name = "Password", targetNamespace = "http://bsestarmf.in/")
        java.lang.String password,
        @WebParam(name = "PassKey", targetNamespace = "http://bsestarmf.in/")
        java.lang.String passKey,
        @WebParam(name = "Param1", targetNamespace = "http://bsestarmf.in/")
        java.lang.String param1,
        @WebParam(name = "Param2", targetNamespace = "http://bsestarmf.in/")
        java.lang.String param2,
        @WebParam(name = "Param3", targetNamespace = "http://bsestarmf.in/")
        java.lang.String param3
    );

    @WebMethod(action = "http://bsestarmf.in/MFOrderEntry/orderEntryParam")
    @Action(input = "http://bsestarmf.in/MFOrderEntry/orderEntryParam", output = "http://bsestarmf.in/MFOrderEntry/orderEntryParamResponse")
    @RequestWrapper(localName = "orderEntryParam", targetNamespace = "http://bsestarmf.in/", className = "in.bsestarmf.OrderEntryParam")
    @ResponseWrapper(localName = "orderEntryParamResponse", targetNamespace = "http://bsestarmf.in/", className = "in.bsestarmf.OrderEntryParamResponse")
    @WebResult(name = "orderEntryParamResult", targetNamespace = "http://bsestarmf.in/")
    public java.lang.String orderEntryParam(
        @WebParam(name = "TransCode", targetNamespace = "http://bsestarmf.in/")
        java.lang.String transCode,
        @WebParam(name = "TransNo", targetNamespace = "http://bsestarmf.in/")
        java.lang.String transNo,
        @WebParam(name = "OrderId", targetNamespace = "http://bsestarmf.in/")
        java.lang.String orderId,
        @WebParam(name = "UserID", targetNamespace = "http://bsestarmf.in/")
        java.lang.String userID,
        @WebParam(name = "MemberId", targetNamespace = "http://bsestarmf.in/")
        java.lang.String memberId,
        @WebParam(name = "ClientCode", targetNamespace = "http://bsestarmf.in/")
        java.lang.String clientCode,
        @WebParam(name = "SchemeCd", targetNamespace = "http://bsestarmf.in/")
        java.lang.String schemeCd,
        @WebParam(name = "BuySell", targetNamespace = "http://bsestarmf.in/")
        java.lang.String buySell,
        @WebParam(name = "BuySellType", targetNamespace = "http://bsestarmf.in/")
        java.lang.String buySellType,
        @WebParam(name = "DPTxn", targetNamespace = "http://bsestarmf.in/")
        java.lang.String dpTxn,
        @WebParam(name = "OrderVal", targetNamespace = "http://bsestarmf.in/")
        java.lang.String orderVal,
        @WebParam(name = "Qty", targetNamespace = "http://bsestarmf.in/")
        java.lang.String qty,
        @WebParam(name = "AllRedeem", targetNamespace = "http://bsestarmf.in/")
        java.lang.String allRedeem,
        @WebParam(name = "FolioNo", targetNamespace = "http://bsestarmf.in/")
        java.lang.String folioNo,
        @WebParam(name = "Remarks", targetNamespace = "http://bsestarmf.in/")
        java.lang.String remarks,
        @WebParam(name = "KYCStatus", targetNamespace = "http://bsestarmf.in/")
        java.lang.String kycStatus,
        @WebParam(name = "RefNo", targetNamespace = "http://bsestarmf.in/")
        java.lang.String refNo,
        @WebParam(name = "SubBrCode", targetNamespace = "http://bsestarmf.in/")
        java.lang.String subBrCode,
        @WebParam(name = "EUIN", targetNamespace = "http://bsestarmf.in/")
        java.lang.String euin,
        @WebParam(name = "EUINVal", targetNamespace = "http://bsestarmf.in/")
        java.lang.String euinVal,
        @WebParam(name = "MinRedeem", targetNamespace = "http://bsestarmf.in/")
        java.lang.String minRedeem,
        @WebParam(name = "DPC", targetNamespace = "http://bsestarmf.in/")
        java.lang.String dpc,
        @WebParam(name = "IPAdd", targetNamespace = "http://bsestarmf.in/")
        java.lang.String ipAdd,
        @WebParam(name = "Password", targetNamespace = "http://bsestarmf.in/")
        java.lang.String password,
        @WebParam(name = "PassKey", targetNamespace = "http://bsestarmf.in/")
        java.lang.String passKey,
        @WebParam(name = "Parma1", targetNamespace = "http://bsestarmf.in/")
        java.lang.String parma1,
        @WebParam(name = "Param2", targetNamespace = "http://bsestarmf.in/")
        java.lang.String param2,
        @WebParam(name = "Param3", targetNamespace = "http://bsestarmf.in/")
        java.lang.String param3
    );

    @WebMethod(action = "http://bsestarmf.in/MFOrderEntry/xsipOrderEntryParam")
    @Action(input = "http://bsestarmf.in/MFOrderEntry/xsipOrderEntryParam", output = "http://bsestarmf.in/MFOrderEntry/xsipOrderEntryParamResponse")
    @RequestWrapper(localName = "xsipOrderEntryParam", targetNamespace = "http://bsestarmf.in/", className = "in.bsestarmf.XsipOrderEntryParam")
    @ResponseWrapper(localName = "xsipOrderEntryParamResponse", targetNamespace = "http://bsestarmf.in/", className = "in.bsestarmf.XsipOrderEntryParamResponse")
    @WebResult(name = "xsipOrderEntryParamResult", targetNamespace = "http://bsestarmf.in/")
    public java.lang.String xsipOrderEntryParam(
        @WebParam(name = "TransactionCode", targetNamespace = "http://bsestarmf.in/")
        java.lang.String transactionCode,
        @WebParam(name = "UniqueRefNo", targetNamespace = "http://bsestarmf.in/")
        java.lang.String uniqueRefNo,
        @WebParam(name = "SchemeCode", targetNamespace = "http://bsestarmf.in/")
        java.lang.String schemeCode,
        @WebParam(name = "MemberCode", targetNamespace = "http://bsestarmf.in/")
        java.lang.String memberCode,
        @WebParam(name = "ClientCode", targetNamespace = "http://bsestarmf.in/")
        java.lang.String clientCode,
        @WebParam(name = "UserId", targetNamespace = "http://bsestarmf.in/")
        java.lang.String userId,
        @WebParam(name = "InternalRefNo", targetNamespace = "http://bsestarmf.in/")
        java.lang.String internalRefNo,
        @WebParam(name = "TransMode", targetNamespace = "http://bsestarmf.in/")
        java.lang.String transMode,
        @WebParam(name = "DpTxnMode", targetNamespace = "http://bsestarmf.in/")
        java.lang.String dpTxnMode,
        @WebParam(name = "StartDate", targetNamespace = "http://bsestarmf.in/")
        java.lang.String startDate,
        @WebParam(name = "FrequencyType", targetNamespace = "http://bsestarmf.in/")
        java.lang.String frequencyType,
        @WebParam(name = "FrequencyAllowed", targetNamespace = "http://bsestarmf.in/")
        java.lang.String frequencyAllowed,
        @WebParam(name = "InstallmentAmount", targetNamespace = "http://bsestarmf.in/")
        java.lang.String installmentAmount,
        @WebParam(name = "NoOfInstallment", targetNamespace = "http://bsestarmf.in/")
        java.lang.String noOfInstallment,
        @WebParam(name = "Remarks", targetNamespace = "http://bsestarmf.in/")
        java.lang.String remarks,
        @WebParam(name = "FolioNo", targetNamespace = "http://bsestarmf.in/")
        java.lang.String folioNo,
        @WebParam(name = "FirstOrderFlag", targetNamespace = "http://bsestarmf.in/")
        java.lang.String firstOrderFlag,
        @WebParam(name = "Brokerage", targetNamespace = "http://bsestarmf.in/")
        java.lang.String brokerage,
        @WebParam(name = "MandateID", targetNamespace = "http://bsestarmf.in/")
        java.lang.String mandateID,
        @WebParam(name = "SubberCode", targetNamespace = "http://bsestarmf.in/")
        java.lang.String subberCode,
        @WebParam(name = "Euin", targetNamespace = "http://bsestarmf.in/")
        java.lang.String euin,
        @WebParam(name = "EuinVal", targetNamespace = "http://bsestarmf.in/")
        java.lang.String euinVal,
        @WebParam(name = "DPC", targetNamespace = "http://bsestarmf.in/")
        java.lang.String dpc,
        @WebParam(name = "XsipRegID", targetNamespace = "http://bsestarmf.in/")
        java.lang.String xsipRegID,
        @WebParam(name = "IPAdd", targetNamespace = "http://bsestarmf.in/")
        java.lang.String ipAdd,
        @WebParam(name = "Password", targetNamespace = "http://bsestarmf.in/")
        java.lang.String password,
        @WebParam(name = "PassKey", targetNamespace = "http://bsestarmf.in/")
        java.lang.String passKey,
        @WebParam(name = "Param1", targetNamespace = "http://bsestarmf.in/")
        java.lang.String param1,
        @WebParam(name = "Param2", targetNamespace = "http://bsestarmf.in/")
        java.lang.String param2,
        @WebParam(name = "Param3", targetNamespace = "http://bsestarmf.in/")
        java.lang.String param3
    );
}
