ALTER TABLE `go4wealthdb`.`user` CHANGE `MOBILE_NUMBER` `MOBILE_NUMBER` VARCHAR(15) NULL;

ALTER TABLE top_schemes CHANGE FIELD2 CREATED_DATE Date NULL
ALTER TABLE top_schemes CHANGE FIELD3 DEACTIVATED_DATE Date NULL

ALTER TABLE `go4wealthdb`.`address_proof` ADD COLUMN `MOBILE_WITH_AADHAAR` VARCHAR(50) NULL;
ALTER TABLE `go4wealthdb`.`address_proof` ADD COLUMN `VERIFIED` VARCHAR(50) NULL;

SELECT COUNT(*) FROM scheme;   -- 26219

SELECT COUNT(*) FROM scheme WHERE scheme_plan='DIRECT';  -- 9345

DELETE FROM scheme WHERE scheme_plan='DIRECT';


UPDATE scheme SET AMFI_CODE='113545' WHERE ISIN='INF251K01902';
UPDATE scheme SET AMFI_CODE='113561' WHERE ISIN='INF251K01860';
UPDATE scheme SET AMFI_CODE='113562' WHERE ISIN='INF251K01886';
UPDATE scheme SET AMFI_CODE='117961' WHERE ISIN='INF251K01EC7';
UPDATE scheme SET AMFI_CODE='117962' WHERE ISIN='INF251K01EE3';
UPDATE scheme SET AMFI_CODE='113548' WHERE ISIN='INF251K01CU3';
UPDATE scheme SET AMFI_CODE='117956' WHERE ISIN='INF251K01CY5';
UPDATE scheme SET AMFI_CODE='117955' WHERE ISIN='INF251K01DB1';
UPDATE scheme SET AMFI_CODE='130465' WHERE ISIN='INF251K01NG9';
UPDATE scheme SET AMFI_CODE='130473' WHERE ISIN='INF251K01NK1';
UPDATE scheme SET AMFI_CODE='130471' WHERE ISIN='INF251K01NI5';
UPDATE scheme SET AMFI_CODE='130476' WHERE ISIN='INF251K01NN5';
UPDATE scheme SET AMFI_CODE='113461' WHERE ISIN='INF251K01969';
UPDATE scheme SET AMFI_CODE='113549' WHERE ISIN='INF251K01CS7';
UPDATE scheme SET AMFI_CODE='113477' WHERE ISIN='INF251K01DN6';
UPDATE scheme SET AMFI_CODE='113478' WHERE ISIN='INF251K01DP1';
UPDATE scheme SET AMFI_CODE='117946' WHERE ISIN='INF251K01DT3';
UPDATE scheme SET AMFI_CODE='117947' WHERE ISIN='INF251K01DV9';
UPDATE scheme SET AMFI_CODE='113464' WHERE ISIN='INF251K01993';
UPDATE scheme SET AMFI_CODE='117958' WHERE ISIN='INF251K01DX5';
UPDATE scheme SET AMFI_CODE='117959' WHERE ISIN='INF251K01DY3';
UPDATE scheme SET AMFI_CODE='113567' WHERE ISIN='INF251K01AY9';
UPDATE scheme SET AMFI_CODE='130474' WHERE ISIN='INF251K01NL9';
UPDATE scheme SET AMFI_CODE='117954' WHERE ISIN='INF251K01CZ2';
UPDATE scheme SET AMFI_CODE='117944' WHERE ISIN='INF251K01DR7';
UPDATE scheme SET AMFI_CODE='113483' WHERE ISIN='INF251K01DM8';
UPDATE scheme SET AMFI_CODE='113557' WHERE ISIN='INF251K01CW9';
UPDATE scheme SET AMFI_CODE='114105' WHERE ISIN='INF251K01EK0';
UPDATE scheme SET AMFI_CODE='114097' WHERE ISIN='INF251K01EM6';
UPDATE scheme SET AMFI_CODE='114100' WHERE ISIN='INF251K01EO2';
UPDATE scheme SET AMFI_CODE='117950' WHERE ISIN='INF251K01ER5';
UPDATE scheme SET AMFI_CODE='117948' WHERE ISIN='INF251K01ET1';
UPDATE scheme SET AMFI_CODE='117949' WHERE ISIN='INF251K01EV7';
UPDATE scheme SET AMFI_CODE='113528' WHERE ISIN='INF251K01EH6';
UPDATE scheme SET AMFI_CODE='103154' WHERE ISIN='INF209K01EE1';
UPDATE scheme SET AMFI_CODE='103164' WHERE ISIN='INF209K01CB1';
UPDATE scheme SET AMFI_CODE='103165' WHERE ISIN='INF209K01DT1';
UPDATE scheme SET AMFI_CODE='103184' WHERE ISIN='INF209K01DX3';
UPDATE scheme SET AMFI_CODE='103186' WHERE ISIN='INF209K01DY1';
UPDATE scheme SET AMFI_CODE='103167' WHERE ISIN='INF209K01CD7';
UPDATE scheme SET AMFI_CODE='103183' WHERE ISIN='INF209K01DL8';
UPDATE scheme SET AMFI_CODE='103173' WHERE ISIN='INF209K01EC5';
UPDATE scheme SET AMFI_CODE='103194' WHERE ISIN='INF209K01KG3';
UPDATE scheme SET AMFI_CODE='103193' WHERE ISIN='INF209KA1LQ4';
UPDATE scheme SET AMFI_CODE='103191' WHERE ISIN='INF209K01KD0';
UPDATE scheme SET AMFI_CODE='133799' WHERE ISIN='INF178L01079';
UPDATE scheme SET AMFI_CODE='133814' WHERE ISIN='INF178L01137';
UPDATE scheme SET AMFI_CODE='100063' WHERE ISIN='INF209K01CL0';
UPDATE scheme SET AMFI_CODE='100065' WHERE ISIN='INF209K01CK2';
UPDATE scheme SET AMFI_CODE='108764' WHERE ISIN='INF194K01IS6';
UPDATE scheme SET AMFI_CODE='108767' WHERE ISIN='INF194K01HG3';
UPDATE scheme SET AMFI_CODE='108766' WHERE ISIN='INF194K01IM9';
UPDATE scheme SET AMFI_CODE='108763' WHERE ISIN='INF194K01IP2';
UPDATE scheme SET AMFI_CODE='108644' WHERE ISIN='INF194K01FB8';
UPDATE scheme SET AMFI_CODE='108646' WHERE ISIN='INF194K01FE2';
UPDATE scheme SET AMFI_CODE='108757' WHERE ISIN='INF194K01LN1';
UPDATE scheme SET AMFI_CODE='108561' WHERE ISIN='INF194K01QH2';
UPDATE scheme SET AMFI_CODE='108557' WHERE ISIN='INF194K01EG0';
UPDATE scheme SET AMFI_CODE='108675' WHERE ISIN='INF194K01QK6';
UPDATE scheme SET AMFI_CODE='108558' WHERE ISIN='INF194K01EA3';
UPDATE scheme SET AMFI_CODE='108650' WHERE ISIN='INF194K01LK7';
UPDATE scheme SET AMFI_CODE='108701' WHERE ISIN='INF194K01LQ4';
UPDATE scheme SET AMFI_CODE='108730' WHERE ISIN='INF194K01KE2';
UPDATE scheme SET AMFI_CODE='108662' WHERE ISIN='INF194K01EQ9';
UPDATE scheme SET AMFI_CODE='108663' WHERE ISIN='INF194K01EN6';
UPDATE scheme SET AMFI_CODE='108692' WHERE ISIN='INF194K01VY7';
UPDATE scheme SET AMFI_CODE='108737' WHERE ISIN='INF194K01NS6';
UPDATE scheme SET AMFI_CODE='108738' WHERE ISIN='INF194K01NP2';
UPDATE scheme SET AMFI_CODE='108544' WHERE ISIN='INF194K01SJ4';
UPDATE scheme SET AMFI_CODE='108546' WHERE ISIN='INF194K01SH8';
UPDATE scheme SET AMFI_CODE='108547' WHERE ISIN='INF194K01SF2';
UPDATE scheme SET AMFI_CODE='108739' WHERE ISIN='INF194K01OB0';
UPDATE scheme SET AMFI_CODE='108693' WHERE ISIN='INF194K01WE7';
UPDATE scheme SET AMFI_CODE='108597' WHERE ISIN='INF194K01540';
UPDATE scheme SET AMFI_CODE='108740' WHERE ISIN='INF194K01NY4';
UPDATE scheme SET AMFI_CODE='108595' WHERE ISIN='INF194K01417';
UPDATE scheme SET AMFI_CODE='108633' WHERE ISIN='INF194K01FV6';
UPDATE scheme SET AMFI_CODE='108634' WHERE ISIN='INF194K01GB6';
UPDATE scheme SET AMFI_CODE='108635' WHERE ISIN='INF194K01FY0';
UPDATE scheme SET AMFI_CODE='108593' WHERE ISIN='INF194K01482';
UPDATE scheme SET AMFI_CODE='108800' WHERE ISIN='INF194K01508';
UPDATE scheme SET AMFI_CODE='108729' WHERE ISIN='INF194K01KH5';
UPDATE scheme SET AMFI_CODE='108727' WHERE ISIN='INF194K01KB8';
UPDATE scheme SET AMFI_CODE='108713' WHERE ISIN='INF194K01HJ7';
UPDATE scheme SET AMFI_CODE='108847' WHERE ISIN='INF194K01664';
UPDATE scheme SET AMFI_CODE='108742' WHERE ISIN='INF194K01NV0';
UPDATE scheme SET AMFI_CODE='108731' WHERE ISIN='INF194K01JV8';
UPDATE scheme SET AMFI_CODE='108908' WHERE ISIN='INF194K01367';
UPDATE scheme SET AMFI_CODE='108992' WHERE ISIN='INF194K01607';
UPDATE scheme SET AMFI_CODE='108691' WHERE ISIN='INF194K01WH0';
UPDATE scheme SET AMFI_CODE='111343' WHERE ISIN='INF194K01FH5';
UPDATE scheme SET AMFI_CODE='111570' WHERE ISIN='INF194K01318';
UPDATE scheme SET AMFI_CODE='111523' WHERE ISIN='INF194K01QN0';
UPDATE scheme SET AMFI_CODE='111527' WHERE ISIN='INF194K01EJ4';
UPDATE scheme SET AMFI_CODE='111971' WHERE ISIN='INF761K01CO4';
UPDATE scheme SET AMFI_CODE='111970' WHERE ISIN='INF761K01CW7';
UPDATE scheme SET AMFI_CODE='109255' WHERE ISIN='INF761K01CP1';
UPDATE scheme SET AMFI_CODE='109264' WHERE ISIN='INF761K01CX5';
UPDATE scheme SET AMFI_CODE='110607' WHERE ISIN='INF761K01090';
UPDATE scheme SET AMFI_CODE='110598' WHERE ISIN='INF761K01124';

ALTER TABLE scheme add column DISPLAY VARCHAR(50) DEFAULT NULL;

ALTER TABLE scheme add column PRIORITY VARCHAR(50) DEFAULT NULL;
ALTER TABLE `go4wealthdb`.`onboarding_status` CHANGE `FIELD1` `ISIP_MANDATE_NUMBER` VARCHAR(512) NULL;
ALTER TABLE `go4wealthdb`.`onboarding_status` CHANGE `FIELD2` `ISIP_MANDATE_RESPONSE` VARCHAR(128) NULL;
ALTER TABLE `go4wealthdb`.`onboarding_status` CHANGE `FIELD3` `ISIP_MANDATE_STATUS` INT(50) NULL;

ALTER TABLE daily_transaction_report_userdata ADD FIELD1 VARCHAR(126) DEFAULT NULL;
ALTER TABLE daily_transaction_report_userdata ADD FIELD2 VARCHAR(126) DEFAULT NULL;
ALTER TABLE daily_transaction_report_userdata ADD FIELD3 VARCHAR(126) DEFAULT NULL;
ALTER TABLE daily_transaction_report_userdata ADD FIELD4 INT(126) DEFAULT NULL;
ALTER TABLE daily_transaction_report_userdata ADD FIELD5 DECIMAL(20,5) DEFAULT NULL;

ALTER TABLE daily_transaction_report_trxndata ADD FIELD1 VARCHAR(126) DEFAULT NULL;
ALTER TABLE daily_transaction_report_trxndata ADD FIELD2 VARCHAR(126) DEFAULT NULL;
ALTER TABLE daily_transaction_report_trxndata ADD FIELD3 VARCHAR(126) DEFAULT NULL;
ALTER TABLE daily_transaction_report_trxndata ADD FIELD4 INT(126) DEFAULT NULL;
ALTER TABLE daily_transaction_report_trxndata ADD FIELD5 DECIMAL(20,5) DEFAULT NULL;


ALTER TABLE daily_transaction_report_extradata ADD FIELD1 VARCHAR(126) DEFAULT NULL;
ALTER TABLE daily_transaction_report_extradata ADD FIELD2 VARCHAR(126) DEFAULT NULL;
ALTER TABLE daily_transaction_report_extradata ADD FIELD3 VARCHAR(126) DEFAULT NULL;
ALTER TABLE daily_transaction_report_extradata ADD FIELD4 INT(126) DEFAULT NULL;
ALTER TABLE daily_transaction_report_extradata ADD FIELD5 DECIMAL(20,5) DEFAULT NULL;


ALTER TABLE `go4wealthdb`.`ppcpaytran` CHANGE `FIELD3` `USER_ID` INT(50) NULL;

ALTER TABLE `go4wealthdb`.`bank_details` MODIFY COLUMN `START_DATE` DATE DEFAULT NULL;
ALTER TABLE `go4wealthdb`.`bank_details` MODIFY COLUMN `END_DATE` DATE DEFAULT NULL;

ALTER TABLE daily_transaction_report_userdata ADD USER_TRXN_NO VARCHAR(126) DEFAULT NULL;
ALTER TABLE daily_transaction_report_trxndata ADD STATUS VARCHAR(126) DEFAULT NULL;
ALTER TABLE daily_transaction_report_extradata ADD STATUS VARCHAR(126) DEFAULT NULL;

ALTER TABLE `go4wealthdb`.`daily_transaction_report_redumption_data` CHANGE `FIELD1` `BSE_ORDER_ID` VARCHAR(50) NULL;

INSERT INTO `store_conf` (`STORE_CONF_ID`,`KEYWORD`,`KEYWORD_VALUE`) VALUES (16,'HOMEVIDEO_LOCATION','/videos');
INSERT INTO `store_conf` (`STORE_CONF_ID`,`KEYWORD`,`KEYWORD_VALUE`) VALUES (17,'HOMEVIDEO_URL','//www.youtube.com/embed/z9sPGHw_uw0');

/** New Alter **/
ALTER TABLE goal_order_items ADD CURRENT_COST decimal(20,5) DEFAULT NULL;

ALTER TABLE GOALS_ORDER ADD COLUMN `STATUS` CHAR(3) NOT NULL;

ALTER TABLE goals ADD COLUMN `GOAL_TYPE` CHAR(3) NOT NULL DEFAULT 'PD';
ALTER TABLE goals ADD COLUMN `DURATION` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE USER_ASSET_ITEMS ADD COLUMN `future_value` DECIMAL(20,5) NOT NULL;


/** New Alter Command **/
ALTER TABLE goals ADD COLUMN `GOAL_KEY` VARCHAR(50) DEFAULT NULL;

UPDATE goals SET GOAL_KEY='CP' WHERE GOAL_ID=1;
UPDATE goals SET GOAL_KEY='FIN' WHERE GOAL_ID=2;
UPDATE goals SET GOAL_KEY='POD' WHERE GOAL_ID=3;
UPDATE goals SET GOAL_KEY='SM' WHERE GOAL_ID=4;
UPDATE goals SET GOAL_KEY='VPD' WHERE GOAL_ID=5;
UPDATE goals SET GOAL_KEY='VPI' WHERE GOAL_ID=6;
UPDATE goals SET GOAL_KEY='FFF' WHERE GOAL_ID=7;
UPDATE goals SET GOAL_KEY='FTST' WHERE GOAL_ID=8;
UPDATE goals SET GOAL_KEY='DH' WHERE GOAL_ID=9;
UPDATE goals SET GOAL_KEY='M1C' WHERE GOAL_ID=10;
UPDATE goals SET GOAL_KEY='PC' WHERE GOAL_ID=11;
UPDATE goals SET GOAL_KEY='SOMB' WHERE GOAL_ID=12;
UPDATE goals SET GOAL_KEY='CHEA' WHERE GOAL_ID=13;
UPDATE goals SET GOAL_KEY='CHEI' WHERE GOAL_ID=14;
UPDATE goals SET GOAL_KEY='CDM' WHERE GOAL_ID=15;
UPDATE goals SET GOAL_KEY='MSH' WHERE GOAL_ID=16;
UPDATE goals SET GOAL_KEY='RP' WHERE GOAL_ID=17;


INSERT INTO `store_conf` (`STORE_CONF_ID`,`KEYWORD`,`KEYWORD_VALUE`) VALUES (18,'SMS_AUTH_KEY','232959AXeMBsNRmuR55b7bf5e4');
INSERT INTO `store_conf` (`STORE_CONF_ID`,`KEYWORD`,`KEYWORD_VALUE`) VALUES (19,'SENDGRID_API_KEY','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');
INSERT INTO `store_conf` (`STORE_CONF_ID`,`KEYWORD`,`KEYWORD_VALUE`) VALUES (20,'SENDGRID_SENDER_EMAIL','gaurav.pandey@moptra.com');



/** New Alter Command **/
ALTER TABLE top_schemes ADD COLUMN `scheme_category` VARCHAR(50) DEFAULT NULL;
UPDATE top_schemes SET scheme_category='Large Cap MF' WHERE top_schemes_id='1';
UPDATE top_schemes SET scheme_category='Mid Cap MF' WHERE top_schemes_id='2';
UPDATE top_schemes SET scheme_category='Small Cap MF' WHERE top_schemes_id='3';

/*** New Alter Query by vinod**/
ALTER TABLE `go4wealthdb`.`orders` ADD COLUMN `GOAL_NAME` VARCHAR(50) DEFAULT NULL;
ALTER TABLE `go4wealthdb`.`orders` ADD COLUMN `GOAL_ID` INT(50) DEFAULT NULL;

/** Payment based api**/
INSERT INTO `store_conf` (`STORE_CONF_ID`,`KEYWORD`,`KEYWORD_VALUE`) VALUES (21,'PAYMENT_PASSWORD_API_URL','http://www.bsestarmf.in/StarMFPaymentGatewayService/StarMFPaymentGatewayService.svc/GetPassword');
INSERT INTO `store_conf` (`STORE_CONF_ID`,`KEYWORD`,`KEYWORD_VALUE`) VALUES (22,'PAYMENT_REDIRECT_URL','https://go4wealth.com/transactions');
INSERT INTO `store_conf` (`STORE_CONF_ID`,`KEYWORD`,`KEYWORD_VALUE`) VALUES (23,'PAYMENT_API_URL','http://www.bsestarmf.in/StarMFPaymentGatewayService/StarMFPaymentGatewayService.svc/PaymentGatewayAPI');
INSERT INTO `store_conf` (`STORE_CONF_ID`,`KEYWORD`,`KEYWORD_VALUE`) VALUES (24,'CHILD_ORDER_PASSWORD_URL','http://www.bsestarmf.in/StarMFWebService/StarMFWebService.svc/GetPasswordForChildOrder');
INSERT INTO `store_conf` (`STORE_CONF_ID`,`KEYWORD`,`KEYWORD_VALUE`) VALUES (25,'CHILD_ORDER_API_URL','http://www.bsestarmf.in/StarMFWebService/StarMFWebService.svc/ChildOrderDetails');


/** New Alter **/
ALTER TABLE USER_ASSET_ITEMS MODIFY column `GOALS_ORDER_ID` int(50) DEFAULT NULL;
ALTER TABLE USER_ASSET_ITEMS MODIFY column `ASSET_CLASS_ID` int(50) DEFAULT NULL;
ALTER TABLE USER_ASSET_ITEMS MODIFY column `ASSET_VALUE` decimal(20,5) DEFAULT NULL;
ALTER TABLE USER_ASSET_ITEMS MODIFY column `future_value` decimal(20,5) DEFAULT NULL;

/** Aof Upload Related Query**/
INSERT INTO `store_conf` (`STORE_CONF_ID`,`KEYWORD`,`KEYWORD_VALUE`) VALUES (26,'AOF_GET_PASSWORD_URL','http://www.bsestarmf.in/StarMFFileUploadService/StarMFFileUploadService.svc/GetPassword');
INSERT INTO `store_conf` (`STORE_CONF_ID`,`KEYWORD`,`KEYWORD_VALUE`) VALUES (27,'AOF_UPLOAD_URL','http://www.bsestarmf.in/StarMFFileUploadService/StarMFFileUploadService.svc/UploadFile');

/** Later Query For State Table**/

ALTER TABLE address_state ADD COLUMN ADDRESS_STATE_CODE VARCHAR(5) NOT NULL;


UPDATE  address_state SET ADDRESS_STATE_CODE = 'JM' WHERE ADDRESS_STATENAME = 'JAMMU AND KASHMIR';
UPDATE  address_state SET ADDRESS_STATE_CODE = 'BH' WHERE ADDRESS_STATENAME = 'BIHAR';
UPDATE  address_state SET ADDRESS_STATE_CODE = 'SI' WHERE ADDRESS_STATENAME = 'SIKKIM';
UPDATE  address_state SET ADDRESS_STATE_CODE = 'AR' WHERE ADDRESS_STATENAME = 'ARUNACHAL PRADESH';
UPDATE  address_state SET ADDRESS_STATE_CODE = 'NA' WHERE ADDRESS_STATENAME = 'NAGALAND';
UPDATE  address_state SET ADDRESS_STATE_CODE = 'MN' WHERE ADDRESS_STATENAME = 'MANIPUR';
UPDATE  address_state SET ADDRESS_STATE_CODE = 'MI' WHERE ADDRESS_STATENAME = 'MIZORAM';
UPDATE  address_state SET ADDRESS_STATE_CODE = 'TR' WHERE ADDRESS_STATENAME = 'TRIPURA';
UPDATE  address_state SET ADDRESS_STATE_CODE = 'ME' WHERE ADDRESS_STATENAME = 'MEGHALAYA';
UPDATE  address_state SET ADDRESS_STATE_CODE = 'AS' WHERE ADDRESS_STATENAME = 'ASSAM';
UPDATE  address_state SET ADDRESS_STATE_CODE = 'WB' WHERE ADDRESS_STATENAME = 'WEST BENGAL';
UPDATE  address_state SET ADDRESS_STATE_CODE = 'HP' WHERE ADDRESS_STATENAME = 'HIMACHAL PRADESH';
UPDATE  address_state SET ADDRESS_STATE_CODE = 'JK' WHERE ADDRESS_STATENAME = 'JHARKHAND';
UPDATE  address_state SET ADDRESS_STATE_CODE = 'OR' WHERE ADDRESS_STATENAME = 'ODISHA';
UPDATE  address_state SET ADDRESS_STATE_CODE = 'CG' WHERE ADDRESS_STATENAME = 'CHHATTISGARH';
UPDATE  address_state SET ADDRESS_STATE_CODE = 'MP' WHERE ADDRESS_STATENAME = 'MADHYA PRADESH';
UPDATE  address_state SET ADDRESS_STATE_CODE = 'GU' WHERE ADDRESS_STATENAME = 'GUJARAT';
UPDATE  address_state SET ADDRESS_STATE_CODE = 'DD' WHERE ADDRESS_STATENAME = 'DAMAN AND DIU';
UPDATE  address_state SET ADDRESS_STATE_CODE = 'DN' WHERE ADDRESS_STATENAME = 'DADRA AND NAGAR HAVELI';
UPDATE  address_state SET ADDRESS_STATE_CODE = 'MA' WHERE ADDRESS_STATENAME = 'MAHARASHTRA';
UPDATE  address_state SET ADDRESS_STATE_CODE = 'AP' WHERE ADDRESS_STATENAME = 'ANDHRA PRADESH';
UPDATE  address_state SET ADDRESS_STATE_CODE = 'KA' WHERE ADDRESS_STATENAME = 'KARNATAKA';
UPDATE  address_state SET ADDRESS_STATE_CODE = 'PU' WHERE ADDRESS_STATENAME = 'PUNJAB';
UPDATE  address_state SET ADDRESS_STATE_CODE = 'GO' WHERE ADDRESS_STATENAME = 'GOA';
UPDATE  address_state SET ADDRESS_STATE_CODE = 'LD' WHERE ADDRESS_STATENAME = 'LAKSHADWEEP';
UPDATE  address_state SET ADDRESS_STATE_CODE = 'KE' WHERE ADDRESS_STATENAME = 'KERALA';
UPDATE  address_state SET ADDRESS_STATE_CODE = 'TN' WHERE ADDRESS_STATENAME = 'TAMIL NADU';
UPDATE  address_state SET ADDRESS_STATE_CODE = 'PO' WHERE ADDRESS_STATENAME = 'PUDUCHERRY';
UPDATE  address_state SET ADDRESS_STATE_CODE = 'AN' WHERE ADDRESS_STATENAME = 'ANDAMAN AND NICOBAR ISLANDS';
UPDATE  address_state SET ADDRESS_STATE_CODE = 'TG' WHERE ADDRESS_STATENAME = 'TELANGANA';
UPDATE  address_state SET ADDRESS_STATE_CODE = 'CH' WHERE ADDRESS_STATENAME = 'CHANDIGARH';
UPDATE  address_state SET ADDRESS_STATE_CODE = 'UC' WHERE ADDRESS_STATENAME = 'UTTARAKHAND';
UPDATE  address_state SET ADDRESS_STATE_CODE = 'HA' WHERE ADDRESS_STATENAME = 'HARYANA';
UPDATE  address_state SET ADDRESS_STATE_CODE = 'ND' WHERE ADDRESS_STATENAME = 'DELHI';
UPDATE  address_state SET ADDRESS_STATE_CODE = 'RA' WHERE ADDRESS_STATENAME = 'RAJASTHAN';
UPDATE  address_state SET ADDRESS_STATE_CODE = 'UP' WHERE ADDRESS_STATENAME = 'UTTAR PRADESH';
UPDATE  address_state SET ADDRESS_STATE_CODE = 'OH' WHERE ADDRESS_STATENAME = 'Others';


/** New Alter Command **/
UPDATE goals  SET GOAL_NAME='Car Purchase', GOAL_BUCKET_ID=1, COST_OF_GOAL=1000000.00000 WHERE GOAL_ID=1;
UPDATE goals  SET GOAL_NAME='Fund in Need (Emergency Fund)', GOAL_BUCKET_ID=1, COST_OF_GOAL=500000.00000 WHERE GOAL_ID=2;
UPDATE goals  SET GOAL_NAME='Pay Off Debt', GOAL_BUCKET_ID=1, COST_OF_GOAL=0.00000 WHERE GOAL_ID=3;
UPDATE goals  SET GOAL_NAME='Self Marriage', GOAL_BUCKET_ID=1, COST_OF_GOAL=1000000.00000 WHERE GOAL_ID=4;
UPDATE goals  SET GOAL_NAME='Vacation Planning-Domestic', GOAL_BUCKET_ID=1, COST_OF_GOAL=250000.00000 WHERE GOAL_ID=5;
UPDATE goals  SET GOAL_NAME='Vacation Planning-International', GOAL_BUCKET_ID=1, COST_OF_GOAL=500000.00000 WHERE GOAL_ID=6;
UPDATE goals  SET GOAL_NAME='Fund for Fun - TV/Appliance/Decor', GOAL_BUCKET_ID=1, COST_OF_GOAL=250000.00000 WHERE GOAL_ID=7;
UPDATE goals  SET GOAL_NAME='Fund to Save Tax', GOAL_BUCKET_ID=1, COST_OF_GOAL=100000.00000 WHERE GOAL_ID=8;
UPDATE goals  SET GOAL_NAME='Dream Home', GOAL_BUCKET_ID=2, COST_OF_GOAL=5000000.00000 WHERE GOAL_ID=9;
UPDATE goals  SET GOAL_NAME='My 1st Cr', GOAL_BUCKET_ID=2, COST_OF_GOAL=10000000.00000 WHERE GOAL_ID=10;
UPDATE goals  SET GOAL_NAME='Philanthrophy & Charity', GOAL_BUCKET_ID=2, COST_OF_GOAL=250000.00000 WHERE GOAL_ID=11;
UPDATE goals  SET GOAL_NAME='Starting my own Business', GOAL_BUCKET_ID=2, COST_OF_GOAL=2000000.00000 WHERE GOAL_ID=12;
UPDATE goals  SET GOAL_NAME='Child Higher Education-Abroad', GOAL_BUCKET_ID=3, COST_OF_GOAL=4000000.00000 WHERE GOAL_ID=13;
UPDATE goals  SET GOAL_NAME='Child Higher Education-India', GOAL_BUCKET_ID=3, COST_OF_GOAL=1500000.00000 WHERE GOAL_ID=14;
UPDATE goals  SET GOAL_NAME='Children Dream Marriage', GOAL_BUCKET_ID=3, COST_OF_GOAL=2500000.00000 WHERE GOAL_ID=15;
UPDATE goals  SET GOAL_NAME='My Second Home', GOAL_BUCKET_ID=3, COST_OF_GOAL=10000000.00000 WHERE GOAL_ID=16;
UPDATE goals  SET GOAL_NAME='Retirement Planning', GOAL_BUCKET_ID=3, COST_OF_GOAL=5000000.00000 WHERE GOAL_ID=17;

/**  New Schemes Commands***/
ALTER TABLE scheme ADD COLUMN `SIP_TRANSACTION_MODE` VARCHAR(50) NULL;
ALTER TABLE scheme ADD COLUMN `SIP_FREQUENCY` VARCHAR(50) NULL;
ALTER TABLE scheme ADD COLUMN `SIP_DATES` VARCHAR(500) NULL;
ALTER TABLE scheme ADD COLUMN `SIP_MINIMUM_GAP` VARCHAR(50) NULL;
ALTER TABLE scheme ADD COLUMN `SIP_MAXIMUM_GAP` VARCHAR(50) NULL;
ALTER TABLE scheme ADD COLUMN `SIP_INSTALLMENT_GAP` VARCHAR(50) NULL;
ALTER TABLE scheme ADD COLUMN `SIP_STATUS` VARCHAR(50) NULL;
ALTER TABLE scheme ADD COLUMN `SIP_MINIMUM_INSTALLMENT_AMOUNT` DECIMAL(20,5) NULL;
ALTER TABLE scheme ADD COLUMN `SIP_MAXIMUM_INSTALLMENT_AMOUNT` DECIMAL(20,5) NULL;
ALTER TABLE scheme ADD COLUMN `SIP_MULTIPLIER_AMOUNT` VARCHAR(50) NULL;
ALTER TABLE scheme ADD COLUMN `SIP_MINIMUM_INSTALLMENT_NUMBERS` VARCHAR(50) NULL;
ALTER TABLE scheme ADD COLUMN `SIP_MAXIMUM_INSTALLMENT_NUMBERS` VARCHAR(50) NULL;


/** New Alter Command **/
INSERT INTO `store_conf` (`STORE_CONF_ID`,`KEYWORD`,`KEYWORD_VALUE`) VALUES (28,'REGISTERED_USER_EXCEL_REPORT_LOCATION','/registered-users-excel');

/** New Insert Command **/
INSERT INTO `store_conf` (`STORE_CONF_ID`,`KEYWORD`,`KEYWORD_VALUE`) VALUES (29,'EMAIL_TO_SEND_USER_REPORT','manu@go4wealth.com');

/**New Api's Url**/
INSERT INTO `store_conf` (`STORE_CONF_ID`,`KEYWORD`,`KEYWORD_VALUE`) VALUES (30,'ORDER_STATUS_API_URL','http://bsestarmf.in/StarMFWebService/StarMFWebService.svc/OrderStatus');
INSERT INTO `store_conf` (`STORE_CONF_ID`,`KEYWORD`,`KEYWORD_VALUE`) VALUES (31,'ALLOTMENT_STATEMENT_API_URL','http://bsestarmf.in/StarMFWebService/StarMFWebService.svc/AllotmentStatement');
INSERT INTO `store_conf` (`STORE_CONF_ID`,`KEYWORD`,`KEYWORD_VALUE`) VALUES (32,'GET_TOKEN_ACCESS_API_URL','http://bsestarmf.in/StarMFWebService/StarMFWebService.svc/GetAccessToken');
INSERT INTO `store_conf` (`STORE_CONF_ID`,`KEYWORD`,`KEYWORD_VALUE`) VALUES (33,'MANDATE_DETAIL_API_URL','http://bsestarmf.in/StarMFWebService/StarMFWebService.svc/MandateDetails');

/***New Tables for report***/


CREATE TABLE `order_status_report_userdata` (
	  `Order_Status_Report_Userdata_Id` INT(50) NOT NULL AUTO_INCREMENT,
	  `ALL_Units` VARCHAR(126) DEFAULT NULL,
	  `Amount` INT(50) DEFAULT NULL,
	  `Buy_Sell` VARCHAR(126) DEFAULT NULL,
	  `Buy_Sell_Type` VARCHAR(126) DEFAULT NULL,
	  `Client_Code` VARCHAR(126) DEFAULT NULL,
	  `Client_Name` VARCHAR(126) DEFAULT NULL,
	  `DPC` VARCHAR(126) DEFAULT NULL,
	  `DPFolio_No` VARCHAR(126) DEFAULT NULL,
	  `DPTrans` VARCHAR(126) DEFAULT NULL,
	  `Date` VARCHAR(126) DEFAULT NULL,
	  `EUIN` VARCHAR(126) DEFAULT NULL,
	  `EUIN_Decl` VARCHAR(126) DEFAULT NULL,
	  `Entry_By` VARCHAR(126) DEFAULT NULL,
	`First_Order` VARCHAR(126) DEFAULT NULL,
	`Folio_No` VARCHAR(126) DEFAULT NULL,
	`ISIN` VARCHAR(126) DEFAULT NULL,
	`Internal_RefNo` VARCHAR(126) DEFAULT NULL,
	`KYC_Flag` VARCHAR(126) DEFAULT NULL,
	`MIN_Redeem_Flag` VARCHAR(126) DEFAULT NULL,
	`Member_Code` VARCHAR(126) DEFAULT NULL,
	`Member_Remarks` VARCHAR(126) DEFAULT NULL,
	`Order_Number` VARCHAR(126) DEFAULT NULL,
	`Order_Remarks` VARCHAR(126) DEFAULT NULL,
	`Order_Status` VARCHAR(126) DEFAULT NULL,
	`Order_Type` VARCHAR(126) DEFAULT NULL,
	`SIPRegn_Date` VARCHAR(126) DEFAULT NULL,
	`SIP_Regn_No` BIGINT(50) DEFAULT NULL,
	`Scheme_Code` VARCHAR(126) DEFAULT NULL,
	`Scheme_Name` VARCHAR(126) DEFAULT NULL,
	`Sett_No` VARCHAR(126) DEFAULT NULL,
	`Sett_Type` VARCHAR(126) DEFAULT NULL,
	`Sub_Br_Code` VARCHAR(126) DEFAULT NULL,
	`Sub_Broker_ARN_Code` VARCHAR(126) DEFAULT NULL,
	`Sub_Order_Type` VARCHAR(126) DEFAULT NULL,
	`Time` VARCHAR(126) DEFAULT NULL,
	`Units` INT(126) DEFAULT NULL,
	  `FIELD1` VARCHAR(126) DEFAULT NULL,
	  `FIELD2` VARCHAR(126) DEFAULT NULL,
	  `FIELD3` VARCHAR(126) DEFAULT NULL,
	  `FIELD4` INT(126) DEFAULT NULL,
	  `FIELD5` DECIMAL(20,5) DEFAULT NULL,
	  PRIMARY KEY (`Order_Status_Report_Userdata_Id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;


CREATE TABLE `allotment_status_report_userdata` (
	  `Allotment_Status_Report_Userdata_Id` INT(50) NOT NULL AUTO_INCREMENT,
	  `Allotted_Amt` decimal(20,3) DEFAULT NULL,
	  `Allotted_Nav` decimal(20,3) DEFAULT NULL,
	  `Allotted_Unit` decimal(20,3) DEFAULT NULL,
	  `Amount` decimal(20,3) DEFAULT NULL,
	  `Beneficiary_Id` VARCHAR(126) DEFAULT NULL,
	  `Branch_Code` VARCHAR(126) DEFAULT NULL,
	  `Client_Code` VARCHAR(126) DEFAULT NULL,
	  `Client_Name` VARCHAR(126) DEFAULT NULL,
	  `DPC_Flag` VARCHAR(126) DEFAULT NULL,
	  `DP_Trans` VARCHAR(126) DEFAULT NULL,
	  `EUIN` VARCHAR(126) DEFAULT NULL,
	  `EUIN_Decl` VARCHAR(126) DEFAULT NULL,
	  `Folio_No` VARCHAR(126) DEFAULT NULL,
	`ISIN` VARCHAR(126) DEFAULT NULL,
	`Internal_Ref_No` VARCHAR(126) DEFAULT NULL,
	`KYC_Flag` VARCHAR(126) DEFAULT NULL,
	`Member_Code` VARCHAR(126) DEFAULT NULL,
	`Order_Date` VARCHAR(126) DEFAULT NULL,
	`Order_No` INT(50) DEFAULT NULL,
	`Order_Type` VARCHAR(126) DEFAULT NULL,
	`Qty` INT(50) DEFAULT NULL,
	`RTA_Scheme_Code` VARCHAR(126) DEFAULT NULL,
	`RTA_Trans_No` VARCHAR(126) DEFAULT NULL,
	`Remarks` VARCHAR(126) DEFAULT NULL,
	`Report_Date` VARCHAR(126) DEFAULT NULL,
	`SIP_Regn_Date` VARCHAR(126) DEFAULT NULL,
	`SIP_Regn_No` BIGINT(50) DEFAULT NULL,
	`STT` INT(126) DEFAULT NULL,
	`Scheme_Code` VARCHAR(126) DEFAULT NULL,
	`Sett_No` VARCHAR(126) DEFAULT NULL,
	`Sett_Type` VARCHAR(126) DEFAULT NULL,
	`Sub_Br_Code` VARCHAR(126) DEFAULT NULL,
	`Sub_Order_Type` VARCHAR(126) DEFAULT NULL,
	`User_Id` INT(50) DEFAULT NULL,
	`Valid_Flag` VARCHAR(126) DEFAULT NULL,
	  `FIELD1` VARCHAR(126) DEFAULT NULL,
	  `FIELD2` VARCHAR(126) DEFAULT NULL,
	  `FIELD3` VARCHAR(126) DEFAULT NULL,
	  `FIELD4` INT(126) DEFAULT NULL,
	  `FIELD5` DECIMAL(20,5) DEFAULT NULL,
	  PRIMARY KEY (`Allotment_Status_Report_Userdata_Id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;


/** New Alter Command **/
ALTER TABLE `go4wealthdb`.`onboarding_status` ADD COLUMN `ENACH_STATUS` VARCHAR(512) default NULL;
ALTER TABLE `go4wealthdb`.`onboarding_status` ADD COLUMN `FIELD2` VARCHAR(512) default NULL;
ALTER TABLE `go4wealthdb`.`onboarding_status` ADD COLUMN `FIELD3` VARCHAR(512) default NULL;


CREATE TABLE `user_additional_bankinfo` (
  `USER_ADDITIONAL_BANKINFO_ID` INT(50) NOT NULL AUTO_INCREMENT,
  `USERID` INT(50) NOT NULL,
  `BANK_NAME` VARCHAR(512) DEFAULT NULL,
  `BANK_BRANCH` VARCHAR(512) DEFAULT NULL,
  `BANK_ADDRESS` VARCHAR(512) DEFAULT NULL,
  `IFSC_CODE` VARCHAR(512) DEFAULT NULL,
  `MICR_CODE` VARCHAR(512) DEFAULT NULL,
  `ACCOUNT_NUMBER` VARCHAR(512) DEFAULT NULL,
  `ACCOUNT_TYPE` VARCHAR(512) DEFAULT NULL,
  `STATUS` VARCHAR(512) DEFAULT NULL,
  PRIMARY KEY (`USER_ADDITIONAL_BANKINFO_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8

/* Redemption Mgt table structure**/

CREATE TABLE `redemption_status_report_userdata` (
                `Redemption_Status_Report_Userdata_Id` INT(50) NOT NULL AUTO_INCREMENT,
	        `Amount` DECIMAL(20,5) DEFAULT '0.0000',
		`Amt` DECIMAL(20,5) DEFAULT '0.0000',
		`Beneficiary_Id` VARCHAR(126) DEFAULT NULL,
		`Branch_Code` VARCHAR(126) DEFAULT NULL,
		`Client_Code` VARCHAR(126) DEFAULT NULL,
		`Client_Name` VARCHAR(126) DEFAULT NULL,
		`DPC_Flag` VARCHAR(126) DEFAULT NULL,
		`DP_Trans` VARCHAR(126) DEFAULT NULL,
		`Folio_No` VARCHAR(126) DEFAULT NULL,
		`ISIN` VARCHAR(126) DEFAULT NULL,
		`Member_Code` VARCHAR(126) DEFAULT NULL,
		`Nav` VARCHAR(126) DEFAULT NULL,
		`Order_Date` VARCHAR(126) DEFAULT NULL,
		`Order_No` INT(50) DEFAULT NULL,
		`Order_Type` VARCHAR(126) DEFAULT NULL,
		`Qty` INT(50) DEFAULT NULL,
		`RTA_Scheme_Code` VARCHAR(126) DEFAULT NULL,
		`RTA_Trans_No` VARCHAR(126) DEFAULT NULL,
		`Remarks` VARCHAR(126) DEFAULT NULL,
		`Report_Date` VARCHAR(126) DEFAULT NULL,
		`STT` INT(50) DEFAULT NULL,
		`Scheme_Code` VARCHAR(126) DEFAULT NULL,
		`Sett_No` VARCHAR(126) DEFAULT NULL,
		`Sett_Type` VARCHAR(126) DEFAULT NULL,
		`Sub_Order_Type` VARCHAR(126) DEFAULT NULL,
		`Unit` VARCHAR(126) DEFAULT NULL,
		`User_Id` INT(50) DEFAULT NULL,
		`UNIT_BALANCE` DECIMAL(20,5) DEFAULT '0.0000',
		`RUPEE_BALANCE` DECIMAL(20,5) DEFAULT '0.0000',
		`REDUMPTION_DATE` VARCHAR(126) DEFAULT NULL,
		`REDUMPTION_AMOUNT` DECIMAL(20,5) DEFAULT '0.0000',
		`REDUMPTION_UNIT` DECIMAL(20,5) DEFAULT '0.0000',
		`STATUS` VARCHAR(126) DEFAULT NULL,
		  `FIELD1` VARCHAR(126) DEFAULT NULL,
		  `FIELD2` VARCHAR(126) DEFAULT NULL,
		  `FIELD3` VARCHAR(126) DEFAULT NULL,
		  `FIELD4` INT(126) DEFAULT NULL,
		  `FIELD5` DECIMAL(20,5) DEFAULT NULL,
	  PRIMARY KEY (`Redemption_Status_Report_Userdata_Id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;



CREATE TABLE `maintain_current_nav_current_value_for_orders` (
                `Maintain_Current_Nav_Current_Value_For_Orders_Id` INT(50) NOT NULL AUTO_INCREMENT,
                `Order_Id` INT(50) DEFAULT NULL,
	        `Current_Amount` DECIMAL(20,5) DEFAULT '0.0000',
		`Current_Nav` DECIMAL(20,5) DEFAULT '0.0000',
		`User_Id` INT(50) DEFAULT NULL,
		`Client_Code` VARCHAR(126) DEFAULT NULL,
		`STATUS` VARCHAR(126) DEFAULT NULL,
		  `FIELD1` VARCHAR(126) DEFAULT NULL,
		  `FIELD2` VARCHAR(126) DEFAULT NULL,
		  `FIELD3` DECIMAL(20,5) DEFAULT NULL,
		  `FIELD4` INT(126) DEFAULT NULL,
		  `FIELD5` DECIMAL(20,5) DEFAULT NULL,
	  PRIMARY KEY (`Maintain_Current_Nav_Current_Value_For_Orders_Id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

INSERT INTO `store_conf` (`STORE_CONF_ID`,`KEYWORD`,`KEYWORD_VALUE`) VALUES (34,'MANDATE_AUTHENTICATION_API_URL','http://bsestarmf.in/StarMFWebService/StarMFWebService.svc/EMandateAuthURL');

CREATE TABLE `user_enquiry` (
  `USER_ENQUIRY_ID` INT(50) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(512) DEFAULT NULL,
  `EMAIL` VARCHAR(512) DEFAULT NULL,
  `MOBILE` VARCHAR(512) DEFAULT NULL,
  `QUERY` VARCHAR(2500) DEFAULT NULL,
  `UPDATE_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`USER_ENQUIRY_ID`)
  ) ENGINE=INNODB DEFAULT CHARSET=utf8
  
INSERT INTO `store_conf` (`STORE_CONF_ID`,`KEYWORD`,`KEYWORD_VALUE`) VALUES (35,'REDEMPTION_STATUS_API_URL','http://bsestarmf.in/StarMFWebService/StarMFWebService.svc/RedemptionStatement');


/* ----- New Alter Command ---- */

CREATE TABLE `portfolio_category` (
  `PORTFOLIO_CATEGORY_ID` INT(50) NOT NULL AUTO_INCREMENT,
  `CATEGORY_NAME` VARCHAR(512) DEFAULT NULL,
  `UPDATE_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY (`PORTFOLIO_CATEGORY_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8


CREATE TABLE `portfolio` (
  `PORTFOLIO_ID` INT(50) NOT NULL AUTO_INCREMENT,
  `PORTFOLIO_CATEGORY_ID` INT(50) DEFAULT NULL,
  `SCHEME_CODE` VARCHAR(512) DEFAULT NULL,
  `SCHEME_NAME` VARCHAR(512) DEFAULT NULL,
  `STATUS`      VARCHAR(512) DEFAULT NULL,
  `UPDATE_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY (`PORTFOLIO_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8


/** -- New Alter Command -- **/

ALTER TABLE `go4wealthdb`.`portfolio_category` ADD COLUMN `CATEGORY_GROUP` VARCHAR(512) DEFAULT NULL;
ALTER TABLE `go4wealthdb`.`portfolio_category` ADD COLUMN `CATEGORY_RETURN` VARCHAR(512) DEFAULT NULL;
ALTER TABLE `go4wealthdb`.`portfolio_category` ADD COLUMN `CATEGORY_RISK` VARCHAR(512) DEFAULT NULL;
ALTER TABLE `go4wealthdb`.`portfolio_category` ADD COLUMN `CATEGORY_KEYWORD` VARCHAR(512) DEFAULT NULL;
ALTER TABLE `go4wealthdb`.`portfolio_category` ADD COLUMN `CATEGORY_CREATED_BY` VARCHAR(512) DEFAULT NULL;

ALTER TABLE scheme CHANGE FIELD1 Fund_Nature VARCHAR(512) NULL;

/**----New Alter Commands date-24-10-2018-----**/
ALTER TABLE `orders` ADD COLUMN `MODEL_PORTFOLIO_CATEGORY` VARCHAR(50) DEFAULT NULL;
ALTER TABLE `order_item` ADD COLUMN `MODEL_PORTFOLIO_CATEGORY` VARCHAR(50) DEFAULT NULL;

ALTER TABLE `orders` ADD COLUMN `ORDER_CATEGORY` VARCHAR(50) DEFAULT NULL;
ALTER TABLE `order_item` ADD COLUMN `ORDER_CATEGORY` VARCHAR(50) DEFAULT NULL;

ALTER TABLE `orders` ADD COLUMN `M_P_BUNDLE_ID` INT(50) DEFAULT NULL;
ALTER TABLE `order_item` ADD COLUMN `M_P_BUNDLE_ID` INT(50) DEFAULT NULL;

/******** New Alter Command On 01-11-2018*************/

ALTER TABLE scheme ADD COLUMN `Nav_Date` VARCHAR(50) NULL;
ALTER TABLE scheme ADD COLUMN `Current_Nav` VARCHAR(50) NULL;
UPDATE portfolio_category SET category_name = 'Tax Saver | ELSS' WHERE category_name = 'Tax Saver'
UPDATE portfolio_category SET category_name = 'Funds For Emergency' WHERE category_name = 'Funds For Immediate Requirement'

/************************* New Insert Command****************/

INSERT INTO `store_conf` (`STORE_CONF_ID`,`KEYWORD`,`KEYWORD_VALUE`) VALUES (36,'CHANGE_PASSWORD_VALUE_NOT','123456!');
INSERT INTO `store_conf` (`STORE_CONF_ID`,`KEYWORD`,`KEYWORD_VALUE`) VALUES (37,'CHANGE_PASSWORD_VALUE_AT','123456@');
INSERT INTO `store_conf` (`STORE_CONF_ID`,`KEYWORD`,`KEYWORD_VALUE`) VALUES (38,'NAV_DATA_SHEET_LOCATION','/navdata');

INSERT INTO `system_properties` (`PROPERTY_KEY`,`PROPERTY_VALUE`) VALUES ('NavUserId','goforwealth');
 INSERT INTO `system_properties` (`PROPERTY_KEY`,`PROPERTY_VALUE`) VALUES ('NavPassword','Icra@123');
 
 /******** New Alter Command On 23-11-2018*************/
ALTER TABLE `USER_ASSET_ITEMS` ADD COLUMN `GOALS_ORDER_ITEM_ID` INT(50) DEFAULT NULL;
 ALTER TABLE onboarding_status CHANGE FIELD4 BILLER_STATUS VARCHAR(512) NULL;
 UPDATE onboarding_status SET ISIP_MANDATE_STATUS = 0 WHERE ISIP_MANDATE_STATUS IS NULL;
 UPDATE onboarding_status SET biller_status = 'Pending' WHERE biller_status IS NULL;
 UPDATE onboarding_status SET enach_status = 'Pending' WHERE enach_status IS NULL;
 ALTER TABLE orders ADD COLUMN PAYMENT_OPTIONS VARCHAR(50) DEFAULT NULL;
 UPDATE orders SET payment_options = 'Pending' WHERE payment_options IS NULL;
 
/*** New Alter Command on 24-11-2018 ***/
UPDATE goals SET SHOW_TO_PROFILE_TYPE='5' WHERE GOAL_ID=1;
UPDATE goals SET SHOW_TO_PROFILE_TYPE='2' WHERE GOAL_ID=2;
UPDATE goals SET SHOW_TO_PROFILE_TYPE='3' WHERE GOAL_ID=3;
UPDATE goals SET SHOW_TO_PROFILE_TYPE='4' WHERE GOAL_ID=4;
UPDATE goals SET SHOW_TO_PROFILE_TYPE='17' WHERE GOAL_ID=5;
UPDATE goals SET SHOW_TO_PROFILE_TYPE='6' WHERE GOAL_ID=6;
UPDATE goals SET SHOW_TO_PROFILE_TYPE='7' WHERE GOAL_ID=7;
UPDATE goals SET SHOW_TO_PROFILE_TYPE='8' WHERE GOAL_ID=8;
UPDATE goals SET SHOW_TO_PROFILE_TYPE='9' WHERE GOAL_ID=9;
UPDATE goals SET SHOW_TO_PROFILE_TYPE='10' WHERE GOAL_ID=10;
UPDATE goals SET SHOW_TO_PROFILE_TYPE='11' WHERE GOAL_ID=11;
UPDATE goals SET SHOW_TO_PROFILE_TYPE='12' WHERE GOAL_ID=12;
UPDATE goals SET SHOW_TO_PROFILE_TYPE='13' WHERE GOAL_ID=13;
UPDATE goals SET SHOW_TO_PROFILE_TYPE='14' WHERE GOAL_ID=14;
UPDATE goals SET SHOW_TO_PROFILE_TYPE='15' WHERE GOAL_ID=15;
UPDATE goals SET SHOW_TO_PROFILE_TYPE='16' WHERE GOAL_ID=16;
UPDATE goals SET SHOW_TO_PROFILE_TYPE='1' WHERE GOAL_ID=17;


/*** New Alter Command on 26-11-2018 ***/
UPDATE age_slabs SET AGE_FROM='55' WHERE AGE_SLAB_ID=8;
UPDATE age_slabs SET AGE_TO='100' WHERE AGE_SLAB_ID=8;

/*** New Alter Command on 28-11-2018 ***/
ALTER TABLE address_proof ADD COLUMN ADDRESS_TYPE VARCHAR(50) DEFAULT NULL;
ALTER TABLE address_proof ADD COLUMN INCOME_SLAB VARCHAR(50) DEFAULT NULL;
ALTER TABLE address_proof ADD COLUMN PEP VARCHAR(50) DEFAULT NULL;

/*** New Alter Command on 30-11-2018 ***/
ALTER TABLE address_proof MODIFY COLUMN `ADDRESS` VARCHAR(512);
ALTER TABLE orders ADD COLUMN MANDATE_ID VARCHAR(50) DEFAULT NULL;

CREATE TABLE `user_mandate_history` (
  `USER_MANDATE_HISTORY_ID` INT(50) NOT NULL AUTO_INCREMENT,
  `USER_ID` INT(50) DEFAULT NULL,
  `USER_BANK_ACCOUNT` VARCHAR(512) DEFAULT NULL,
  `BANK_IFSC` VARCHAR(512) DEFAULT NULL,
  `MANDATE_TYPE` VARCHAR(512) DEFAULT NULL,
  `STATUS` VARCHAR(512) DEFAULT NULL,
  `MANDATE_ID` VARCHAR(512) DEFAULT NULL,
  `ORDER_PLACE_FLAG` VARCHAR(512) DEFAULT NULL,
  `CREATED_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `MANDATE_CREATED_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `FIELD1` VARCHAR(512) DEFAULT NULL,
  `FIELD2` VARCHAR(512) DEFAULT NULL,
  `FIELD3` VARCHAR(512) DEFAULT NULL,
  `FIELD4` INT(50) DEFAULT NULL,
  `FIELD5` INT(50) DEFAULT NULL,
  PRIMARY KEY (`USER_MANDATE_HISTORY_ID`)
  ) ENGINE=INNODB DEFAULT CHARSET=utf8
  
/** New Queries For 03-12-2018 **/
INSERT INTO isip_allowed_bank_list VALUES(1,'IDSB','IndusInd Bank','Netbanking & Mobile banking Register and Pay','Both',NULL,NULL,NULL,NULL,NULL);
INSERT INTO isip_allowed_bank_list VALUES(2,'AXIS','Axis Bank','Netbanking & Mobile banking Register and Pay','Both',NULL,NULL,NULL,NULL,NULL);
INSERT INTO isip_allowed_bank_list VALUES(3,'BOB','Bank of Baroda','Netbanking Register and Pay','Both',NULL,NULL,NULL,NULL,NULL);	
INSERT INTO isip_allowed_bank_list VALUES(4,'BOM','Bank of Maharashtra','Netbanking & Mobile banking Register and Pay','View and Pay only',NULL,NULL,NULL,NULL,NULL);	
INSERT INTO isip_allowed_bank_list VALUES(5,'CBI','Central Bank of India','Only MPAY Register and Pay','Both',NULL,NULL,NULL,NULL,NULL);	
INSERT INTO isip_allowed_bank_list VALUES(6,'CNB','Canara Bank','Only Mobile banking Register and Pay','Both',NULL,NULL,NULL,NULL,NULL);
INSERT INTO isip_allowed_bank_list VALUES(7,'CORPB','Corporation Bank','Netbanking Register and Pay','View and Pay only',NULL,NULL,NULL,NULL,NULL);	
INSERT INTO isip_allowed_bank_list VALUES(8,'COSMOS','COSMOS Bank','Netbanking Register and Pay','Both',NULL,NULL,NULL,NULL,NULL);	
INSERT INTO isip_allowed_bank_list VALUES(9,'CSB','Catholic Syrian Bank','Netbanking Register and Pay','View and Pay only',NULL,NULL,NULL,NULL,NULL);	
INSERT INTO isip_allowed_bank_list VALUES(10,'CUB','City Union Bank','Netbanking & Mobile banking Register and Pay','View and Pay only',NULL,NULL,NULL,NULL,NULL);	
INSERT INTO isip_allowed_bank_list VALUES(11,'DBS','Development Bank of Singapore','Only Mobile banking Register and Pay','View and Pay only',NULL,NULL,NULL,NULL,NULL);	
INSERT INTO isip_allowed_bank_list VALUES(12,'DLB','The Dhanalakshmi Bank','Netbanking & Mobile banking Register and Pay','View and Pay only',NULL,NULL,NULL,NULL,NULL);	
INSERT INTO isip_allowed_bank_list VALUES(13,'FED','Federal Bank','Only Mobile banking Register and Pay','View and Pay only',NULL,NULL,NULL,NULL,NULL);	
INSERT INTO isip_allowed_bank_list VALUES(14,'FRB','FIRSTRAND BANK','Netbanking Register and Pay','View and Pay only',NULL,NULL,NULL,NULL,NULL);
INSERT INTO isip_allowed_bank_list VALUES(15,'IDFC','IDFC Bank','Only Mobile banking Register and Pay','View and Pay only',NULL,NULL,NULL,NULL,NULL);	
INSERT INTO isip_allowed_bank_list VALUES(16,'INDB','Indian bank','Netbanking & Mobile banking Register and Pay','View and Pay only',NULL,NULL,NULL,NULL,NULL);	
INSERT INTO isip_allowed_bank_list VALUES(17,'IOB','INDIAN OVERSEAS BANK','Only Mobile banking Register and Pay','View and Pay only',NULL,NULL,NULL,NULL,NULL);	
INSERT INTO isip_allowed_bank_list VALUES(18,'KBL','Karnataka Bank','Only Mobile banking Register and Pay','View and Pay',NULL,NULL,NULL,NULL,NULL); 
INSERT INTO isip_allowed_bank_list VALUES(19,'LVB','Lakshmi Vilas Bank','Only Mobile banking Register and Pay','View and Pay only',NULL,NULL,NULL,NULL,NULL);	
INSERT INTO isip_allowed_bank_list VALUES(20,'NKGSB','NKGSB bank','Netbanking & Mobile banking Register and Pay','both',NULL,NULL,NULL,NULL,NULL);	
INSERT INTO isip_allowed_bank_list VALUES(21,'PNB','Punjab National Bank','Only Mobile banking Register and Pay','Both',NULL,NULL,NULL,NULL,NULL);	
INSERT INTO isip_allowed_bank_list VALUES(22,'RATNAB','Ratnakar Bank','Netbanking Register and Pay','View and Pay only',NULL,NULL,NULL,NULL,NULL);	
INSERT INTO isip_allowed_bank_list VALUES(23,'SIB','South Indian bank','Only Mobile banking Register and Pay','View and Pay only',NULL,NULL,NULL,NULL,NULL);	
INSERT INTO isip_allowed_bank_list VALUES(24,'SRSB','Saraswat Bank','Netbanking Register and Pay','View and Pay only',NULL,NULL,NULL,NULL,NULL);	
INSERT INTO isip_allowed_bank_list VALUES(25,'UBIB','Union Bank of India','Netbanking Register and Pay','Both',NULL,NULL,NULL,NULL,NULL);	
INSERT INTO isip_allowed_bank_list VALUES(26,'UCOB','UCO Bank','Netbanking & Mobile banking Register and Pay','Both',NULL,NULL,NULL,NULL,NULL);	
INSERT INTO isip_allowed_bank_list VALUES(27,'UNI','United Bank of India','Only MPAY Register and Pay','Both',NULL,NULL,NULL,NULL,NULL);	
INSERT INTO isip_allowed_bank_list VALUES(28,'YESB','Yes Bank','Netbanking & Mobile banking Register and Pay','Both',NULL,NULL,NULL,NULL,NULL);	
INSERT INTO isip_allowed_bank_list VALUES(29,'YESBCRP','YES CORPORATE BANK Ltd','Netbanking & Mobile banking Register and Pay','Both',NULL,NULL,NULL,NULL,NULL);	
INSERT INTO isip_allowed_bank_list VALUES(30,'HDFCB','HDFC Bank','Netbanking & Mobile banking Register and Pay','Both',NULL,NULL,NULL,NULL,NULL);	
INSERT INTO isip_allowed_bank_list VALUES(31,'KTK','Kotak Mahindra Bank','Netbanking & Mobile banking Register and Pay','Both',NULL,NULL,NULL,NULL,NULL);	
INSERT INTO isip_allowed_bank_list VALUES(32,'SVC','Shamrao Vithal Co-operative Bank','Only Netbanking','View and Pay only',NULL,NULL,NULL,NULL,NULL);	
INSERT INTO isip_allowed_bank_list VALUES(33,'TNSC','Tamil Nadu State Apex Co-operative bank','Only Netbanking','View and Pay only',NULL,NULL,NULL,NULL,NULL);	
INSERT INTO isip_allowed_bank_list VALUES(34,'ANDH','Andhra Bank',' Only Mobile banking Register and Pay','Both',NULL,NULL,NULL,NULL,NULL);	
INSERT INTO isip_allowed_bank_list VALUES(35,'idbi','IDBI Bank','Netbanking Register and Pay','Both',NULL,NULL,NULL,NULL,NULL);	
INSERT INTO isip_allowed_bank_list VALUES(36,'icici','ICICI Bank','Netbanking Register and Pay','Both',NULL,NULL,NULL,NULL,NULL);	
INSERT INTO isip_allowed_bank_list VALUES(37,'ybank','State Bank of India','Netbanking & Mobile banking Register and Pay','Both',NULL,NULL,NULL,NULL,NULL);	

CREATE TABLE `isip_allowed_bank_list` (
  `ISIP_ALLOWED_BANK_LIST_ID` INT(50) NOT NULL AUTO_INCREMENT,
  `BANK_ID` VARCHAR(512) DEFAULT NULL,
  `BANK_NAME` VARCHAR(512) DEFAULT NULL,
  `REMARKS` VARCHAR(512) DEFAULT NULL,
  `PAYMENT_MODE` VARCHAR(512) DEFAULT NULL,
  `FIELD1` VARCHAR(512) DEFAULT NULL,
  `FIELD2` VARCHAR(512) DEFAULT NULL,
  `FIELD3` VARCHAR(512) DEFAULT NULL,
  `FIELD4` INT(50) DEFAULT NULL,
  `FIELD5` INT(50) DEFAULT NULL,
  PRIMARY KEY (`ISIP_ALLOWED_BANK_LIST_ID`)
  ) ENGINE=INNODB DEFAULT CHARSET=utf8


ALTER TABLE address_proof MODIFY COLUMN `FIELD2` VARCHAR(512);
ALTER TABLE address_proof MODIFY COLUMN `FIELD3` VARCHAR(512);
INSERT INTO `store_conf` (`STORE_CONF_ID`,`KEYWORD`,`KEYWORD_VALUE`) VALUES (39,'MANDATE_PDF_LOCATION','/mandate-pdf');
INSERT INTO `store_conf` (`STORE_CONF_ID`,`KEYWORD`,`KEYWORD_VALUE`) VALUES (40,'MANDATE_TIFF_LOCATION','/mandate-tiff');
 
ALTER TABLE scheme add column SCHEME_CATEGORY VARCHAR(512) DEFAULT NULL;
ALTER TABLE scheme add column SCHEME_SUB_CATEGORY VARCHAR(512) DEFAULT NULL;
ALTER TABLE scheme add column SCHEME_OPTIONS VARCHAR(512) DEFAULT NULL;
ALTER TABLE scheme add column FUND_MANAGER VARCHAR(512) DEFAULT NULL;
ALTER TABLE scheme add column INVESTMENT_OBJECTIVE VARCHAR(1000) DEFAULT NULL;
ALTER TABLE scheme add column CLASSIFICATION VARCHAR(512) DEFAULT NULL;

/* New Commanda for date 05-12-2018*/
INSERT INTO `store_conf` (`STORE_CONF_ID`,`KEYWORD`,`KEYWORD_VALUE`) VALUES (41,'AMOUNT_LIMIT_WITHDRAWAL_FROM_BANK_IN_WORLD','One Lac Only');
 
/***  New Commands For Date 06-12-2018**/
INSERT INTO `store_conf` (`STORE_CONF_ID`,`KEYWORD`,`KEYWORD_VALUE`) VALUES (42,'MANDATE_UPLOAD_URL','http://bsestarmf.in/StarMFFileUploadService/StarMFFileUploadService.svc/UploadMandateScanFile');
ALTER TABLE onboarding_status CHANGE FIELD3 UPLOAD_MANDATE_STATUS VARCHAR(512) NULL;


/*** New Query Date 14-12-2018 ***/
ALTER TABLE income_slabs ADD COLUMN INCOME_PERCENTAGE VARCHAR(512) DEFAULT '40';

/*** New Query Date 14-01-2019 ***/
ALTER TABLE `go4wealthdb`.`top_schemes` ADD COLUMN `SEQUENCE` INT(10) DEFAULT NULL;

/** New Query For 15-01-2019***/
ALTER TABLE redumption_management CHANGE FIELD1 SIP_Regn_No BIGINT(50) NULL;
ALTER TABLE redumption_management MODIFY COLUMN FOLIO_NUMBER varchar(126);
ALTER TABLE maintain_current_nav_current_value_for_orders CHANGE FIELD2 FOLIO_NO varchar(126) NULL;
ALTER TABLE maintain_current_nav_current_value_for_orders CHANGE FIELD3 SIP_Regn_No bigint(50) NULL;
ALTER TABLE maintain_current_nav_current_value_for_orders CHANGE FIELD4 INVESTED_AMOUNT decimal(20,3) DEFAULT NULL;
ALTER TABLE maintain_current_nav_current_value_for_orders CHANGE FIELD5 CURRENT_UNIT decimal(20,3) DEFAULT NULL;
ALTER TABLE redumption_management CHANGE FIELD4 USER_ID INT(50) DEFAULT NULL;
ALTER TABLE maintain_current_nav_current_value_for_orders CHANGE Last_Updated_date Last_Nav_Updated_date varchar(126) DEFAULT NULL;
ALTER TABLE maintain_current_nav_current_value_for_orders ADD COLUMN `Last_Redumption_Updated_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE maintain_current_nav_current_value_for_orders CHANGE Current_Nav Scheme_Code varchar(126) DEFAULT NULL;
ALTER TABLE redumption_management CHANGE FIELD2 Scheme_Name varchar(126) DEFAULT NULL;

/*Nedd To Execute below Query before deploying to production*/
/** New Query For 21-01-2019***/

ALTER TABLE allotment_status_report_userdata CHANGE FIELD3 STATUS VARCHAR(50) NULL;
ALTER TABLE allotment_status_report_userdata CHANGE FIELD4 Allot_Mail_Status INT(10) NULL;

ALTER TABLE order_status_report_userdata CHANGE FIELD3 STATUS VARCHAR(50) NULL;
ALTER TABLE order_status_report_userdata CHANGE FIELD4 Allot_Mail_Status INT(10) NULL;

UPDATE allotment_status_report_userdata SET sip_regn_no =3353211 WHERE order_no =44991297;
UPDATE allotment_status_report_userdata SET sip_regn_no =3353635 WHERE order_no =44996358; 
UPDATE allotment_status_report_userdata SET sip_regn_no =3832700 WHERE order_no =52089864;
UPDATE allotment_status_report_userdata SET sip_regn_no =3841698 WHERE order_no =52141533;
UPDATE allotment_status_report_userdata SET sip_regn_no =3841684 WHERE order_no =52141512; 
UPDATE allotment_status_report_userdata SET sip_regn_no =3911400 WHERE order_no =53011352; 
UPDATE allotment_status_report_userdata SET sip_regn_no =3924285 WHERE order_no =53212308;
UPDATE allotment_status_report_userdata SET sip_regn_no =3924130 WHERE order_no =53210513; 
UPDATE allotment_status_report_userdata SET sip_regn_no =3973224 WHERE order_no =53601666; 
UPDATE allotment_status_report_userdata SET sip_regn_no =4015372 WHERE order_no =54703717; 
UPDATE allotment_status_report_userdata SET sip_regn_no =4017955 WHERE order_no =54744916; 
UPDATE allotment_status_report_userdata SET sip_regn_no =4027932 WHERE order_no =54809072; 
UPDATE allotment_status_report_userdata SET sip_regn_no =3973248 WHERE order_no =53601710; 
UPDATE allotment_status_report_userdata SET sip_regn_no =4096427 WHERE order_no =55898762; 
UPDATE allotment_status_report_userdata SET sip_regn_no =4096420 WHERE order_no =55898736; 
UPDATE allotment_status_report_userdata SET sip_regn_no =4096034 WHERE order_no =55898588;
UPDATE allotment_status_report_userdata SET sip_regn_no =4112448 WHERE order_no =55992694; 
UPDATE allotment_status_report_userdata SET sip_regn_no =4109506 WHERE order_no =55988510; 
UPDATE allotment_status_report_userdata SET sip_regn_no =4125426 WHERE order_no =56348934; 
UPDATE allotment_status_report_userdata SET sip_regn_no =4158349 WHERE order_no =56829141; 
UPDATE allotment_status_report_userdata SET sip_regn_no =4096942 WHERE order_no =55899239; 
UPDATE allotment_status_report_userdata SET sip_regn_no =4096929 WHERE order_no =55899231; 
UPDATE allotment_status_report_userdata SET sip_regn_no =4189002 WHERE order_no =57018655; 
UPDATE allotment_status_report_userdata SET sip_regn_no =4184643 WHERE order_no =57013572; 
UPDATE allotment_status_report_userdata SET sip_regn_no =4183050 WHERE order_no =57011455;

UPDATE allotment_status_report_userdata SET sip_regn_no =0 WHERE sip_regn_date='';

UPDATE allotment_status_report_userdata SET STATUS ='AD' WHERE STATUS IS NULL;
UPDATE allotment_status_report_userdata SET allot_mail_status =1 WHERE allot_mail_status IS NULL;

UPDATE order_status_report_userdata SET STATUS ='AD' WHERE STATUS IS NULL;
UPDATE order_status_report_userdata SET allot_mail_status =1 WHERE allot_mail_status IS NULL;
INSERT INTO `store_conf` (`STORE_CONF_ID`,`KEYWORD`,`KEYWORD_VALUE`) VALUES (43,'ALLOTEMENT_TIME','12');
INSERT INTO `store_conf` (`STORE_CONF_ID`,`KEYWORD`,`KEYWORD_VALUE`) VALUES (44,'NODE_API_FOR_MAIL_REPORT','https://go4wealth.com/generateStatement/consolidatedStatement');
UPDATE order_status_report_userdata SET STATUS ='AP' WHERE order_number =58590115;

UPDATE allotment_status_report_userdata SET STATUS ='AP' WHERE order_no =58590115;
UPDATE orders SET STATUS ='AP' WHERE bse_order_id = 58590115;
UPDATE order_item SET STATUS ='AP' WHERE orders_id = 758;
UPDATE ppcpayinst SET state ='AP' WHERE TRANSACTION_ID = 519;



/*** New Query Date 18-01-2019 by Gaurav***/
DELETE FROM goals WHERE GOAL_ID=18;
DELETE FROM goals WHERE GOAL_ID=19;
DELETE FROM goals WHERE GOAL_ID=20;
DELETE FROM goals WHERE GOAL_ID=98;
DELETE FROM goals WHERE GOAL_ID=97;
DELETE FROM goals WHERE GOAL_ID=96;
DELETE FROM goals WHERE GOAL_ID=95;
DELETE FROM goals WHERE GOAL_ID=94;
DELETE FROM goals WHERE GOAL_ID=93;
DELETE FROM goals WHERE GOAL_ID=90;
DELETE FROM goals WHERE GOAL_ID=89;
DELETE FROM goals WHERE GOAL_ID=88;
DELETE FROM goals WHERE GOAL_ID=85;
DELETE FROM goals WHERE GOAL_ID=83;
DELETE FROM goals WHERE GOAL_ID=82;
DELETE FROM goals WHERE GOAL_ID=81;
DELETE FROM goals WHERE GOAL_ID=80;
DELETE FROM goals WHERE GOAL_ID=78;
DELETE FROM goals WHERE GOAL_ID=77;
DELETE FROM goals WHERE GOAL_ID=75;
DELETE FROM goals WHERE GOAL_ID=74;
DELETE FROM goals WHERE GOAL_ID=72;
DELETE FROM goals WHERE GOAL_ID=71;
DELETE FROM goals WHERE GOAL_ID=70;
DELETE FROM goals WHERE GOAL_ID=69;
DELETE FROM goals WHERE GOAL_ID=68;
DELETE FROM goals WHERE GOAL_ID=67;
DELETE FROM goals WHERE GOAL_ID=66;
DELETE FROM goals WHERE GOAL_ID=65;
DELETE FROM goals WHERE GOAL_ID=64;
DELETE FROM goals WHERE GOAL_ID=63;
DELETE FROM goals WHERE GOAL_ID=62;
DELETE FROM goals WHERE GOAL_ID=61;
DELETE FROM goals WHERE GOAL_ID=60;
DELETE FROM goals WHERE GOAL_ID=59;
DELETE FROM goals WHERE GOAL_ID=58;
DELETE FROM goals WHERE GOAL_ID=57;
DELETE FROM goals WHERE GOAL_ID=56;
DELETE FROM goals WHERE GOAL_ID=55;
DELETE FROM goals WHERE GOAL_ID=54;
DELETE FROM goals WHERE GOAL_ID=53;
DELETE FROM goals WHERE GOAL_ID=52;
DELETE FROM goals WHERE GOAL_ID=51;
DELETE FROM goals WHERE GOAL_ID=50;
DELETE FROM goals WHERE GOAL_ID=47;
DELETE FROM goals WHERE GOAL_ID=44;
DELETE FROM goals WHERE GOAL_ID=43;
DELETE FROM goals WHERE GOAL_ID=40;
DELETE FROM goals WHERE GOAL_ID=39;
DELETE FROM goals WHERE GOAL_ID=38;
DELETE FROM goals WHERE GOAL_ID=34;
DELETE FROM goals WHERE GOAL_ID=33;
DELETE FROM goals WHERE GOAL_ID=32;
DELETE FROM goals WHERE GOAL_ID=31;
DELETE FROM goals WHERE GOAL_ID=30;
DELETE FROM goals WHERE GOAL_ID=29;
DELETE FROM goals WHERE GOAL_ID=28;
DELETE FROM goals WHERE GOAL_ID=27;
DELETE FROM goals WHERE GOAL_ID=26;
DELETE FROM goals WHERE GOAL_ID=25;
DELETE FROM goals WHERE GOAL_ID=24;
DELETE FROM goals WHERE GOAL_ID=23;
DELETE FROM goals WHERE GOAL_ID=22;
DELETE FROM goals WHERE GOAL_ID=21;
DELETE FROM goals WHERE GOAL_ID=132;
DELETE FROM goals WHERE GOAL_ID=131;
DELETE FROM goals WHERE GOAL_ID=130;
DELETE FROM goals WHERE GOAL_ID=129;
DELETE FROM goals WHERE GOAL_ID=128;
DELETE FROM goals WHERE GOAL_ID=127;
DELETE FROM goals WHERE GOAL_ID=125;
DELETE FROM goals WHERE GOAL_ID=124;
DELETE FROM goals WHERE GOAL_ID=123;
DELETE FROM goals WHERE GOAL_ID=122;
DELETE FROM goals WHERE GOAL_ID=121;
DELETE FROM goals WHERE GOAL_ID=120;
DELETE FROM goals WHERE GOAL_ID=119;
DELETE FROM goals WHERE GOAL_ID=118;
DELETE FROM goals WHERE GOAL_ID=117;
DELETE FROM goals WHERE GOAL_ID=116;
DELETE FROM goals WHERE GOAL_ID=115;
DELETE FROM goals WHERE GOAL_ID=101;
DELETE FROM goals WHERE GOAL_ID=102;
DELETE FROM goals WHERE GOAL_ID=103;
DELETE FROM goals WHERE GOAL_ID=104;
DELETE FROM goals WHERE GOAL_ID=105;
DELETE FROM goals WHERE GOAL_ID=106;
DELETE FROM goals WHERE GOAL_ID=107;
DELETE FROM goals WHERE GOAL_ID=108;
DELETE FROM goals WHERE GOAL_ID=109;
DELETE FROM goals WHERE GOAL_ID=110;
DELETE FROM goals WHERE GOAL_ID=111;
DELETE FROM goals WHERE GOAL_ID=112;
DELETE FROM goals WHERE GOAL_ID=113;
DELETE FROM goals WHERE GOAL_ID=114;

UPDATE orders SET GOAL_NAME='(NULL)' , GOAL_ID=(NULL) WHERE ORDERS_ID=99;
UPDATE orders SET GOAL_NAME='(NULL)' , GOAL_ID=(NULL) WHERE ORDERS_ID=102;
UPDATE orders SET GOAL_NAME='(NULL)' , GOAL_ID=(NULL) WHERE ORDERS_ID=104;
UPDATE orders SET GOAL_NAME='(NULL)' , GOAL_ID=(NULL) WHERE ORDERS_ID=120;
UPDATE orders SET GOAL_NAME='Retirement Planning' , GOAL_ID=9776 WHERE ORDERS_ID=121;
UPDATE goal_order_items SET FIELD1=1 WHERE GOAL_ORDER_ITEM_ID=9776;
UPDATE orders SET GOAL_NAME='(NULL)' , GOAL_ID=(NULL) WHERE ORDERS_ID=122;
UPDATE orders SET GOAL_NAME='Car Purchase' , GOAL_ID=9778 WHERE ORDERS_ID=123;
UPDATE goal_order_items SET FIELD1=1 WHERE GOAL_ORDER_ITEM_ID=9778;
UPDATE orders SET GOAL_NAME='(NULL)' , GOAL_ID=(NULL) WHERE ORDERS_ID=124;
UPDATE orders SET GOAL_NAME='(NULL)' , GOAL_ID=(NULL) WHERE ORDERS_ID=125;
UPDATE orders SET GOAL_NAME='(NULL)' , GOAL_ID=(NULL) WHERE ORDERS_ID=127;


UPDATE orders SET GOAL_NAME='(NULL)' , GOAL_ID=(NULL) WHERE ORDERS_ID=255;
UPDATE orders SET GOAL_NAME='(NULL)' , GOAL_ID=(NULL) WHERE ORDERS_ID=405;
UPDATE orders SET GOAL_NAME='(NULL)' , GOAL_ID=(NULL) WHERE ORDERS_ID=588;
UPDATE orders SET GOAL_NAME='(NULL)' , GOAL_ID=(NULL) WHERE ORDERS_ID=680;
UPDATE orders SET GOAL_NAME='(NULL)' , GOAL_ID=(NULL) WHERE ORDERS_ID=766;

UPDATE orders SET GOAL_NAME='(NULL)' , GOAL_ID=(NULL) WHERE ORDERS_ID=329;
UPDATE orders SET GOAL_NAME='Retirement Planning' , GOAL_ID=5286 WHERE ORDERS_ID=383;
UPDATE orders SET GOAL_NAME='Retirement Planning' , GOAL_ID=5286 WHERE ORDERS_ID=741;
UPDATE goal_order_items SET FIELD1=1 WHERE GOAL_ORDER_ITEM_ID=5286;

UPDATE orders SET GOAL_NAME='(NULL)' , GOAL_ID=(NULL) WHERE ORDERS_ID=357;

UPDATE orders SET GOAL_NAME='(NULL)' , GOAL_ID=(NULL) WHERE ORDERS_ID=419;
UPDATE orders SET GOAL_NAME='Dream Home Down Payment' , GOAL_ID=9843 WHERE ORDERS_ID=420;
UPDATE goal_order_items SET FIELD1=1 WHERE GOAL_ORDER_ITEM_ID=9843;
UPDATE orders SET GOAL_NAME='(NULL)' , GOAL_ID=(NULL) WHERE ORDERS_ID=429;
UPDATE orders SET GOAL_NAME='(NULL)' , GOAL_ID=(NULL) WHERE ORDERS_ID=430;
UPDATE orders SET GOAL_NAME='Self Marriage' , GOAL_ID=9842 WHERE ORDERS_ID=728;
UPDATE orders SET GOAL_NAME='(NULL)' , GOAL_ID=(NULL) WHERE ORDERS_ID=758;

UPDATE orders SET GOAL_NAME='(NULL)' , GOAL_ID=(NULL) WHERE ORDERS_ID=427;

UPDATE orders SET GOAL_NAME='Fund in Need (Emergency Fund)' , GOAL_ID=9320 WHERE ORDERS_ID=604;
UPDATE goal_order_items SET FIELD1=1 WHERE GOAL_ORDER_ITEM_ID=9320;

UPDATE orders SET GOAL_NAME='(NULL)' , GOAL_ID=(NULL) WHERE ORDERS_ID=626;
UPDATE orders SET GOAL_NAME='(NULL)' , GOAL_ID=(NULL) WHERE ORDERS_ID=786;

UPDATE orders SET GOAL_NAME='(NULL)' , GOAL_ID=(NULL) WHERE ORDERS_ID=740;

UPDATE orders SET GOAL_NAME='(NULL)' , GOAL_ID=(NULL) WHERE ORDERS_ID=742;
UPDATE orders SET GOAL_NAME='(NULL)' , GOAL_ID=(NULL) WHERE ORDERS_ID=743;

UPDATE orders SET GOAL_NAME='My 1st Cr' , GOAL_ID=9798 WHERE ORDERS_ID=788;
UPDATE orders SET GOAL_NAME='Retirement Planning' , GOAL_ID=9799 WHERE ORDERS_ID=789;
UPDATE orders SET GOAL_NAME='My 1st Cr' , GOAL_ID=9798 WHERE ORDERS_ID=790;
UPDATE goal_order_items SET FIELD1=1 WHERE GOAL_ORDER_ITEM_ID=9798;
UPDATE goal_order_items SET FIELD1=1 WHERE GOAL_ORDER_ITEM_ID=9799;

UPDATE orders SET GOAL_NAME='(NULL)' , GOAL_ID=(NULL) WHERE ORDERS_ID=420;
UPDATE orders SET GOAL_NAME='(NULL)' , GOAL_ID=(NULL) WHERE ORDERS_ID=728;


DELETE FROM user_asset_items WHERE GOALS_ORDER_ID=58;
DELETE FROM goals_order WHERE GOALS_ORDER_ID=58;

DELETE FROM user_asset_items WHERE GOALS_ORDER_ID=59;
DELETE FROM goals_order WHERE GOALS_ORDER_ID=59;


DELETE FROM user_asset_items WHERE GOALS_ORDER_ID=66;
DELETE FROM goals_order WHERE GOALS_ORDER_ID=66;

UPDATE user_asset_items SET GOALS_ORDER_ITEM_ID=1000 WHERE GOALS_ORDER_ID=106;

UPDATE user_asset_items SET GOALS_ORDER_ITEM_ID=1834 WHERE GOALS_ORDER_ID=74 AND user_asset_item_id=12;
UPDATE user_asset_items SET GOALS_ORDER_ITEM_ID=1831 WHERE GOALS_ORDER_ID=74 AND user_asset_item_id=13;

UPDATE user_asset_items SET GOALS_ORDER_ITEM_ID=3650 WHERE GOALS_ORDER_ID=377;

UPDATE user_asset_items SET GOALS_ORDER_ITEM_ID=3578 WHERE GOALS_ORDER_ID=378;

UPDATE user_asset_items SET GOALS_ORDER_ITEM_ID=3844 WHERE GOALS_ORDER_ID=403;

UPDATE user_asset_items SET GOALS_ORDER_ITEM_ID=4041 WHERE GOALS_ORDER_ID=411;

DELETE FROM user_asset_items WHERE GOALS_ORDER_ID=426 AND ASSET_CLASS_ID=4;
DELETE FROM user_asset_items WHERE GOALS_ORDER_ID=426 AND ASSET_CLASS_ID=5;
DELETE FROM user_asset_items WHERE GOALS_ORDER_ID=426 AND ASSET_CLASS_ID=6;
UPDATE user_asset_items SET GOALS_ORDER_ITEM_ID=4835 WHERE GOALS_ORDER_ID=426 AND user_asset_item_id=30;
UPDATE user_asset_items SET GOALS_ORDER_ITEM_ID=4836 WHERE GOALS_ORDER_ID=426 AND user_asset_item_id=31;
UPDATE user_asset_items SET GOALS_ORDER_ITEM_ID=4837 WHERE GOALS_ORDER_ID=426 AND user_asset_item_id=32;

UPDATE user_asset_items SET GOALS_ORDER_ITEM_ID=4803 WHERE GOALS_ORDER_ID=422 AND user_asset_item_id=44;
UPDATE user_asset_items SET GOALS_ORDER_ITEM_ID=4804 WHERE GOALS_ORDER_ID=422 AND user_asset_item_id=45;

UPDATE user_asset_items SET GOALS_ORDER_ITEM_ID=4851 WHERE GOALS_ORDER_ID=410;

UPDATE user_asset_items SET GOALS_ORDER_ITEM_ID=5043 WHERE GOALS_ORDER_ID=436;


DELETE FROM user_asset_items WHERE GOALS_ORDER_ID=435 AND ASSET_CLASS_ID=6;
UPDATE user_asset_items SET GOALS_ORDER_ITEM_ID=4949 WHERE GOALS_ORDER_ID=435 AND user_asset_item_id=51;
UPDATE user_asset_items SET GOALS_ORDER_ITEM_ID=4952 WHERE GOALS_ORDER_ID=435 AND user_asset_item_id=54;

UPDATE user_asset_items SET GOALS_ORDER_ITEM_ID=5039 WHERE GOALS_ORDER_ID=441;


ALTER TABLE goals ADD COLUMN STATUS VARCHAR(512) DEFAULT NULL;

UPDATE goals SET STATUS='Active' WHERE GOAL_TYPE='PD';

UPDATE goals SET STATUS='Deactive' WHERE GOAL_ID=2;
UPDATE goals SET STATUS='Deactive' WHERE GOAL_ID=3;
UPDATE goals SET STATUS='Deactive' WHERE GOAL_ID=8;
UPDATE goals SET STATUS='Deactive' WHERE GOAL_ID=5;
UPDATE goals SET STATUS='Deactive' WHERE GOAL_ID=14;


UPDATE goals SET SHOW_TO_PROFILE_TYPE=6, GOAL_NAME='Car Purchase', COST_OF_GOAL=800000, DURATION=5, GOAL_BUCKET_ID=2 WHERE GOAL_ID=1;
UPDATE goals SET SHOW_TO_PROFILE_TYPE=13,DURATION=0, GOAL_BUCKET_ID=1 WHERE GOAL_ID=2;
UPDATE goals SET SHOW_TO_PROFILE_TYPE=14,DURATION=0, GOAL_BUCKET_ID=1 WHERE GOAL_ID=3;
UPDATE goals SET SHOW_TO_PROFILE_TYPE=2, GOAL_NAME='Self Marriage' ,COST_OF_GOAL=1000000 , DURATION=7, GOAL_BUCKET_ID=2 WHERE GOAL_ID=4;
UPDATE goals SET SHOW_TO_PROFILE_TYPE=15, DURATION=0, GOAL_BUCKET_ID=1 WHERE GOAL_ID=5;
UPDATE goals SET SHOW_TO_PROFILE_TYPE=3 , GOAL_NAME='Vacation Planning' ,COST_OF_GOAL=200000, DURATION=3, GOAL_BUCKET_ID=1 WHERE GOAL_ID=6;
UPDATE goals SET SHOW_TO_PROFILE_TYPE=10, GOAL_NAME='Lifestyle Needs - Gadgets,etc' ,COST_OF_GOAL=200000, DURATION=3, GOAL_BUCKET_ID=1 WHERE GOAL_ID=7;
UPDATE goals SET SHOW_TO_PROFILE_TYPE=16, DURATION=0, GOAL_BUCKET_ID=1 WHERE GOAL_ID=8;
UPDATE goals SET SHOW_TO_PROFILE_TYPE=7, GOAL_NAME='Dream Home' ,COST_OF_GOAL=800000, DURATION=10, GOAL_BUCKET_ID=3 WHERE GOAL_ID=9;
UPDATE goals SET SHOW_TO_PROFILE_TYPE=8, GOAL_NAME='My 1st Crore ' ,COST_OF_GOAL=10000000, DURATION=15, GOAL_BUCKET_ID=3 WHERE GOAL_ID=10;
UPDATE goals SET SHOW_TO_PROFILE_TYPE=12 , COST_OF_GOAL=200000, DURATION=3, GOAL_BUCKET_ID=1 WHERE GOAL_ID=11;
UPDATE goals SET SHOW_TO_PROFILE_TYPE=9, GOAL_NAME='Starting own Business' ,COST_OF_GOAL=2000000, DURATION=10, GOAL_BUCKET_ID=3 WHERE GOAL_ID=12;
UPDATE goals SET SHOW_TO_PROFILE_TYPE=4, GOAL_NAME='Child Higher Education' ,COST_OF_GOAL=1500000, DURATION=10, GOAL_BUCKET_ID=3 WHERE GOAL_ID=13;
UPDATE goals SET SHOW_TO_PROFILE_TYPE=17,DURATION=0, GOAL_NAME='Child Higher Education-India', GOAL_BUCKET_ID=1 WHERE GOAL_ID=14;
UPDATE goals SET SHOW_TO_PROFILE_TYPE=5, GOAL_NAME='Child Dream Marriage' ,COST_OF_GOAL=2000000, DURATION=15, GOAL_BUCKET_ID=3 WHERE GOAL_ID=15;
UPDATE goals SET SHOW_TO_PROFILE_TYPE=11 , COST_OF_GOAL=2000000, DURATION=10, GOAL_BUCKET_ID=3 WHERE GOAL_ID=16;
UPDATE goals SET SHOW_TO_PROFILE_TYPE=1, GOAL_NAME='Pension/Retirement Plan', COST_OF_GOAL=40000, GOAL_BUCKET_ID=3 WHERE GOAL_ID=17;


UPDATE goal_order_items SET DESCRIPTION='Car Purchase' WHERE USER_ID=190 AND GOAL_ID=1;
UPDATE goal_order_items SET DESCRIPTION='Fund in Need (Emergency Fund)' WHERE USER_ID=190 AND GOAL_ID=2;
UPDATE goal_order_items SET DESCRIPTION='Self Marriage' WHERE USER_ID=190 AND GOAL_ID=4;
UPDATE goal_order_items SET DESCRIPTION='Fund to Save Tax' WHERE USER_ID=190 AND GOAL_ID=8;
UPDATE goal_order_items SET DESCRIPTION='Dream Home' WHERE USER_ID=190 AND GOAL_ID=9;
UPDATE goal_order_items SET DESCRIPTION='Pension/Retirement Plan' WHERE USER_ID=190 AND GOAL_ID=17;


UPDATE goal_order_items SET DESCRIPTION='Car Purchase' WHERE USER_ID=191 AND GOAL_ID=1;
UPDATE goal_order_items SET DESCRIPTION='Fund in Need (Emergency Fund)' WHERE USER_ID=191 AND GOAL_ID=2;
UPDATE goal_order_items SET DESCRIPTION='Self Marriage' WHERE USER_ID=191 AND GOAL_ID=4;
UPDATE goal_order_items SET DESCRIPTION='Fund to Save Tax' WHERE USER_ID=191 AND GOAL_ID=8;
UPDATE goal_order_items SET DESCRIPTION='Dream Home' WHERE USER_ID=191 AND GOAL_ID=9;
UPDATE goal_order_items SET DESCRIPTION='Pension/Retirement Plan' WHERE USER_ID=191 AND GOAL_ID=17;

UPDATE goal_order_items SET DESCRIPTION='Car Purchase' WHERE USER_ID=192 AND GOAL_ID=1;
UPDATE goal_order_items SET DESCRIPTION='Fund in Need (Emergency Fund)' WHERE USER_ID=192 AND GOAL_ID=2;
UPDATE goal_order_items SET DESCRIPTION='Fund to Save Tax' WHERE USER_ID=192 AND GOAL_ID=8;
UPDATE goal_order_items SET DESCRIPTION='Dream Home' WHERE USER_ID=192 AND GOAL_ID=9;
UPDATE goal_order_items SET DESCRIPTION='Pension/Retirement Plan' WHERE USER_ID=192 AND GOAL_ID=17;


UPDATE goal_order_items SET DESCRIPTION='Car Purchase' WHERE USER_ID=193 AND GOAL_ID=1;
UPDATE goal_order_items SET DESCRIPTION='Fund in Need (Emergency Fund)' WHERE USER_ID=193 AND GOAL_ID=2;
UPDATE goal_order_items SET DESCRIPTION='Vacation Planning-Domestic' WHERE USER_ID=193 AND GOAL_ID=5;
UPDATE goal_order_items SET DESCRIPTION='Fund to Save Tax' WHERE USER_ID=193 AND GOAL_ID=8;
UPDATE goal_order_items SET DESCRIPTION='Dream Home' WHERE USER_ID=193 AND GOAL_ID=9;
UPDATE goal_order_items SET DESCRIPTION='Child Higher Education' WHERE USER_ID=193 AND GOAL_ID=14;
UPDATE goal_order_items SET DESCRIPTION='Child Dream Marriage' WHERE USER_ID=193 AND GOAL_ID=15;
UPDATE goal_order_items SET DESCRIPTION='Pension/Retirement Plan' WHERE USER_ID=193 AND GOAL_ID=17;

UPDATE goal_order_items SET DESCRIPTION='Car Purchase' WHERE USER_ID=196 AND GOAL_ID=1;
UPDATE goal_order_items SET DESCRIPTION='Vacation Planning-Domestic' WHERE USER_ID=196 AND GOAL_ID=5;
UPDATE goal_order_items SET DESCRIPTION='Fund to Save Tax' WHERE USER_ID=196 AND GOAL_ID=8;
UPDATE goal_order_items SET DESCRIPTION='Dream Home' WHERE USER_ID=196 AND GOAL_ID=9;
UPDATE goal_order_items SET DESCRIPTION='Pension/Retirement Plan' WHERE USER_ID=196 AND GOAL_ID=17;

UPDATE goal_order_items SET DESCRIPTION='Car Purchase' WHERE USER_ID=197 AND GOAL_ID=1;
UPDATE goal_order_items SET DESCRIPTION='Vacation Planning-Domestic' WHERE USER_ID=197 AND GOAL_ID=5;
UPDATE goal_order_items SET DESCRIPTION='Fund to Save Tax' WHERE USER_ID=197 AND GOAL_ID=8;
UPDATE goal_order_items SET DESCRIPTION='Dream Home' WHERE USER_ID=197 AND GOAL_ID=9;
UPDATE goal_order_items SET DESCRIPTION='Pension/Retirement Plan' WHERE USER_ID=197 AND GOAL_ID=17;

UPDATE goal_order_items SET DESCRIPTION='Dream Home' WHERE USER_ID=198 AND GOAL_ID=9;
UPDATE goal_order_items SET DESCRIPTION='Pension/Retirement Plan' WHERE USER_ID=198 AND GOAL_ID=17;

UPDATE goal_order_items SET DESCRIPTION='Dream Home' WHERE USER_ID=199 AND GOAL_ID=9;
UPDATE goal_order_items SET DESCRIPTION='Pension/Retirement Plan' WHERE USER_ID=199 AND GOAL_ID=17;

UPDATE goal_order_items SET DESCRIPTION='Car Purchase' WHERE USER_ID=201 AND GOAL_ID=1;
UPDATE goal_order_items SET DESCRIPTION='Vacation Planning-Domestic' WHERE USER_ID=201 AND GOAL_ID=5;
UPDATE goal_order_items SET DESCRIPTION='Fund to Save Tax' WHERE USER_ID=201 AND GOAL_ID=8;
UPDATE goal_order_items SET DESCRIPTION='Dream Home' WHERE USER_ID=201 AND GOAL_ID=9;
UPDATE goal_order_items SET DESCRIPTION='Pension/Retirement Plan' WHERE USER_ID=201 AND GOAL_ID=17;

UPDATE goal_order_items SET DESCRIPTION='Car Purchase' WHERE USER_ID=202 AND GOAL_ID=1;
UPDATE goal_order_items SET DESCRIPTION='Vacation Planning-Domestic' WHERE USER_ID=202 AND GOAL_ID=5;
UPDATE goal_order_items SET DESCRIPTION='Fund to Save Tax' WHERE USER_ID=202 AND GOAL_ID=8;
UPDATE goal_order_items SET DESCRIPTION='Dream Home' WHERE USER_ID=202 AND GOAL_ID=9;
UPDATE goal_order_items SET DESCRIPTION='Child Higher Education' WHERE USER_ID=202 AND GOAL_ID=14;
UPDATE goal_order_items SET DESCRIPTION='Child Dream Marriage' WHERE USER_ID=202 AND GOAL_ID=15;
UPDATE goal_order_items SET DESCRIPTION='Pension/Retirement Plan' WHERE USER_ID=202 AND GOAL_ID=17;


UPDATE goal_order_items SET DESCRIPTION='Car Purchase' WHERE USER_ID=203 AND GOAL_ID=1;
UPDATE goal_order_items SET DESCRIPTION='Self Marriage' WHERE USER_ID=203 AND GOAL_ID=4;
UPDATE goal_order_items SET DESCRIPTION='Vacation Planning-Domestic' WHERE USER_ID=203 AND GOAL_ID=5;
UPDATE goal_order_items SET DESCRIPTION='Fund to Save Tax' WHERE USER_ID=203 AND GOAL_ID=8;
UPDATE goal_order_items SET DESCRIPTION='Dream Home' WHERE USER_ID=203 AND GOAL_ID=9;
UPDATE goal_order_items SET DESCRIPTION='Pension/Retirement Plan' WHERE USER_ID=203 AND GOAL_ID=17;


UPDATE goal_order_items SET DESCRIPTION='Car Purchase' WHERE USER_ID=204 AND GOAL_ID=1;
UPDATE goal_order_items SET DESCRIPTION='Vacation Planning-Domestic' WHERE USER_ID=204 AND GOAL_ID=5;
UPDATE goal_order_items SET DESCRIPTION='Fund to Save Tax' WHERE USER_ID=204 AND GOAL_ID=8;
UPDATE goal_order_items SET DESCRIPTION='Dream Home' WHERE USER_ID=204 AND GOAL_ID=9;
UPDATE goal_order_items SET DESCRIPTION='Pension/Retirement Plan' WHERE USER_ID=204 AND GOAL_ID=17;


UPDATE goal_order_items SET DESCRIPTION='Vacation Planning-Domestic' WHERE USER_ID=206 AND GOAL_ID=5;
UPDATE goal_order_items SET DESCRIPTION='Fund to Save Tax' WHERE USER_ID=206 AND GOAL_ID=8;
UPDATE goal_order_items SET DESCRIPTION='Dream Home' WHERE USER_ID=206 AND GOAL_ID=9;
UPDATE goal_order_items SET DESCRIPTION='Child Higher Education' WHERE USER_ID=206 AND GOAL_ID=14;
UPDATE goal_order_items SET DESCRIPTION='Child Dream Marriage' WHERE USER_ID=206 AND GOAL_ID=15;
UPDATE goal_order_items SET DESCRIPTION='Pension/Retirement Plan' WHERE USER_ID=206 AND GOAL_ID=17;


UPDATE goal_order_items SET DESCRIPTION='Self Marriage' WHERE USER_ID=205 AND GOAL_ID=4;
UPDATE goal_order_items SET DESCRIPTION='Vacation Planning-Domestic' WHERE USER_ID=205 AND GOAL_ID=5;
UPDATE goal_order_items SET DESCRIPTION='Fund to Save Tax' WHERE USER_ID=205 AND GOAL_ID=8;
UPDATE goal_order_items SET DESCRIPTION='Dream Home' WHERE USER_ID=205 AND GOAL_ID=9;
UPDATE goal_order_items SET DESCRIPTION='Pension/Retirement Plan' WHERE USER_ID=205 AND GOAL_ID=17;


UPDATE goal_order_items SET DESCRIPTION='Vacation Planning-Domestic' WHERE USER_ID=208 AND GOAL_ID=5;
UPDATE goal_order_items SET DESCRIPTION='Fund to Save Tax' WHERE USER_ID=208 AND GOAL_ID=8;
UPDATE goal_order_items SET DESCRIPTION='Dream Home' WHERE USER_ID=208 AND GOAL_ID=9;
UPDATE goal_order_items SET DESCRIPTION='Child Higher Education' WHERE USER_ID=208 AND GOAL_ID=14;
UPDATE goal_order_items SET DESCRIPTION='Child Dream Marriage' WHERE USER_ID=208 AND GOAL_ID=15;
UPDATE goal_order_items SET DESCRIPTION='Pension/Retirement Plan' WHERE USER_ID=208 AND GOAL_ID=17;


UPDATE goal_order_items SET DESCRIPTION='Vacation Planning-Domestic' WHERE USER_ID=209 AND GOAL_ID=5;
UPDATE goal_order_items SET DESCRIPTION='Lifestyle Needs - Gadgets,etc' WHERE USER_ID=209 AND GOAL_ID=7;
UPDATE goal_order_items SET DESCRIPTION='Fund to Save Tax' WHERE USER_ID=209 AND GOAL_ID=8;
UPDATE goal_order_items SET DESCRIPTION='Dream Home' WHERE USER_ID=209 AND GOAL_ID=9;
UPDATE goal_order_items SET DESCRIPTION='My 1st Crore' WHERE USER_ID=209 AND GOAL_ID=10;
UPDATE goal_order_items SET DESCRIPTION='Child Higher Education' WHERE USER_ID=209 AND GOAL_ID=14;
UPDATE goal_order_items SET DESCRIPTION='Child Dream Marriage' WHERE USER_ID=209 AND GOAL_ID=15;
UPDATE goal_order_items SET DESCRIPTION='Pension/Retirement Plan' WHERE USER_ID=209 AND GOAL_ID=17;


UPDATE goal_order_items SET DESCRIPTION='Self Marriage' WHERE USER_ID=210 AND GOAL_ID=4;
UPDATE goal_order_items SET DESCRIPTION='Dream Home' WHERE USER_ID=210 AND GOAL_ID=9;
UPDATE goal_order_items SET DESCRIPTION='My 1st Crore' WHERE USER_ID=210 AND GOAL_ID=10;
UPDATE goal_order_items SET DESCRIPTION='Pension/Retirement Plan' WHERE USER_ID=210 AND GOAL_ID=17;

UPDATE goal_order_items SET DESCRIPTION='Self Marriage' WHERE USER_ID=211 AND GOAL_ID=4;
UPDATE goal_order_items SET DESCRIPTION='Dream Home' WHERE USER_ID=211 AND GOAL_ID=9;
UPDATE goal_order_items SET DESCRIPTION='Pension/Retirement Plan' WHERE USER_ID=211 AND GOAL_ID=17;


UPDATE goal_order_items SET DESCRIPTION='Vacation Planning-Domestic' WHERE USER_ID=212 AND GOAL_ID=5;
UPDATE goal_order_items SET DESCRIPTION='Lifestyle Needs - Gadgets,etc' WHERE USER_ID=212 AND GOAL_ID=7;
UPDATE goal_order_items SET DESCRIPTION='Fund to Save Tax' WHERE USER_ID=212 AND GOAL_ID=8;
UPDATE goal_order_items SET DESCRIPTION='Dream Home' WHERE USER_ID=212 AND GOAL_ID=9;
UPDATE goal_order_items SET DESCRIPTION='My 1st Crore' WHERE USER_ID=212 AND GOAL_ID=10;
UPDATE goal_order_items SET DESCRIPTION='Starting own Business' WHERE USER_ID=212 AND GOAL_ID=12;
UPDATE goal_order_items SET DESCRIPTION='Pension/Retirement Plan' WHERE USER_ID=212 AND GOAL_ID=17;


UPDATE goal_order_items SET DESCRIPTION='Vacation Planning-Domestic' WHERE USER_ID=213 AND GOAL_ID=5;
UPDATE goal_order_items SET DESCRIPTION='Lifestyle Needs - Gadgets,etc' WHERE USER_ID=213 AND GOAL_ID=7;
UPDATE goal_order_items SET DESCRIPTION='Fund to Save Tax' WHERE USER_ID=213 AND GOAL_ID=8;
UPDATE goal_order_items SET DESCRIPTION='Dream Home' WHERE USER_ID=213 AND GOAL_ID=9;
UPDATE goal_order_items SET DESCRIPTION='My 1st Crore' WHERE USER_ID=213 AND GOAL_ID=10;
UPDATE goal_order_items SET DESCRIPTION='Starting own Business' WHERE USER_ID=213 AND GOAL_ID=12;
UPDATE goal_order_items SET DESCRIPTION='Pension/Retirement Plan' WHERE USER_ID=213 AND GOAL_ID=17;


UPDATE goal_order_items SET DESCRIPTION='Vacation Planning-Domestic' WHERE USER_ID=214 AND GOAL_ID=5;
UPDATE goal_order_items SET DESCRIPTION='Lifestyle Needs - Gadgets,etc' WHERE USER_ID=214 AND GOAL_ID=7;
UPDATE goal_order_items SET DESCRIPTION='Fund to Save Tax' WHERE USER_ID=214 AND GOAL_ID=8;
UPDATE goal_order_items SET DESCRIPTION='Dream Home' WHERE USER_ID=214 AND GOAL_ID=9;
UPDATE goal_order_items SET DESCRIPTION='My 1st Crore' WHERE USER_ID=214 AND GOAL_ID=10;
UPDATE goal_order_items SET DESCRIPTION='Philanthrophy & Charity' WHERE USER_ID=214 AND GOAL_ID=11;
UPDATE goal_order_items SET DESCRIPTION='Starting own Business' WHERE USER_ID=214 AND GOAL_ID=12;
UPDATE goal_order_items SET DESCRIPTION='Pension/Retirement Plan' WHERE USER_ID=214 AND GOAL_ID=17;


UPDATE goal_order_items SET DESCRIPTION='Vacation Planning-Domestic' WHERE USER_ID=215 AND GOAL_ID=5;
UPDATE goal_order_items SET DESCRIPTION='Fund to Save Tax' WHERE USER_ID=215 AND GOAL_ID=8;
UPDATE goal_order_items SET DESCRIPTION='Philanthrophy & Charity' WHERE USER_ID=215 AND GOAL_ID=11;
UPDATE goal_order_items SET DESCRIPTION='Starting own Business' WHERE USER_ID=215 AND GOAL_ID=12;
UPDATE goal_order_items SET DESCRIPTION='Pension/Retirement Plan' WHERE USER_ID=215 AND GOAL_ID=17;


UPDATE goal_order_items SET DESCRIPTION='Vacation Planning-Domestic' WHERE USER_ID=216 AND GOAL_ID=5;
UPDATE goal_order_items SET DESCRIPTION='Lifestyle Needs - Gadgets,etc' WHERE USER_ID=216 AND GOAL_ID=7;
UPDATE goal_order_items SET DESCRIPTION='Fund to Save Tax' WHERE USER_ID=216 AND GOAL_ID=8;
UPDATE goal_order_items SET DESCRIPTION='Dream Home' WHERE USER_ID=216 AND GOAL_ID=9;
UPDATE goal_order_items SET DESCRIPTION='My 1st Crore' WHERE USER_ID=216 AND GOAL_ID=10;
UPDATE goal_order_items SET DESCRIPTION='Starting own Business' WHERE USER_ID=216 AND GOAL_ID=12;
UPDATE goal_order_items SET DESCRIPTION='Pension/Retirement Plan' WHERE USER_ID=216 AND GOAL_ID=17;


UPDATE goal_order_items SET DESCRIPTION='Self Marriage' WHERE USER_ID=217 AND GOAL_ID=4;
UPDATE goal_order_items SET DESCRIPTION='Dream Home' WHERE USER_ID=217 AND GOAL_ID=9;
UPDATE goal_order_items SET DESCRIPTION='My 1st Crore' WHERE USER_ID=217 AND GOAL_ID=10;
UPDATE goal_order_items SET DESCRIPTION='Pension/Retirement Plan' WHERE USER_ID=217 AND GOAL_ID=17;


UPDATE goal_order_items SET DESCRIPTION='Self Marriage' WHERE USER_ID=218 AND GOAL_ID=4;
UPDATE goal_order_items SET DESCRIPTION='Dream Home' WHERE USER_ID=218 AND GOAL_ID=9;
UPDATE goal_order_items SET DESCRIPTION='My 1st Crore' WHERE USER_ID=218 AND GOAL_ID=10;
UPDATE goal_order_items SET DESCRIPTION='Pension/Retirement Plan' WHERE USER_ID=218 AND GOAL_ID=17;


UPDATE goal_order_items SET DESCRIPTION='Vacation Planning-Domestic' WHERE USER_ID=219 AND GOAL_ID=5;
UPDATE goal_order_items SET DESCRIPTION='Fund to Save Tax' WHERE USER_ID=219 AND GOAL_ID=8;
UPDATE goal_order_items SET DESCRIPTION='Dream Home' WHERE USER_ID=219 AND GOAL_ID=9;
UPDATE goal_order_items SET DESCRIPTION='My 1st Crore' WHERE USER_ID=219 AND GOAL_ID=10;
UPDATE goal_order_items SET DESCRIPTION='Pension/Retirement Plan' WHERE USER_ID=219 AND GOAL_ID=17;


UPDATE goal_order_items SET DESCRIPTION='Vacation Planning-Domestic' WHERE USER_ID=221 AND GOAL_ID=5;
UPDATE goal_order_items SET DESCRIPTION='Fund to Save Tax' WHERE USER_ID=221 AND GOAL_ID=8;
UPDATE goal_order_items SET DESCRIPTION='Dream Home' WHERE USER_ID=221 AND GOAL_ID=9;
UPDATE goal_order_items SET DESCRIPTION='My 1st Crore' WHERE USER_ID=221 AND GOAL_ID=10;
UPDATE goal_order_items SET DESCRIPTION='Child Higher Education' WHERE USER_ID=221 AND GOAL_ID=14;
UPDATE goal_order_items SET DESCRIPTION='Child Dream Marriage' WHERE USER_ID=221 AND GOAL_ID=15;
UPDATE goal_order_items SET DESCRIPTION='Pension/Retirement Plan' WHERE USER_ID=221 AND GOAL_ID=17;


UPDATE goal_order_items SET DESCRIPTION='Self Marriage' WHERE USER_ID=222 AND GOAL_ID=4;
UPDATE goal_order_items SET DESCRIPTION='Dream Home' WHERE USER_ID=222 AND GOAL_ID=9;
UPDATE goal_order_items SET DESCRIPTION='Pension/Retirement Plan' WHERE USER_ID=222 AND GOAL_ID=17;

UPDATE goal_order_items SET DESCRIPTION='Self Marriage' WHERE USER_ID=225 AND GOAL_ID=4;
UPDATE goal_order_items SET DESCRIPTION='Dream Home' WHERE USER_ID=225 AND GOAL_ID=9;
UPDATE goal_order_items SET DESCRIPTION='Pension/Retirement Plan' WHERE USER_ID=225 AND GOAL_ID=17;


UPDATE goal_order_items SET DESCRIPTION='Vacation Planning-Domestic' WHERE USER_ID=226 AND GOAL_ID=5;
UPDATE goal_order_items SET DESCRIPTION='Fund to Save Tax' WHERE USER_ID=226 AND GOAL_ID=8;
UPDATE goal_order_items SET DESCRIPTION='Dream Home' WHERE USER_ID=226 AND GOAL_ID=9;
UPDATE goal_order_items SET DESCRIPTION='Child Higher Education' WHERE USER_ID=226 AND GOAL_ID=14;
UPDATE goal_order_items SET DESCRIPTION='Child Dream Marriage' WHERE USER_ID=226 AND GOAL_ID=15;
UPDATE goal_order_items SET DESCRIPTION='Pension/Retirement Plan' WHERE USER_ID=226 AND GOAL_ID=17;


UPDATE goal_order_items SET DESCRIPTION='Vacation Planning-Domestic' WHERE USER_ID=227 AND GOAL_ID=5;
UPDATE goal_order_items SET DESCRIPTION='Fund to Save Tax' WHERE USER_ID=227 AND GOAL_ID=8;
UPDATE goal_order_items SET DESCRIPTION='Dream Home' WHERE USER_ID=227 AND GOAL_ID=9;
UPDATE goal_order_items SET DESCRIPTION='Child Higher Education' WHERE USER_ID=227 AND GOAL_ID=14;
UPDATE goal_order_items SET DESCRIPTION='Child Dream Marriage' WHERE USER_ID=227 AND GOAL_ID=15;
UPDATE goal_order_items SET DESCRIPTION='Pension/Retirement Plan' WHERE USER_ID=227 AND GOAL_ID=17;


UPDATE goal_order_items SET DESCRIPTION='Vacation Planning-Domestic' WHERE USER_ID=228 AND GOAL_ID=5;
UPDATE goal_order_items SET DESCRIPTION='Fund to Save Tax' WHERE USER_ID=228 AND GOAL_ID=8;
UPDATE goal_order_items SET DESCRIPTION='Dream Home' WHERE USER_ID=228 AND GOAL_ID=9;
UPDATE goal_order_items SET DESCRIPTION='Child Higher Education' WHERE USER_ID=228 AND GOAL_ID=14;
UPDATE goal_order_items SET DESCRIPTION='Child Dream Marriage' WHERE USER_ID=228 AND GOAL_ID=15;
UPDATE goal_order_items SET DESCRIPTION='Pension/Retirement Plan' WHERE USER_ID=228 AND GOAL_ID=17;


UPDATE goal_order_items SET DESCRIPTION='Self Marriage' WHERE USER_ID=229 AND GOAL_ID=4;
UPDATE goal_order_items SET DESCRIPTION='Fund to Save Tax' WHERE USER_ID=229 AND GOAL_ID=8;
UPDATE goal_order_items SET DESCRIPTION='Dream Home' WHERE USER_ID=229 AND GOAL_ID=9;
UPDATE goal_order_items SET DESCRIPTION='Pension/Retirement Plan' WHERE USER_ID=229 AND GOAL_ID=17;

UPDATE goal_order_items SET DESCRIPTION='Self Marriage' WHERE USER_ID=230 AND GOAL_ID=4;
UPDATE goal_order_items SET DESCRIPTION='Fund to Save Tax' WHERE USER_ID=230 AND GOAL_ID=8;
UPDATE goal_order_items SET DESCRIPTION='Dream Home' WHERE USER_ID=230 AND GOAL_ID=9;
UPDATE goal_order_items SET DESCRIPTION='Pension/Retirement Plan' WHERE USER_ID=230 AND GOAL_ID=17;


UPDATE goal_order_items SET DESCRIPTION='Self Marriage' WHERE USER_ID=233 AND GOAL_ID=4;
UPDATE goal_order_items SET DESCRIPTION='Dream Home' WHERE USER_ID=233 AND GOAL_ID=9;
UPDATE goal_order_items SET DESCRIPTION='Pension/Retirement Plan' WHERE USER_ID=233 AND GOAL_ID=17;


UPDATE goal_order_items SET DESCRIPTION='Self Marriage' WHERE USER_ID=232 AND GOAL_ID=4;
UPDATE goal_order_items SET DESCRIPTION='Fund to Save Tax' WHERE USER_ID=232 AND GOAL_ID=8;
UPDATE goal_order_items SET DESCRIPTION='Dream Home' WHERE USER_ID=232 AND GOAL_ID=9;
UPDATE goal_order_items SET DESCRIPTION='Pension/Retirement Plan' WHERE USER_ID=232 AND GOAL_ID=17


UPDATE goal_order_items SET DESCRIPTION='Vacation Planning-Domestic' WHERE USER_ID=234 AND GOAL_ID=5;
UPDATE goal_order_items SET DESCRIPTION='Lifestyle Needs - Gadgets,etc' WHERE USER_ID=234 AND GOAL_ID=7;
UPDATE goal_order_items SET DESCRIPTION='Fund to Save Tax' WHERE USER_ID=234 AND GOAL_ID=8;
UPDATE goal_order_items SET DESCRIPTION='Dream Home' WHERE USER_ID=234 AND GOAL_ID=9;
UPDATE goal_order_items SET DESCRIPTION='My 1st Crore' WHERE USER_ID=234 AND GOAL_ID=10;
UPDATE goal_order_items SET DESCRIPTION='Philanthrophy & Charity' WHERE USER_ID=234 AND GOAL_ID=11;
UPDATE goal_order_items SET DESCRIPTION='Starting own Business' WHERE USER_ID=234 AND GOAL_ID=12;
UPDATE goal_order_items SET DESCRIPTION='Pension/Retirement Plan' WHERE USER_ID=234 AND GOAL_ID=17;

UPDATE goal_order_items SET DESCRIPTION='Vacation Planning-Domestic' WHERE USER_ID=235 AND GOAL_ID=5;
UPDATE goal_order_items SET DESCRIPTION='Fund to Save Tax' WHERE USER_ID=235 AND GOAL_ID=8;
UPDATE goal_order_items SET DESCRIPTION='Dream Home' WHERE USER_ID=235 AND GOAL_ID=9;
UPDATE goal_order_items SET DESCRIPTION='Pension/Retirement Plan' WHERE USER_ID=235 AND GOAL_ID=17;


UPDATE goal_order_items SET DESCRIPTION='Self Marriage' WHERE USER_ID=236 AND GOAL_ID=4;
UPDATE goal_order_items SET DESCRIPTION='Vacation Planning-Domestic' WHERE USER_ID=236 AND GOAL_ID=5;
UPDATE goal_order_items SET DESCRIPTION='Fund to Save Tax' WHERE USER_ID=236 AND GOAL_ID=8;
UPDATE goal_order_items SET DESCRIPTION='Dream Home' WHERE USER_ID=236 AND GOAL_ID=9;
UPDATE goal_order_items SET DESCRIPTION='Pension/Retirement Plan' WHERE USER_ID=236 AND GOAL_ID=17;
UPDATE goal_order_items SET DESCRIPTION='Pay Off Debt' WHERE USER_ID=236 AND GOAL_ID=35;

UPDATE goal_order_items SET FIELD1=0;

UPDATE orders SET GOAL_NAME='Pension/Retirement Plan' WHERE ORDERS_ID=121;

UPDATE orders SET GOAL_NAME='Pension/Retirement Plan' WHERE ORDERS_ID=383;

UPDATE orders SET GOAL_NAME='Pension/Retirement Plan' WHERE ORDERS_ID=741;

UPDATE orders SET GOAL_NAME='Pension/Retirement Plan' WHERE ORDERS_ID=789;

UPDATE orders SET GOAL_NAME='Pension/Retirement Plan' WHERE ORDERS_ID=827;

UPDATE orders SET GOAL_NAME='Pension/Retirement Plan' WHERE ORDERS_ID=840;

UPDATE goal_order_items SET DESCRIPTION='Pension/Retirement Plan' WHERE GOAL_ID=17;

/*** Scheme Alter Query ********/
UPDATE scheme SET DISPLAY=0 , KEYWORD='ICICI-Prudential-Bluechip-Fund---Institutional-I---Growth' WHERE SCHEME_CODE='FOCUS-INST';
UPDATE scheme SET DISPLAY=0 , KEYWORD='ICICI-PRUDENTIAL-INDEX-INSTITUTIONAL-OPTION-I-GROWTH' WHERE SCHEME_CODE='ICICI1406-ICICI-GR';
UPDATE scheme SET DISPLAY=0 , KEYWORD='ICICI-PRUDENTIAL-INFRASTRUCTURE-FUND---DIVIDEND-PAYOUT' WHERE SCHEME_CODE='IFD-ICICIPRU-DP';
UPDATE scheme SET DISPLAY=0 , KEYWORD='ICICI-PRUDENTIAL-INFRASTRUCTURE-FUND---DIVIDEND-REINVESTMENT' WHERE SCHEME_CODE='IFD-ICICIPRU-DR';
UPDATE scheme SET DISPLAY=0 , KEYWORD='ICICI-PRUDENTIAL-INFRASTRUCTURE-FUND---GROWTH' WHERE SCHEME_CODE='IFG-ICICIPRU-GR';
UPDATE scheme SET DISPLAY=0 , KEYWORD='ICICI-PRUDENTIAL-SMALLCAP-FUND---INSTITUTIONAL-GROWTH' WHERE SCHEME_CODE='INASTA-INST';
UPDATE scheme SET DISPLAY=0 , KEYWORD='ICICI-PRUDENTIAL-EXPORTS-AND-SERVICES---DIVIDEND-PAYOUT' WHERE SCHEME_CODE='SID-ICICI-DP';
UPDATE scheme SET DISPLAY=0 , KEYWORD='ICICI-PRUDENTIAL-EXPORTS-AND-SERVICES---DIVIDEND-REINVESTMENT' WHERE SCHEME_CODE='SID-ICICI-DR';
UPDATE scheme SET DISPLAY=0 , KEYWORD='ICICI-PRUDENTIAL-EXPORTS-AND-SERVICES---GROWTH' WHERE SCHEME_CODE='SIG-ICICI-DP';


/*** New Query Date 13-02-2019 ***/
UPDATE goals  SET COST_OF_GOAL=500000.00000, SHOW_TO_PROFILE_TYPE=6 WHERE GOAL_ID=1;
UPDATE goals  SET SHOW_TO_PROFILE_TYPE=4, DURATION=7 WHERE GOAL_ID=4;
UPDATE goals  SET SHOW_TO_PROFILE_TYPE=3, DURATION=3 WHERE GOAL_ID=6;
UPDATE goals  SET SHOW_TO_PROFILE_TYPE=10 WHERE GOAL_ID=7;
UPDATE goals  SET GOAL_NAME='Dream Home (Down Pymt.)', COST_OF_GOAL=800000.00000, SHOW_TO_PROFILE_TYPE=7, DURATION=12 WHERE GOAL_ID=9;
UPDATE goals  SET SHOW_TO_PROFILE_TYPE=8, DURATION=20 WHERE GOAL_ID=10;
UPDATE goals  SET SHOW_TO_PROFILE_TYPE=12 WHERE GOAL_ID=11;
UPDATE goals  SET SHOW_TO_PROFILE_TYPE=9 WHERE GOAL_ID=12;
UPDATE goals  SET SHOW_TO_PROFILE_TYPE=2, DURATION=10 WHERE GOAL_ID=13;
UPDATE goals  SET SHOW_TO_PROFILE_TYPE=5, COST_OF_GOAL=2000000 WHERE GOAL_ID=15;
UPDATE goals  SET GOAL_NAME='My Second Home (Down Pymt.)', SHOW_TO_PROFILE_TYPE=11,COST_OF_GOAL=2000000 WHERE GOAL_ID=16;
UPDATE goals  SET SHOW_TO_PROFILE_TYPE=1 WHERE GOAL_ID=17;

/*** New Query Date 14-02-2019 ***/
INSERT INTO `store_conf` (`STORE_CONF_ID`,`KEYWORD`,`KEYWORD_VALUE`) VALUES (45,'PREVIOUD_DATE_FOR_SIP_INSTALLMENT_UPDATE','13 Feb 2019');
ALTER TABLE goals MODIFY SHOW_TO_PROFILE_TYPE INTEGER(10);
INSERT INTO `store_conf` (`STORE_CONF_ID`,`KEYWORD`,`KEYWORD_VALUE`) VALUES (46,'MAXIMUM_INSTALLMENT_FOR_SIP','240');

INSERT INTO `store_conf` (`STORE_CONF_ID`,`KEYWORD`,`KEYWORD_VALUE`) VALUES (47,'REDUMPTION_TIME','5');


DELETE FROM scheme WHERE SCHEME_CODE='BO176-DR';
DELETE FROM scheme WHERE SCHEME_CODE='BO178-DR';
DELETE FROM scheme WHERE SCHEME_CODE='BO180-DR';
DELETE FROM scheme WHERE SCHEME_CODE='BO182-DR';
DELETE FROM scheme WHERE SCHEME_CODE='BO184-DR';
DELETE FROM scheme WHERE SCHEME_CODE='BO186-DR';
DELETE FROM scheme WHERE SCHEME_CODE='BO188-DR';
DELETE FROM scheme WHERE SCHEME_CODE='449-DP';
DELETE FROM scheme WHERE SCHEME_CODE='449-DR';
DELETE FROM scheme WHERE SCHEME_CODE='BO162-DR';
DELETE FROM scheme WHERE SCHEME_CODE='BO164-DR';
DELETE FROM scheme WHERE SCHEME_CODE='BO166-DR';
DELETE FROM scheme WHERE SCHEME_CODE='BO168-DR';
DELETE FROM scheme WHERE SCHEME_CODE='BO170-DR';
DELETE FROM scheme WHERE SCHEME_CODE='BO172-DR';
DELETE FROM scheme WHERE SCHEME_CODE='BO174-DR';
DELETE FROM scheme WHERE SCHEME_CODE='SBD543D-DP';
DELETE FROM scheme WHERE SCHEME_CODE='SBD543G-GR';
DELETE FROM scheme WHERE SCHEME_CODE='QMFTS-DR';
DELETE FROM scheme WHERE SCHEME_CODE='QMFTS-DR-L1';
DELETE FROM scheme WHERE SCHEME_CODE='BXBA074-DR';
DELETE FROM scheme WHERE SCHEME_CODE='BXBA074-DR-L1';
DELETE FROM scheme WHERE SCHEME_CODE='DS1809-GR';
DELETE FROM scheme WHERE SCHEME_CODE='DS1810-DP';
DELETE FROM scheme WHERE SCHEME_CODE='DS1811-DP';
DELETE FROM scheme WHERE SCHEME_CODE='LT242D-DP';
DELETE FROM scheme WHERE SCHEME_CODE='LT242D-DP-L1';
DELETE FROM scheme WHERE SCHEME_CODE='KM188DR-DR';
DELETE FROM scheme WHERE SCHEME_CODE='KM188DR-DR-L1';
DELETE FROM scheme WHERE SCHEME_CODE='KO188-DP';
DELETE FROM scheme WHERE SCHEME_CODE='KO188-DP-L1';


/** New Queries For 06-03-2019****/
ALTER TABLE orders ADD COLUMN FOLLIO_No VARCHAR(126) DEFAULT NULL;

/** New Query Date 08-03-2019 **/
INSERT INTO `store_conf` (`STORE_CONF_ID`,`KEYWORD`,`KEYWORD_VALUE`) VALUES (48,'NO_OF_ITERATION_FOR_PREVIOUS_SIP_INSTALLMENT','4');


/*** New Query Date 09-03-2019 ***/
ALTER TABLE user_enquiry ADD COLUMN `STATUS` VARCHAR(50) DEFAULT 'Not Reply';

/*****New Query 12-03-2019*************/
ALTER TABLE ORDERS ADD COLUMN TRANFER_IN_ID INT(50) DEFAULT 0;


/*** New Query 14-03-2019 ********/
DROP TABLE goal_comb_rel;
DROP TABLE sip_profile_comb;
DROP TABLE sip_user_history;
DROP TABLE guest_user;

/*** New Query 16-03-2019 ***/
UPDATE scheme SET AMC_CODE='DSP_MF'  WHERE AMC_CODE='DSPBLACKROCK';



/*** New Query 26-03-2019 ***/
CREATE TABLE `consolidated_portfollio` (
  `Consolidated_Portfollio_Id` INT(50) NOT NULL AUTO_INCREMENT,
  `Order_Id` INT(50) DEFAULT NULL,
  `Current_Amount` DECIMAL(20,5) DEFAULT '0.00000',
  `Scheme_Code` VARCHAR(126) DEFAULT NULL,
  `User_Id` INT(50) DEFAULT NULL,
  `Client_Code` VARCHAR(126) DEFAULT NULL,
  `STATUS` VARCHAR(126) DEFAULT NULL,
  `STATUS_CODE` INT(50) DEFAULT '0',
  `Last_Nav_Updated_date` VARCHAR(126) DEFAULT NULL,
  `FOLIO_NO` VARCHAR(126) DEFAULT NULL,
  `SIP_Regn_No` BIGINT(50) DEFAULT NULL,
  `INVESTED_AMOUNT` DECIMAL(20,3) DEFAULT NULL,
  `ALLOTED_UNIT` DECIMAL(20,3) DEFAULT NULL,
  `Last_Redumption_Updated_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `FIELD1` VARCHAR(126) DEFAULT NULL,
  `FIELD2` VARCHAR(126) DEFAULT NULL,
  `FIELD3` INT(50) DEFAULT NULL,
  `FIELD4` DECIMAL(20,3) DEFAULT NULL,
  PRIMARY KEY (`Consolidated_Portfollio_Id`)
) ENGINE=INNODB AUTO_INCREMENT=151 DEFAULT CHARSET=utf8

/** New Query 27-03-2019**/
ALTER TABLE redumption_management ADD COLUMN SCHEME_CODE VARCHAR(50) DEFAULT NULL;
ALTER TABLE redumption_management CHANGE FIELD3 REDEEM_ORDER_ID VARCHAR(50) DEFAULT NULL;
/* NEW qUERY FOR 28-03-2019**/
ALTER TABLE consolidated_portfollio CHANGE FIELD3 TRANFER_IN_ID INT(50);



/* New Query AT 25-04-2019 **/
ALTER TABLE allotment_status_report_userdata ADD COLUMN GOAL_ID INT(50) DEFAULT 0;
ALTER TABLE allotment_status_report_userdata ADD COLUMN GOAL_NAME VARCHAR(512) DEFAULT NULL;

ALTER TABLE order_status_report_userdata ADD COLUMN GOAL_ID INT(50) DEFAULT 0;
ALTER TABLE order_status_report_userdata ADD COLUMN GOAL_NAME VARCHAR(512) DEFAULT NULL;

ALTER TABLE consolidated_portfollio ADD COLUMN GOAL_ID INT(50) DEFAULT 0;
ALTER TABLE consolidated_portfollio ADD COLUMN GOAL_NAME VARCHAR(512) DEFAULT NULL;