INSERT INTO role(ROLE_ID, ROLE_NAME) VALUES ('1','ADMIN');
INSERT INTO role(ROLE_ID, ROLE_NAME) VALUES ('2', 'AGENT');
INSERT INTO role(ROLE_ID, ROLE_NAME) VALUES ('3', 'MANAGER');
INSERT INTO role(ROLE_ID, ROLE_NAME) VALUES ('4', 'USER');


INSERT INTO `go4wealthdb`.`authority` (`AUTHORITY_TYPE`) VALUES ('USER_ROLE');
INSERT INTO `go4wealthdb`.`authority` (`AUTHORITY_TYPE`) VALUES ('ADMIN_ROLE');
INSERT INTO `go4wealthdb`.`authority` (`AUTHORITY_TYPE`) VALUES ('AGENT_ROLE');


INSERT  INTO `user`(`USER_ID`,`username`,`PASSWORD`,`MOBILE_NUMBER`,`REGISTER_TYPE`,`FIRST_NAME`,`LAST_NAME`,`GENDER`,`DATE_OF_BIRTH`,`CREATED_TIMESTAMP`,`UPDATED_DATE_TIME`,`FIELD1`,`FIELD2`,`FIELD3`,`FIELD4`,`STATUS`) VALUES (3,'8859788733','$2a$12$zPSs77I7DaCRV85ESP0ZwODEU1xXOIvcb4/xRiNk9Gj6PvX.fQazq','8859788733','MO',NULL,NULL,NULL,NULL,'2018-04-25 20:42:17','2018-04-25 20:42:59',NULL,NULL,NULL,NULL,NULL);