
CREATE TABLE pan_details (
  USER_ID int(50) NOT NULL,
  PAN_NO varchar(50) NOT NULL,  
  DATE_OF_BIRTH timestamp NOT NULL,
  GENDER varchar(50) NOT NULL,
  VERIFIED varchar(50),
  PAN_CARD_SELFIE_VIDEO varchar(256),
  FIELD1 int(50) DEFAULT NULL,
  FIELD2 varchar(128) DEFAULT NULL,
  FIELD3 varchar(256) DEFAULT NULL,
  UNIQUE (PAN_NO),
  PRIMARY KEY (USER_ID),
  FOREIGN KEY (USER_ID) REFERENCES user (USER_ID)
);

CREATE TABLE bank_details (
  USER_ID int(50) NOT NULL,
  ACCOUNT_NO varchar(50) NOT NULL,  
  IFSC varchar(50) NOT NULL,
  CONFIRM varchar(20),
  BANK_NAME varchar(100),
  BANK_ADDRESS varchar(256),
  BANK_BRANCH varchar(100),
  NOMINEE_NAME varchar(50),
  NOMINEE_RELATION varchar(50),
  SIGNATURE_IMAGE varchar(256),
  FIELD1 int(50) DEFAULT NULL,
  FIELD2 varchar(128) DEFAULT NULL,
  FIELD3 varchar(256) DEFAULT NULL,
  UNIQUE (ACCOUNT_NO),
  PRIMARY KEY (USER_ID),
  FOREIGN KEY (USER_ID) REFERENCES user (USER_ID)
);

CREATE TABLE kyc_details (
  USER_ID int(50) NOT NULL,
  MOTHER_NAME varchar(50),  
  MARITAL_STATUS varchar(20),
  PHOTOGRAPH varchar(256),
  PAN_CARD_IMAGE varchar(256),  
  FIELD1 int(50) DEFAULT NULL,
  FIELD2 varchar(128) DEFAULT NULL,
  FIELD3 varchar(256) DEFAULT NULL,
  PRIMARY KEY (USER_ID),
  FOREIGN KEY (USER_ID) REFERENCES user (USER_ID)
);

CREATE TABLE address_proof (
  ADDRESS_PROOF_ID int(50) NOT NULL AUTO_INCREMENT,
  USER_ID int(50) NOT NULL,
  ADDRESS_PROOF_NAME varchar(50) NOT NULL,
  ADDRESS_PROOF_NO varchar(50),
  FRONT_IMAGE varchar(256),  
  BACK_IMAGE varchar(256),  
  ADDRESS varchar(256), 
  PINCODE varchar(10),
  CITY varchar(100), 
  STATE varchar(100),   
  FIELD1 int(50) DEFAULT NULL,
  FIELD2 varchar(128) DEFAULT NULL,
  FIELD3 varchar(256) DEFAULT NULL,
  UNIQUE (ADDRESS_PROOF_NO),
  PRIMARY KEY (ADDRESS_PROOF_ID),
  FOREIGN KEY (USER_ID) REFERENCES user (USER_ID)
);

ALTER TABLE pan_details MODIFY DATE_OF_BIRTH TIMESTAMP NULL;

ALTER TABLE pan_details MODIFY GENDER VARCHAR(50) NULL;

ALTER TABLE pan_details ADD FULL_NAME VARCHAR(100) NULL;

ALTER TABLE bank_details ADD ACCOUNT_TYPE VARCHAR(10) NULL;

ALTER TABLE bank_details ADD MICR_CODE VARCHAR(100) NULL;

ALTER TABLE bank_details ADD START_DATE TIMESTAMP NULL;

ALTER TABLE bank_details ADD END_DATE TIMESTAMP NULL;

ALTER TABLE kyc_details ADD FATHER_NAME VARCHAR(50) DEFAULT NULL;

