DROP TABLE ORDERS_ITEM;
DROP TABLE ORDERS;
DROP TABLE SCHEME_CODE_MAPPING;
DROP TABLE SCHEME;
DROP TABLE SCHEME_SUB_CATEGORY;
DROP TABLE SCHEME_CATEGORY;
DROP TABLE FUND_HOUSES;


CREATE TABLE `FUND_HOUSES` (
`FUND_HOUSE_ID` INT(50) NOT NULL AUTO_INCREMENT,
`FUND_HOUSE_NAME` VARCHAR(126) DEFAULT NULL,
`FUND_NAME` VARCHAR(126) DEFAULT NULL,
`FUND_SPONSOR` VARCHAR(126) DEFAULT NULL,
`FUND_RELEASE_DATE` TIMESTAMP DEFAULT '0000-00-00 00:00:00',
`AMC_ADDRESS` VARCHAR(126) DEFAULT NULL,
`WEBSITE` VARCHAR(126) DEFAULT NULL,
`FIELD1` VARCHAR(128) DEFAULT NULL,
`FIEL23` VARCHAR(128) DEFAULT NULL,
PRIMARY KEY (`FUND_HOUSE_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;


CREATE TABLE `SCHEME_CATEGORY` (
`SCHEME_CATEGORY_ID` INT(50) NOT NULL AUTO_INCREMENT,
`CATEGORY` VARCHAR(126) DEFAULT NULL,
 PRIMARY KEY (`SCHEME_CATEGORY_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;


CREATE TABLE `SCHEME_SUB_CATEGORY`(
`SCHEME_SUB_CATEGORY_ID` INT(50) NOT NULL AUTO_INCREMENT,
`SUB_CATEGORY` VARCHAR(126) DEFAULT NULL,
PRIMARY KEY (`SCHEME_SUB_CATEGORY_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;





/*** New Table ***/
CREATE TABLE `SCHEME_CODE_MAPPING` (
`SCHEME_CODE_MAPPING_ID` INT(50) NOT NULL AUTO_INCREMENT,
`SCHEME_CODE` VARCHAR(126) DEFAULT NULL,
`RTA_SCHEME_CODE` VARCHAR(126) DEFAULT NULL,
`AMC_SCHEME_CODE` VARCHAR(126) DEFAULT NULL,
PRIMARY KEY (`SCHEME_CODE_MAPPING_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;


ALTER TABLE SCHEME ADD UNIQUE_NO INT(10) NOT NULL;
ALTER TABLE SCHEME ADD SCHEME_CODE VARCHAR(126) NOT NULL;
ALTER TABLE SCHEME ADD AMC_CODE VARCHAR(126) DEFAULT NULL;
ALTER TABLE SCHEME CHANGE `SCHEME_LAUNCH_DATE` `SCHEME_LAUNCH_DATE` TIMESTAMP DEFAULT '0000-00-00 00:00:00';


/** New Table For NAV_MASTER **/
CREATE TABLE `NAV_MASTER` (
`NAV_MASTER_ID` INT(50) NOT NULL AUTO_INCREMENT,
`SCHEME_CODE` VARCHAR(126) DEFAULT NULL,
`SCHEME_NAME` VARCHAR(126) DEFAULT NULL,
`RTA_SCHEME_CODE` VARCHAR(126) DEFAULT NULL,
`RTA_CODE` VARCHAR(126) DEFAULT NULL,
`ISIN_CODE` VARCHAR(126) DEFAULT NULL,
`NAV_DATE` VARCHAR(126) DEFAULT NULL,
`NAV_VALUE` VARCHAR(126) DEFAULT NULL,
`DIVIDEND_REINVEST_FLAG` VARCHAR(126) DEFAULT NULL,
PRIMARY KEY (`NAV_MASTER_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `orders` (
  `ORDERS_ID` int(50) NOT NULL AUTO_INCREMENT,
  `USER_ID` int(50) NOT NULL,
  `TOTALPRODUCT` decimal(20,5) NOT NULL,
  `TOTALTAX` decimal(20,5) NOT NULL DEFAULT '0.00000',
  `DESCRIPTION` varchar(254) DEFAULT NULL,
  `LOCKED` char(1) DEFAULT NULL,
  `TIMEPLACED` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `LASTUPDATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `STATUS` char(3) NOT NULL,
  `TOTALADJUSTMENT` decimal(20,5) NOT NULL DEFAULT '0.00000',
  `TYPE` char(7) DEFAULT NULL,
  `CSR_MEMBER_ID` bigint(20) DEFAULT NULL,
  `EXPIREDATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `FIELD1` int(11) DEFAULT NULL,
  `FIELD2` varchar(128) DEFAULT NULL,
  `FIELD3` varchar(254) DEFAULT NULL,
  `startdate` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `address_id` bigint(20) NOT NULL,
  PRIMARY KEY (`ORDERS_ID`),
  KEY `address_id` (`address_id`),
  KEY `USER_ID` (`USER_ID`),
  FOREIGN KEY (`USER_ID`) REFERENCES `user` (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8;


CREATE TABLE `order_item` (
  `ORDER_ITEM_ID` int(50) NOT NULL AUTO_INCREMENT,
  `ORDERS_ID` int(50) NOT NULL,
  `SCHEME_ID` int(50) NOT NULL,
  `PRODUCTPRICE` decimal(20,5) NOT NULL,
  `STATUS` char(3) NOT NULL,
  `LASTCREATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `LASTUPDATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `TIMERELEASED` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `TIMESHIPED` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `QUANTITY` double NOT NULL,
  `TAXAMOUNT` decimal(20,5) NOT NULL DEFAULT '0.00000',
  `TOTALADJUSTMENT` decimal(20,5) NOT NULL DEFAULT '0.00000',
  `DESCRIPTION` varchar(254) DEFAULT NULL,
  `FIELD1` int(11) DEFAULT NULL,
  `FIELD2` varchar(128) DEFAULT NULL,
  `FIELD3` varchar(254) DEFAULT NULL,
  PRIMARY KEY (`ORDER_ITEM_ID`),
  KEY `ORDERS_ID` (`ORDERS_ID`),
  KEY `SCHEME_ID` (`SCHEME_ID`),
  CONSTRAINT `order_item_ibfk_1` FOREIGN KEY (`ORDERS_ID`) REFERENCES `orders` (`ORDERS_ID`),
  CONSTRAINT `order_item_ibfk_2` FOREIGN KEY (`SCHEME_ID`) REFERENCES `scheme` (`SCHEME_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;

CREATE TABLE `system_properties` (
  `PROPERTY_KEY` varchar(50) NOT NULL,
  `PROPERTY_VALUE` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



CREATE TABLE `SCHEME` (
`SCHEME_ID` INT(50) NOT NULL AUTO_INCREMENT,
`UNIQUE_NO` INT(10) DEFAULT NULL,
`SCHEME_CODE` VARCHAR(126) DEFAULT NULL,
`RTA_SCHEME_CODE` VARCHAR(50) DEFAULT NULL,
`AMC_SCHEME_CODE` VARCHAR(50) DEFAULT NULL,
`ISIN` VARCHAR(126) DEFAULT NULL,
`AMC_CODE` VARCHAR(126) DEFAULT NULL,
`SCHEME_TYPE` VARCHAR(126) DEFAULT NULL,
`SCHEME_PLAN` VARCHAR(126) DEFAULT NULL,
`SCHEME_NAME` VARCHAR(256) DEFAULT NULL,
`PURCHASE_ALLOWED` VARCHAR(5) DEFAULT NULL,
`PURCHASE_TRANSACTION_MODE` VARCHAR(126) DEFAULT NULL,
`MINIMUN_PURCHASE_AMOUNT` VARCHAR(126) DEFAULT NULL,
`ADDITIONAL_PURCHASE_AMOUNT` VARCHAR(126) DEFAULT NULL,
`MAXIMUM_PURCHASE_AMOUNT` VARCHAR(126) DEFAULT NULL,
`PURCHASE_AMOUNT_MULTIPLIER` VARCHAR(126) DEFAULT NULL,
`PURCHASE_CUTOFF_TIME` VARCHAR(126) DEFAULT NULL,
`REDEMPTION_ALLOWED` VARCHAR(5) DEFAULT NULL,
`REDEMPTION_TRANSACTION_MODE` VARCHAR(126) DEFAULT NULL,
`MINIMUM_REDEMPTION_QTY` VARCHAR(126) DEFAULT NULL,
`REDEMPTION_QTY_MULTIPLIER` VARCHAR(126) DEFAULT NULL,
`MAXIMUM_REDEMPTION_QTY` VARCHAR(126) DEFAULT NULL,
`REDEMPTION_AMOUNT_MINIMUM` VARCHAR(126) DEFAULT NULL,
`REDEMPTION_AMOUNT_MAXIMUM` VARCHAR(126) DEFAULT NULL,
`REDEMPTION_AMOUNT_MULTIPLE` VARCHAR(126) DEFAULT NULL,
`REDEMPTION_CUTOFF_TIME` VARCHAR(126) DEFAULT NULL,
`RTA_AGENT_CODE` VARCHAR(126) DEFAULT NULL,
`AMC_ACTIVE_FLAG` VARCHAR(126) DEFAULT NULL,
`DIVIDEND_REINVESTMENT_FLAG` VARCHAR(5) DEFAULT NULL,
`SIP_FLAG` VARCHAR(5) DEFAULT NULL,
`STP_FLAG` VARCHAR(5) DEFAULT NULL,
`SWP_FLAG` VARCHAR(5) DEFAULT NULL,
`SWITCH_FLAG` VARCHAR(5) DEFAULT NULL,
`SETTLEMENT_TYPE` VARCHAR(126) DEFAULT NULL,
`AMC_IND` VARCHAR(126) DEFAULT NULL,
`FACE_VALUE` VARCHAR(126) DEFAULT NULL,
`START_DATE` VARCHAR(126) DEFAULT NULL,
`END_DATE` VARCHAR(126) DEFAULT NULL,
`EXIT_LOAD_FLAG` VARCHAR(5) DEFAULT NULL,
`EXIT_LOAD` VARCHAR(512) DEFAULT NULL,
`LOCK_IN_PERIOD_FLAG` VARCHAR(126) DEFAULT NULL,
`LOCK_IN_PERIOD` VARCHAR(126) DEFAULT NULL,
`CHANNEL_PARTNER_CODE` VARCHAR(126) DEFAULT NULL,
`AMFI_CODE` INT(50) NOT NULL,
`BENCHMARK_CODE` VARCHAR(126) DEFAULT NULL,
`RATING` VARCHAR(126) DEFAULT NULL,
`NFO_DATE` TIMESTAMP DEFAULT '0000-00-00 00:00:00', 
`STATUS` VARCHAR(126) DEFAULT NULL,
`REGISTRAR_TRANSFER_AGENT` VARCHAR(126) DEFAULT NULL,
`RISK` VARCHAR(126) DEFAULT NULL,
`YEAR` VARCHAR(126) DEFAULT NULL,
`RETURN_VALUE` VARCHAR(126) DEFAULT NULL,
`MIN_SIP_AMOUNT` VARCHAR(126) DEFAULT NULL,
`FIELD1` VARCHAR(126) DEFAULT NULL,
`FIELD2` VARCHAR(126) DEFAULT NULL,
PRIMARY KEY (`SCHEME_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;


CREATE TABLE `UNIQUE_SCHEME` (
`UNIQUE_SCHEME_ID` INT(50) NOT NULL AUTO_INCREMENT,
`UNIQUE_NO` INT(10) DEFAULT NULL,
`SCHEME_CODE` VARCHAR(126) DEFAULT NULL,
`RTA_SCHEME_CODE` VARCHAR(50) DEFAULT NULL,
`AMC_SCHEME_CODE` VARCHAR(50) DEFAULT NULL,
`ISIN` VARCHAR(126) DEFAULT NULL,
`AMC_CODE` VARCHAR(126) DEFAULT NULL,
`SCHEME_TYPE` VARCHAR(126) DEFAULT NULL,
`SCHEME_PLAN` VARCHAR(126) DEFAULT NULL,
`SCHEME_NAME` VARCHAR(126) DEFAULT NULL,
`PURCHASE_ALLOWED` VARCHAR(5) DEFAULT NULL,
`PURCHASE_TRANSACTION_MODE` VARCHAR(126) DEFAULT NULL,
`MINIMUN_PURCHASE_AMOUNT` VARCHAR(126) DEFAULT NULL,
`ADDITIONAL_PURCHASE_AMOUNT` VARCHAR(126) DEFAULT NULL,
`MAXIMUM_PURCHASE_AMOUNT` VARCHAR(126) DEFAULT NULL,
`PURCHASE_AMOUNT_MULTIPLIER` VARCHAR(126) DEFAULT NULL,
`PURCHASE_CUTOFF_TIME` VARCHAR(126) DEFAULT NULL,
`REDEMPTION_ALLOWED` VARCHAR(5) DEFAULT NULL,
`REDEMPTION_TRANSACTION_MODE` VARCHAR(126) DEFAULT NULL,
`MINIMUM_REDEMPTION_QTY` VARCHAR(126) DEFAULT NULL,
`REDEMPTION_QTY_MULTIPLIER` VARCHAR(126) DEFAULT NULL,
`MAXIMUM_REDEMPTION_QTY` VARCHAR(126) DEFAULT NULL,
`REDEMPTION_AMOUNT_MINIMUM` VARCHAR(126) DEFAULT NULL,
`REDEMPTION_AMOUNT_MAXIMUM` VARCHAR(126) DEFAULT NULL,
`REDEMPTION_AMOUNT_MULTIPLE` VARCHAR(126) DEFAULT NULL,
`REDEMPTION_CUTOFF_TIME` VARCHAR(126) DEFAULT NULL,
`RTA_AGENT_CODE` VARCHAR(126) DEFAULT NULL,
`AMC_ACTIVE_FLAG` VARCHAR(126) DEFAULT NULL,
`DIVIDEND_REINVESTMENT_FLAG` VARCHAR(5) DEFAULT NULL,
`SIP_FLAG` VARCHAR(5) DEFAULT NULL,
`STP_FLAG` VARCHAR(5) DEFAULT NULL,
`SWP_FLAG` VARCHAR(5) DEFAULT NULL,
`SWITCH_FLAG` VARCHAR(5) DEFAULT NULL,
`SETTLEMENT_TYPE` VARCHAR(126) DEFAULT NULL,
`AMC_IND` VARCHAR(126) DEFAULT NULL,
`FACE_VALUE` VARCHAR(126) DEFAULT NULL,
`START_DATE` VARCHAR(126) DEFAULT NULL,
`END_DATE` VARCHAR(126) DEFAULT NULL,
`EXIT_LOAD_FLAG` VARCHAR(5) DEFAULT NULL,
`EXIT_LOAD` VARCHAR(126) DEFAULT NULL,
`LOCK_IN_PERIOD_FLAG` VARCHAR(126) DEFAULT NULL,
`LOCK_IN_PERIOD` VARCHAR(126) DEFAULT NULL,
`CHANNEL_PARTNER_CODE` VARCHAR(126) DEFAULT NULL,
`AMFI_CODE` INT(50) NOT NULL,
`BENCHMARK_CODE` VARCHAR(126) DEFAULT NULL,
`RATING` VARCHAR(126) DEFAULT NULL,
`NFO_DATE` TIMESTAMP DEFAULT '0000-00-00 00:00:00', 
`STATUS` VARCHAR(126) DEFAULT NULL,
`REGISTRAR_TRANSFER_AGENT` VARCHAR(126) DEFAULT NULL,
`RISK` VARCHAR(126) DEFAULT NULL,
`YEAR` VARCHAR(126) DEFAULT NULL,
`RETURN_VALUE` VARCHAR(126) DEFAULT NULL,
`MIN_SIP_AMOUNT` VARCHAR(126) DEFAULT NULL,
`FIELD1` VARCHAR(126) DEFAULT NULL,
`FIELD2` VARCHAR(126) DEFAULT NULL,
PRIMARY KEY (`UNIQUE_SCHEME_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;


CREATE TABLE order_unique_ref (
  ORDER_UNIQUE_REF_ID int(10) NOT NULL,
  ORDER_UNIQUE_REF_NO varchar(50) NOT NULL,      
  FIELD1 int(50) DEFAULT NULL,
  FIELD2 varchar(128) DEFAULT NULL,
  FIELD3 varchar(256) DEFAULT NULL,
  PRIMARY KEY (ORDER_UNIQUE_REF_ID)
)


ALTER TABLE orders
CHANGE address_id BSE_ORDER_ID VARCHAR(50) NULL


INSERT INTO order_unique_ref(ORDER_UNIQUE_REF_ID,ORDER_UNIQUE_REF_NO) VALUES(1,'7777800')

ALTER TABLE orders MODIFY TYPE CHAR(7) DEFAULT NULL


CREATE TABLE scheme_recent_view (
  RECENT_VIEW_ID INT(50) NOT NULL AUTO_INCREMENT,
  SCHEME_ID INT(50) NOT NULL,
  LAST_UPDATED TIMESTAMP NOT NULL,    
  PRIMARY KEY (RECENT_VIEW_ID),
  FOREIGN KEY (SCHEME_ID) REFERENCES scheme (SCHEME_ID)
) 


CREATE TABLE store_conf (
  STORE_CONF_ID int(10) NOT NULL,
  KEYWORD varchar(100) NOT NULL,  
  KEYWORD_VALUE VARCHAR(256) NOT NULL,
  FIELD1 int(50) DEFAULT NULL,
  FIELD2 varchar(128) DEFAULT NULL,
  FIELD3 varchar(256) DEFAULT NULL,
  UNIQUE(KEYWORD),
  PRIMARY KEY (STORE_CONF_ID)
)


INSERT INTO store_conf (STORE_CONF_ID, KEYWORD, KEYWORD_VALUE) VALUES(1,'IMAGE_LOCATION','D:\\go4wealth-image');
INSERT INTO store_conf (STORE_CONF_ID, KEYWORD, KEYWORD_VALUE) VALUES(2,'PDF_LOCATION','\\aof_pdf');
INSERT INTO store_conf (STORE_CONF_ID, KEYWORD, KEYWORD_VALUE) VALUES(3,'TIFF_LOCATION','\\aof_tiff');
INSERT INTO store_conf (STORE_CONF_ID, KEYWORD, KEYWORD_VALUE) VALUES(4,'USERIMAGE_LOCATION','\\userimage');
INSERT INTO store_conf (STORE_CONF_ID, KEYWORD, KEYWORD_VALUE) VALUES(5,'PAN_LOCATION','\\pancard');
INSERT INTO store_conf (STORE_CONF_ID, KEYWORD, KEYWORD_VALUE) VALUES(6,'SIGNATURE_LOCATION','\\signature');
INSERT INTO store_conf (STORE_CONF_ID, KEYWORD, KEYWORD_VALUE) VALUES(7,'ADHARCARD_LOCATION','\\adharcard');
INSERT INTO store_conf (STORE_CONF_ID, KEYWORD, KEYWORD_VALUE) VALUES(8,'DUMMYIMAGE_LOCATION','\\dummyimage');
INSERT INTO store_conf (STORE_CONF_ID, KEYWORD, KEYWORD_VALUE) VALUES(9,'BLOGIMAGE_LOCATION','\\blogImages');
INSERT INTO store_conf (STORE_CONF_ID, KEYWORD, KEYWORD_VALUE) VALUES(10,'TESTIMONIAL_LOCATION','\\testimonialImages');
INSERT INTO store_conf (STORE_CONF_ID, KEYWORD, KEYWORD_VALUE) VALUES(11,'VERIFY_EMAIL_URL','https://localhost:4200/verify-email?token=');


ALTER TABLE SCHEME ADD KEYWORD VARCHAR(256) DEFAULT NULL;



/** Daily_Transaction_Report **/

CREATE TABLE daily_transaction_report_userdata(
  DAILY_TRANSACTION_REPORT_USERDATA_ID INT(50) NOT NULL AUTO_INCREMENT,
  USER_CODE VARCHAR(126) DEFAULT NULL,
  AMC_CODE VARCHAR(126) DEFAULT NULL,
  MICR_NO VARCHAR(126) DEFAULT NULL,
  PROD_CODE VARCHAR(126) DEFAULT NULL,
  FOLIO_NO VARCHAR(126) DEFAULT NULL,
  OLD_FOLIO VARCHAR(126) DEFAULT NULL,
  ALT_FOLIO VARCHAR(126) DEFAULT NULL,
  SCHEME VARCHAR(126) DEFAULT NULL,
  SCHEME_TYPE VARCHAR(126) DEFAULT NULL,
  TARG_SRC_SCHEME VARCHAR(126) DEFAULT NULL,
  INV_NAME VARCHAR(126) DEFAULT NULL,
  INV_IIN VARCHAR(126) DEFAULT NULL,
  LOADS VARCHAR(126) DEFAULT NULL,
  PRIMARY KEY (DAILY_TRANSACTION_REPORT_USERDATA_ID)
  )

CREATE TABLE daily_transaction_report_trxndata(
  DAILY_TRANSACTION_REPORT_TRXNDATA_ID INT(50) NOT NULL AUTO_INCREMENT,
  DAILY_TRANSACTION_REPORT_USERDATA_ID INT(50) DEFAULT NULL,
  TRXN_NO VARCHAR(126) DEFAULT NULL,
  USR_TRX_NO VARCHAR(126) DEFAULT NULL,
  TRXN_TYPE VARCHAR(126) DEFAULT NULL,
  TRXN_MODE VARCHAR(126) DEFAULT NULL,
  TRXN_STAT VARCHAR(126) DEFAULT NULL,
  TRXN_CHARGES VARCHAR(126) DEFAULT NULL,
  SRC_OF_TXN VARCHAR(126) DEFAULT NULL,
  SIP_TRXN_NO VARCHAR(126) DEFAULT NULL,
  TRXN_SUFFIX VARCHAR(126) DEFAULT NULL,
  TRXN_TYPE_FLAG VARCHAR(126) DEFAULT NULL,
  TRXN_NATURE VARCHAR(126) DEFAULT NULL,
  TRXN_SUB_TYPE VARCHAR(126) DEFAULT NULL,
  PRIMARY KEY (DAILY_TRANSACTION_REPORT_TRXNDATA_ID),
  FOREIGN KEY (DAILY_TRANSACTION_REPORT_USERDATA_ID) REFERENCES daily_transaction_report_userdata (DAILY_TRANSACTION_REPORT_USERDATA_ID)
) 


CREATE TABLE daily_transaction_report_extradata(
  DAILY_TRANSACTION_REPORT_EXTRADATA_ID INT(50) NOT NULL AUTO_INCREMENT,
  DAILY_TRANSACTION_REPORT_USERDATA_ID INT(50) DEFAULT NULL,
  BROK_CODE VARCHAR(126) DEFAULT NULL,
  SUB_BROK VARCHAR(126) DEFAULT NULL,
  MULT_BROK VARCHAR(126) DEFAULT NULL,
  BROK_COMM VARCHAR(126) DEFAULT NULL,
  BROK_PERC VARCHAR(126) DEFAULT NULL,
  SUB_BRK_ARN VARCHAR(126) DEFAULT NULL,
  SRC_BRK_CODE VARCHAR(126) DEFAULT NULL,
  APPLICATION_NO VARCHAR(126) DEFAULT NULL,
  SEQ_NO VARCHAR(126) DEFAULT NULL,
  DP_ID VARCHAR(126) DEFAULT NULL,
  PAN VARCHAR(126) DEFAULT NULL,
  AC_NO VARCHAR(126) DEFAULT NULL,
  BANK_NAME VARCHAR(126) DEFAULT NULL,
  TAX VARCHAR(126) DEFAULT NULL,
  TOTAL_TAX VARCHAR(126) DEFAULT NULL,
  TAX_STATUS VARCHAR(126) DEFAULT NULL,
  LOCATION VARCHAR(126) DEFAULT NULL,
  REMARKS VARCHAR(126) DEFAULT NULL,
  UNITS VARCHAR(126) DEFAULT NULL,
  AMOUNT VARCHAR(126) DEFAULT NULL,
  ELIGIB_AMT VARCHAR(126) DEFAULT NULL,
  IGST_AMOUNT VARCHAR(126) DEFAULT NULL,
  CGST_AMOUNT VARCHAR(126) DEFAULT NULL,
  SGST_AMOUNT VARCHAR(126) DEFAULT NULL,
  PUR_PRICE VARCHAR(126) DEFAULT NULL,
  SCAN_REF_NO VARCHAR(126) DEFAULT NULL,
  EUIN VARCHAR(126) DEFAULT NULL,
  EUIN_VALID VARCHAR(126) DEFAULT NULL,
  EUIN_OPTED VARCHAR(126) DEFAULT NULL,
  EXCHANGE_FLAG VARCHAR(126) DEFAULT NULL,
  EXCH_DC_FLAG VARCHAR(126) DEFAULT NULL,
  SW_FLAG VARCHAR(126) DEFAULT NULL,
  REINVEST_FLAG VARCHAR(126) DEFAULT NULL,
  CA_INITIATED_DATE VARCHAR(126) DEFAULT NULL,
  TRAD_DATE VARCHAR(126) DEFAULT NULL,
  POST_DATE VARCHAR(126) DEFAULT NULL,
  REP_DATE VARCHAR(126) DEFAULT NULL,
  SYS_REGN_DATE VARCHAR(126) DEFAULT NULL,
  GST_STATE_CODE VARCHAR(126) DEFAULT NULL,
  REVERSAL_CODE VARCHAR(126) DEFAULT NULL,
  TICOB_TRNO VARCHAR(126) DEFAULT NULL,
  TICOB_TRTYPE VARCHAR(126) DEFAULT NULL,
  TICOB_POSTED_DATE VARCHAR(126) DEFAULT NULL,
  TER_LOCATION VARCHAR(126) DEFAULT NULL,
  TE_15H VARCHAR(126) DEFAULT NULL,
  TIME1 VARCHAR(126) DEFAULT NULL,
  STT VARCHAR(126) DEFAULT NULL,
  PRIMARY KEY (DAILY_TRANSACTION_REPORT_EXTRADATA_ID),
  FOREIGN KEY (DAILY_TRANSACTION_REPORT_USERDATA_ID) REFERENCES daily_transaction_report_userdata (DAILY_TRANSACTION_REPORT_USERDATA_ID)
)


CREATE TABLE bank_codes(
bank_code_id INT(50) NOT NULL AUTO_INCREMENT,
bank_mode VARCHAR(50) NOT NULL,
bank_name VARCHAR(125) NOT NULL,
bank_code VARCHAR(50) NOT NULL,
FIELD1 INT(50) DEFAULT NULL,
FIELD2 VARCHAR(128) DEFAULT NULL,
PRIMARY KEY (bank_code_id),
UNIQUE KEY bank_name (bank_name)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(1,'NODAL','HDFC BANK','HDF');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(2,'DIRECT','Axis Bank','UTI');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(3,'DIRECT','ICICI Bank - Retail Net Banking','ICI');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(4,'DIRECT','IDBI Bank - Retail Net Banking','IDB');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(5,'DIRECT','Kotak Bank','162');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(6,'DIRECT','State Bank of India','SBI');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(7,'NODAL','Allahabad Bank - Retail Net Banking','ALB');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(8,'NODAL','Andhra Bank','ADB');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(9,'NODAL','Bank of Bahrain and Kuwait','BBK');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(10,'NODAL','Bank of Baroda - Corporate Banking','BBC');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(11,'NODAL','Bank of Baroda - Retail Net Banking','BBR');

INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(12,'NODAL','Bank of Maharashtra','BOM');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(13,'NODAL','Bharatiya Mahila Bank','BMN');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(14,'NODAL','Canara Bank','CNB');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(15,'NODAL','Catholic Syrian Bank','CSB');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(16,'NODAL','Central Bank of India','CBI');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(17,'NODAL','Corporation Bank','CRP');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(18,'NODAL','Cosmos Bank','COB');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(19,'NODAL','Dena Bank','DEN');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(20,'NODAL','Deutsche Bank','DBK');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(21,'NODAL','Development Credit Bank - Corporate','DC2');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(22,'NODAL','Development Credit Bank - Retail','DCB');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(23,'NODAL','Dhanlakshmi Bank','DLB');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(24,'NODAL','Federal Bank','FBK');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(25,'NODAL','Indian Bank','INB');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(26,'NODAL','Indian Overseas Bank','IOB');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(27,'NODAL','IndusInd Bank','IDS');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(28,'NODAL','ING Vysya Bank - Retail Net Banking','ING');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(29,'NODAL','Jammu & Kashmir Bank','JKB');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(30,'NODAL','Janata Sahakari Bank','JSB');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(31,'NODAL','Karnataka Bank Ltd','KBL');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(32,'NODAL','Karur Vysya Bank','KVB');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(33,'NODAL','Laxmi Vilas Bank - Corporate Net Banking','LVC');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(34,'NODAL','Laxmi Vilas Bank - Retail Net Banking','LVR');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(35,'NODAL','NKGSB BANK','NKB');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(36,'NODAL','Oriental Bank of Commerce','OBC');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(37,'NODAL','Punjab & Maharastra Coop Bank','PMC');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(38,'NODAL','Punjab & Sind Bank','PSB');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(39,'NODAL','Punjab National Bank - Corporate Banking','CPN');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(40,'NODAL','Punjab National Bank - Retail Net Banking','PNB');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(41,'NODAL','Ratnakar Bank - Retail Net Banking','RTN');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(42,'NODAL','RBS (The Royal Bank of Scotland)','RBS');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(43,'NODAL','Saraswat Bank','SWB');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(44,'NODAL','Shamrao Vitthal Co-operative Bank - Retail Net Banking','SVC');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(45,'NODAL','South Indian Bank','SIB');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(46,'NODAL','Standard Chartered Bank','SCB');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(47,'NODAL','Syndicate Bank','SYD');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(48,'NODAL','Tamilnad Mercantile Bank Ltd.','TMB');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(49,'NODAL','Tamilnadu State Coop Bank','TNC');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(50,'NODAL','TJSB Bank','TJB');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(51,'NODAL','UCO Bank','UCO');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(52,'NODAL','Union Bank of India','UBI');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(53,'NODAL','United Bank of India','UNI');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(54,'NODAL','Vijaya Bank','VJB');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(55,'DIRECT','Yes Bank Ltd','YBK');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(56,'NODAL','STATE BANK OF MYSORE','SBM');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(57,'DIRECT','CITY UNION BANK LIMITED','CIU');
INSERT INTO bank_codes (bank_code_id, bank_mode, bank_name,bank_code) VALUES(58,'NODAL','Ratnakar Bank - Retail Net Banking','RBL');


/** New tables **/
CREATE TABLE address_city(
ADDRESS_CITY_ID INT(50) NOT NULL AUTO_INCREMENT,
ADDRESS_CITYNAME VARCHAR(50) NOT NULL,
PRIMARY KEY (ADDRESS_CITY_ID)
) ENGINE=INNODB DEFAULT CHARSET=utf8;


CREATE TABLE address_state(
ADDRESS_STATE_ID INT(50) NOT NULL AUTO_INCREMENT,
ADDRESS_STATENAME VARCHAR(50) NOT NULL,
PRIMARY KEY (ADDRESS_STATE_ID)
) ENGINE=INNODB DEFAULT CHARSET=utf8;


INSERT INTO `address_state` (`ADDRESS_STATE_ID`, `ADDRESS_STATENAME`) VALUES
(1, 'JAMMU AND KASHMIR'),
(2, 'BIHAR'),
(3, 'SIKKIM'),
(4, 'ARUNACHAL PRADESH'),
(5, 'NAGALAND'),
(6, 'MANIPUR'),
(7, 'MIZORAM'),
(8, 'TRIPURA'),
(9, 'MEGHALAYA'),
(10, 'ASSAM'),
(11, 'WEST BENGAL'),
(12, 'HIMACHAL PRADESH'),
(13, 'JHARKHAND'),
(14, 'ODISHA'),
(15, 'CHHATTISGARH'),
(16, 'MADHYA PRADESH'),
(17, 'GUJARAT'),
(18, 'DAMAN AND DIU'),
(19, 'DADRA AND NAGAR HAVELI'),
(20, 'MAHARASHTRA'),
(21, 'ANDHRA PRADESH'),
(22, 'KARNATAKA'),
(23, 'PUNJAB'),
(24, 'GOA'),
(25, 'LAKSHADWEEP'),
(26, 'KERALA'),
(27, 'TAMIL NADU'),
(28, 'PUDUCHERRY'),
(29, 'ANDAMAN AND NICOBAR ISLANDS'),
(30, 'TELANGANA'),
(31, 'CHANDIGARH'),
(32, 'UTTARAKHAND'),
(33, 'HARYANA'),
(34, 'DELHI'),
(35,  'RAJASTHAN'),
(36, 'UTTAR PRADESH');

/*** **/


/** New Table **/
CREATE TABLE user_watchlist(
	USER_WATCHLIST_ID INT(50) NOT NULL AUTO_INCREMENT,
	USER_ID INT(50) NOT NULL,
	SCHEME_CODE VARCHAR(126) DEFAULT NULL,
	PURCHASED_STATUS VARCHAR(50) DEFAULT NULL,
	REMOVED_STATUS VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY(USER_WATCHLIST_ID),
	FOREIGN KEY (USER_ID) REFERENCES `user` (USER_ID)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

/*Payment Tables*/
CREATE TABLE ppcpaytran (
  TRANSACTION_ID BIGINT(20) NOT NULL,
  TRANSACTIONTYPE INT(6) NOT NULL,
  PROCESSEDAMOUNT DECIMAL(20,5) NOT NULL DEFAULT '0.00000',
  STATE INT(6) NOT NULL,
  TIMECREATED TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  TIMEUPDATED TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  RESPONSECODE VARCHAR(25) DEFAULT NULL,
  REASONCODE VARCHAR(25) DEFAULT NULL,
  REFERENCENUMBER VARCHAR(512) DEFAULT NULL,
  TRACKINGID VARCHAR(512) DEFAULT NULL,
  FIELD1 VARCHAR(128) DEFAULT NULL,
  FIELD2 VARCHAR(254) DEFAULT NULL,
  FIELD3 INT(11) DEFAULT NULL,
  PRIMARY KEY (TRANSACTION_ID),
  FOREIGN KEY (TRANSACTION_ID) REFERENCES ppcpayinst (TRANSACTION_ID)
)



CREATE TABLE ppcpayinst (
  TRANSACTION_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  ORDERS_ID INT(10) NOT NULL,
  AMOUNT DECIMAL(20,5) NOT NULL,
  APPROVINGAMOUNT DECIMAL(20,5) NOT NULL DEFAULT '0.00000',
  APPROVEDAMOUNT DECIMAL(20,5) NOT NULL DEFAULT '0.00000',
  CREDITINGAMOUNT DECIMAL(20,5) NOT NULL DEFAULT '0.00000',
  CREDITEDAMOUNT DECIMAL(20,5) NOT NULL DEFAULT '0.00000',  
  TIMECREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  TIMEUPDATED TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  CURRENCY VARCHAR(50) NOT NULL,
  STATE VARCHAR(6) NOT NULL DEFAULT '0',
  MARKFORDELETE INT(5) NOT NULL DEFAULT '0',
  FIELD1 VARCHAR(128) DEFAULT NULL,
  FIELD2 VARCHAR(254) DEFAULT NULL,
  FIELD3 INT(11) DEFAULT NULL,
  PRIMARY KEY (TRANSACTION_ID),
  FOREIGN KEY (ORDERS_ID) REFERENCES orders (ORDERS_ID)
)

CREATE TABLE `redumption_management` (
  `REDUMPTION_MANAGEMENT_ID` INT(50) NOT NULL AUTO_INCREMENT,
  `FOLIO_NUMBER` INT(126) DEFAULT NULL,
  `BSE_ORDER_ID` VARCHAR(126) DEFAULT NULL,
  `REDUMPTION_AMOUNT` DECIMAL(20,5) DEFAULT NULL,
  `AVAILABLE_AMOUNT` DECIMAL(20,5) DEFAULT NULL,
  `REDUMPTION_DATE` VARCHAR(126) DEFAULT NULL,
  `REDUMPTION_UNIT` DECIMAL(20,5) DEFAULT NULL,
  `STATUS` VARCHAR(126) DEFAULT NULL,
  `FIELD1` VARCHAR(126) DEFAULT NULL,
  `FIELD2` VARCHAR(126) DEFAULT NULL,
  `FIELD3` VARCHAR(126) DEFAULT NULL,
  `FIELD4` INT(126) DEFAULT NULL,
  `FIELD5` DECIMAL(20,5) DEFAULT NULL,
  PRIMARY KEY (`REDUMPTION_MANAGEMENT_ID`)
  ) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8