CREATE TABLE `CITIES` (
  `CITY_ID` INT(50) NOT NULL AUTO_INCREMENT,
  `CITY_NAME` VARCHAR(126) DEFAULT NULL,
  `CITY_CODE` VARCHAR(10) DEFAULT NULL,
  PRIMARY KEY (`CITY_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

/*CREATE TABLE `CITY_SLABS` (
 `CITY_SLAB_ID` INT(50) NOT NULL AUTO_INCREMENT,
 `CITY_CODE` VARCHAR(126) DEFAULT NULL,
 `CITY_SLAB_CODE` VARCHAR(10) DEFAULT NULL,
 PRIMARY KEY (`CITY_SLAB_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;*/

CREATE TABLE `INCOME_SLABS` (
  `INCOME_SLAB_ID` INT(50) NOT NULL AUTO_INCREMENT,
  `INCOME_SLAB_NAME` VARCHAR(126) DEFAULT NULL,
  `INCOME_FROM` INT(3) DEFAULT NULL,
  `INCOME_TO` INT(3) DEFAULT NULL,
  PRIMARY KEY (`INCOME_SLAB_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `AGE_SLABS` (
  `AGE_SLAB_ID` INT(50) NOT NULL AUTO_INCREMENT,
  `AGE_SLAB_NAME` VARCHAR(126) DEFAULT NULL,
  `AGE_FROM` INT(3) DEFAULT NULL,
  `AGE_TO` INT(3) DEFAULT NULL,
  PRIMARY KEY (`AGE_SLAB_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `MARITAL_STATUS` (
  `MARITAL_STATUS_ID` INT(50) NOT NULL AUTO_INCREMENT,
  `MARITAL_STATUS_NAME` VARCHAR(126) DEFAULT NULL,
  `MARITAL_STATUS_VALUE` VARCHAR(3) DEFAULT NULL,
  PRIMARY KEY (`MARITAL_STATUS_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `KIDS_SLABS` (
  `KIDS_SLAB_ID` INT(50) NOT NULL AUTO_INCREMENT,
  `KIDS_SLAB_NAME` VARCHAR(126) DEFAULT NULL,
  `KIDS_SLAB_VALUE` INT(3) DEFAULT NULL,
  PRIMARY KEY (`KIDS_SLAB_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

ALTER TABLE CITIES ADD COLUMN MF_CLASSIFICATION VARCHAR(50) DEFAULT NULL;
ALTER TABLE INCOME_SLABS ADD COLUMN INCOME_SLAB_CODE VARCHAR(5) DEFAULT NULL;
ALTER TABLE AGE_SLABS ADD COLUMN AGE_SLAB_CODE VARCHAR(5) DEFAULT NULL;
ALTER TABLE KIDS_SLABS ADD COLUMN KIDS_SLAB_CODE VARCHAR(5) DEFAULT NULL;
ALTER TABLE MARITAL_STATUS ADD COLUMN MARITAL_STATUS_CODE VARCHAR(5) DEFAULT NULL;


CREATE TABLE `SIP_PROFILE_COMB` (
  `SIP_PROFILE_COMB_ID` INT(50) NOT NULL AUTO_INCREMENT,
  `CITY_CODE` VARCHAR(5) DEFAULT NULL,
  `MARITAL_STATUS_CODE` VARCHAR(5) DEFAULT NULL,
  `KIDS_SLAB_CODE` VARCHAR(5) DEFAULT NULL,
  `INCOME_SLAB_CODE` VARCHAR(5) DEFAULT NULL,
  `AGE_SLAB_CODE` VARCHAR(5) DEFAULT NULL,
  `KIDS_CURR_AGE` VARCHAR(126) DEFAULT NULL,
  `AGE_TO_RETIRE` INT(3) DEFAULT NULL,
  `CUSTOMER_CODE` VARCHAR(30) DEFAULT NULL,
  PRIMARY KEY (`SIP_PROFILE_COMB_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;


CREATE TABLE `GOAL_BUCKET` (
  `GOAL_BUCKET_ID` INT(50) NOT NULL AUTO_INCREMENT,
  `GOAL_BUCKET_NAME` VARCHAR(126) DEFAULT NULL,
  `GOAL_BUCKET_CODE` VARCHAR(5) DEFAULT NULL,
  PRIMARY KEY (`GOAL_BUCKET_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `GOALS` (
  `GOAL_ID` INT(50) NOT NULL AUTO_INCREMENT,
  `GOAL_NAME` VARCHAR(126) DEFAULT NULL,
  `GOAL_BUCKET_ID` INT(50) NOT NULL,
  `SHOW_TO_PROFILE_TYPE` VARCHAR(50) DEFAULT NULL,
  `COST_OF_GOAL` DECIMAL(10,5) NOT NULL,
   PRIMARY KEY (`GOAL_ID`),
   FOREIGN KEY (`GOAL_BUCKET_ID`) REFERENCES GOAL_BUCKET(`GOAL_BUCKET_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

ALTER TABLE goals MODIFY COLUMN COST_OF_GOAL DECIMAL(20,5) NOT NULL;

CREATE TABLE GOAL_COMB_REL(
  `GOAL_ID` INT(50) NOT NULL ,
  `SIP_PROFILE_COMB_ID` INT(50) NOT NULL,
  PRIMARY KEY(`GOAL_ID`,`SIP_PROFILE_COMB_ID`),
  FOREIGN KEY (`GOAL_ID`) REFERENCES GOALS(`GOAL_ID`),
  FOREIGN KEY (`SIP_PROFILE_COMB_ID`) REFERENCES SIP_PROFILE_COMB(`SIP_PROFILE_COMB_ID`)
 ) ENGINE=INNODB DEFAULT CHARSET=utf8;

ALTER TABLE goal_comb_rel ADD  COLUMN cutomor_code VARCHAR(30) NOT NULL;

CREATE TABLE `GUEST_USER` (
  `GUEST_USER_ID` INT(50) NOT NULL AUTO_INCREMENT,
  `CREATED_TIMESTAMP` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `UPDATED_DATE_TIME` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  `FIELD1` INT(50) DEFAULT NULL,
  `FIELD2` VARCHAR(128) DEFAULT NULL,
  `FIELD4` VARCHAR(128) DEFAULT NULL,
  PRIMARY KEY (`GUEST_USER_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;


CREATE TABLE SIP_USER_HISTORY(
  `SIP_USER_HISTORY_ID` INT(50) NOT NULL AUTO_INCREMENT,
  `GUEST_USER_ID` INT(50) NOT NULL,
  `CITY_NAME` VARCHAR(126) DEFAULT NULL,
  `INCOME_SLAB_NAME` VARCHAR(126) DEFAULT NULL,
  `AGE` INT(3) DEFAULT NULL,
  `MARITAL_STATUS_VALUE` VARCHAR(3) DEFAULT NULL,
  `KIDS_SLAB_VALUE` INT(3) DEFAULT NULL,
  `CREATED_TIMESTAMP` TIMESTAMP DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY(`SIP_USER_HISTORY_ID`),
  FOREIGN KEY (`GUEST_USER_ID`) REFERENCES GUEST_USER(`GUEST_USER_ID`)
 ) ENGINE=INNODB DEFAULT CHARSET=utf8;
 
  ALTER TABLE SIP_USER_HISTORY MODIFY COLUMN MARITAL_STATUS_VALUE VARCHAR(126) DEFAULT NULL;

  
  ALTER TABLE goals ADD COLUMN GOAL_ICON VARCHAR(126) DEFAULT NULL;
