CREATE TABLE `GOALS_ORDER` (
  `GOALS_ORDER_ID` INT(50) NOT NULL AUTO_INCREMENT,
  `USER_ID` INT(50) NOT NULL,
  `DESCRIPTION` VARCHAR(128) DEFAULT NULL,
  `RISK_PROFILE` VARCHAR(126) DEFAULT NULL,
  `FUND_TYPE` VARCHAR(126) DEFAULT NULL,
  `INFLATION` DECIMAL(10,5) NOT NULL,
  `ROI` DECIMAL(10,5) NOT NULL,
  `TOTAL_MONTHLY_SAVING` DECIMAL(20,5) NOT NULL,
  `TOTAL_LUMPSUM_SAVING` DECIMAL(20,5) NOT NULL,
  `TOTAL_MONTHLY_ADJUSTMENT` DECIMAL(20,5) NOT NULL,
  `TOTAL_LUMPSUM_ADJUSMENT` DECIMAL(20,5) NOT NULL,
  `TOTAL_FUTURE_VALUE` DECIMAL(20,5) NOT NULL,
  `TOTAL_ASSET_VALUE` DECIMAL(20,5) NOT NULL,
  `CREATED_TIMESTAMP` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `UPDATED_DATE_TIME` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  `FIELD1` INT(50) DEFAULT NULL,
  `FIELD2` VARCHAR(128) DEFAULT NULL,
  `FIELD4` VARCHAR(128) DEFAULT NULL,
   PRIMARY KEY (`GOALS_ORDER_ID`),
   FOREIGN KEY (`USER_ID`) REFERENCES `user` (`USER_ID`)
   ) ENGINE=INNODB DEFAULT CHARSET=utf8;

 
 CREATE TABLE GOAL_ORDER_ITEMS(
  `GOAL_ORDER_ITEM_ID` INT(50) NOT NULL AUTO_INCREMENT,
  `GOAL_ID` INT(50) NOT NULL ,
  `GOALS_ORDER_ID` INT(50) NOT NULL,
  `USER_ID` INT(50) NOT NULL,
  `DESCRIPTION` VARCHAR(254) DEFAULT NULL,
  `FUTURE_VALUE` DECIMAL(20,5) NOT NULL,
  `DURATION` INT(50) DEFAULT NULL ,
  `GOAL_DATE` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `MONTHLY_SAVING` DECIMAL(20,5) NOT NULL,
  `LUMPSUM_SAVING` DECIMAL(20,5) NOT NULL,
  `CREATED_TIMESTAMP` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `UPDATED_DATE_TIME` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  `FIELD1` INT(50) DEFAULT NULL,
  `FIELD2` VARCHAR(128) DEFAULT NULL,
  `FIELD4` VARCHAR(128) DEFAULT NULL,
  PRIMARY KEY(`GOAL_ORDER_ITEM_ID`),
  FOREIGN KEY (`GOALS_ORDER_ID`) REFERENCES GOALS_ORDER(`GOALS_ORDER_ID`),
  FOREIGN KEY (`GOAL_ID`) REFERENCES GOALS(`GOAL_ID`),
  FOREIGN KEY (`USER_ID`) REFERENCES `user` (`USER_ID`)
 ) ENGINE=INNODB DEFAULT CHARSET=utf8;
 
 
 CREATE TABLE USER_ASSET_ITEMS(
  `GOALS_ORDER_ID` INT(50) NOT NULL,
  `ASSET_CLASS_ID` INT(50) NOT NULL,
  `ASSET_VALUE` DECIMAL(20,5) NOT NULL,
  PRIMARY KEY(`GOALS_ORDER_ID`,`ASSET_CLASS_ID`),
  FOREIGN KEY (`GOALS_ORDER_ID`) REFERENCES GOALS_ORDER(`GOALS_ORDER_ID`),
  FOREIGN KEY (`ASSET_CLASS_ID`) REFERENCES ASSET_CLASS(`ASSET_CLASS_ID`)
 ) ENGINE=INNODB DEFAULT CHARSET=utf8;