DROP TABLE goal_comb_rel;
DROP TABLE sip_profile_comb;
DROP TABLE sip_user_history;
DROP TABLE guest_user;
DROP TABLE transfer_in;
DROP TABLE transfer_in_details;
DROP TABLE transfer_in_user_details;

DROP TABLE scheme_sub_category;
DROP TABLE scheme_code_mapping;
DROP TABLE unique_scheme;

DROP TABLE scheme_category;

DROP TABLE daily_transaction_report_trxndata;
DROP TABLE daily_transaction_report_redumption_data;
DROP TABLE daily_transaction_report_extradata;
DROP TABLE daily_transaction_report_userdata;


ALTER TABLE user_enquiry ADD COLUMN `STATUS` VARCHAR(50) DEFAULT 'Not Reply';

ALTER TABLE ORDERS ADD COLUMN TRANFER_IN_ID INT(50) DEFAULT 0;

UPDATE scheme SET AMC_CODE='DSP_MF'  WHERE AMC_CODE='DSPBLACKROCK';


CREATE TABLE `consolidated_portfollio` (
  `Consolidated_Portfollio_Id` INT(50) NOT NULL AUTO_INCREMENT,
  `Order_Id` INT(50) DEFAULT NULL,
  `Current_Amount` DECIMAL(20,5) DEFAULT '0.00000',
  `Scheme_Code` VARCHAR(126) DEFAULT NULL,
  `User_Id` INT(50) DEFAULT NULL,
  `Client_Code` VARCHAR(126) DEFAULT NULL,
  `STATUS` VARCHAR(126) DEFAULT NULL,
  `STATUS_CODE` INT(50) DEFAULT '0',
  `Last_Nav_Updated_date` VARCHAR(126) DEFAULT NULL,
  `FOLIO_NO` VARCHAR(126) DEFAULT NULL,
  `SIP_Regn_No` BIGINT(50) DEFAULT NULL,
  `INVESTED_AMOUNT` DECIMAL(20,3) DEFAULT NULL,
  `ALLOTED_UNIT` DECIMAL(20,3) DEFAULT NULL,
  `Last_Redumption_Updated_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `FIELD1` VARCHAR(126) DEFAULT NULL,
  `FIELD2` VARCHAR(126) DEFAULT NULL,
  `FIELD3` INT(50) DEFAULT NULL,
  `FIELD4` DECIMAL(20,3) DEFAULT NULL,
  PRIMARY KEY (`Consolidated_Portfollio_Id`)
) ENGINE=INNODB AUTO_INCREMENT=151 DEFAULT CHARSET=utf8


ALTER TABLE redumption_management ADD COLUMN SCHEME_CODE VARCHAR(50) DEFAULT NULL;
ALTER TABLE redumption_management CHANGE FIELD3 REDEEM_ORDER_ID VARCHAR(50) DEFAULT NULL;


CREATE TABLE `transfer_in`(
`TRANSFER_IN_ID` INT(50) NOT NULL AUTO_INCREMENT,
`UNIQUE_ID` INT(50) DEFAULT NULL,
`FOLIO_NUMBER` VARCHAR(126) DEFAULT NULL,
`SCHEME_CODE` VARCHAR(512) DEFAULT NULL,
`INVESTER_NAME` VARCHAR(128) DEFAULT NULL,
`STARTED_ON` VARCHAR(126) DEFAULT NULL,
`PRICE` DECIMAL(20,5) NOT NULL DEFAULT '0.00000',
`UNIT` DECIMAL(20,5) NOT NULL DEFAULT '0.00000',
`AVAILABLE_UNIT` DECIMAL(20,5) DEFAULT '0.00000',
`AMOUNT` DECIMAL(20,5) NOT NULL DEFAULT '0.00000',
`PAN` VARCHAR(128) DEFAULT NULL,
`RTA_AGENT` VARCHAR(50) DEFAULT NULL,
`TRANSACTION_TYPE` VARCHAR(50) DEFAULT NULL,
`SIP_REG_NO` VARCHAR(126) DEFAULT NULL,
`INVESTMENT_TYPE` VARCHAR(50) DEFAULT NULL,
`TIME_CREATED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
`LAST_UPDATED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
`STATUS` VARCHAR(50) DEFAULT NULL,
`STATUS_CODE` INT(5) DEFAULT '0',
`FIELD1` DECIMAL(20,5) NOT NULL DEFAULT '0.00000',
`USER_ID` INT(50) NOT NULL DEFAULT '0',
`FIELD3` VARCHAR(50) DEFAULT NULL,
`FIELD4` VARCHAR(128) DEFAULT NULL,
PRIMARY KEY(`TRANSFER_IN_ID`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

ALTER TABLE consolidated_portfollio CHANGE FIELD3 TRANFER_IN_ID INT(50);