CREATE DATABASE IF NOT EXISTS `go4wealthdb` ;

USE `go4wealthdb`;

CREATE TABLE `user` (
  `USER_ID` int(50) NOT NULL AUTO_INCREMENT,
  `username` varchar(126) NOT NULL,
  `PASSWORD` varchar(126) NOT NULL,
  `MOBILE_NUMBER` varchar(50) DEFAULT NULL,
  `REGISTER_TYPE` varchar(126) NOT NULL,
  `EMAIL` varchar(126) DEFAULT NULL,
  `FIRST_NAME` varchar(126) DEFAULT NULL,
  `LAST_NAME` varchar(126) DEFAULT NULL,
  `GENDER` varchar(50) DEFAULT NULL,
  `DATE_OF_BIRTH` date DEFAULT NULL,
  `CREATED_TIMESTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_DATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `FIELD1` int(50) DEFAULT NULL,
  `FIELD2` varchar(128) DEFAULT NULL,
  `FIELD3` varchar(512) DEFAULT NULL,
  `FIELD4` varchar(128) DEFAULT NULL,
  `STATUS` varchar(10) DEFAULT NULL,
  `EMAIL_VERIFIED` int(5) NOT NULL,
  PRIMARY KEY (`USER_ID`),
  UNIQUE KEY `username` (`username`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;


CREATE TABLE `authority` (
  `AUTHORITY_ID` INT(50) NOT NULL AUTO_INCREMENT,
  `AUTHORITY_TYPE` VARCHAR(126) DEFAULT NULL,
  PRIMARY KEY (`AUTHORITY_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `user_authority` (
  `USER_ID` INT(50) NOT NULL,
  `AUTHORITY_ID` INT(50) NOT NULL,
  PRIMARY KEY (`USER_ID`,`AUTHORITY_ID`),
  FOREIGN KEY (`USER_ID`) REFERENCES `user` (`USER_ID`),
  FOREIGN KEY (`AUTHORITY_ID`) REFERENCES `authority` (`AUTHORITY_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `user_profile` (
  `USER_PROFILE_ID` INT(50) NOT NULL,
  `AADHAAR_NUMBER` VARCHAR(128) DEFAULT NULL,
  `PAN_NUMBER` VARCHAR(128) DEFAULT NULL,
  `CREATED_TIMESTAMP` TIMESTAMP DEFAULT '0000-00-00 00:00:00',
  `UPDATED_DATE_TIME` TIMESTAMP DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  `FIELD1` INT(50) DEFAULT NULL,
  `FIELD2` VARCHAR(128) DEFAULT NULL,
  PRIMARY KEY (`USER_PROFILE_ID`),
  FOREIGN KEY (`USER_PROFILE_ID`) REFERENCES `user` (`USER_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `agent_profile` (
  `AGENT_PROFILE_ID` INT(50) NOT NULL,
  `ARN_CODE` VARCHAR(128) DEFAULT NULL,
  `AADHAAR_NUMBER` VARCHAR(128) DEFAULT NULL,
  `PAN_NUMBER` VARCHAR(128) DEFAULT NULL,
  `CREATED_TIMESTAMP` TIMESTAMP DEFAULT '0000-00-00 00:00:00',
  `UPDATED_DATE_TIME` TIMESTAMP DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  `FIELD1` INT(50) DEFAULT NULL,
  `FIELD2` VARCHAR(128) DEFAULT NULL,
   PRIMARY KEY (`AGENT_PROFILE_ID`),
   FOREIGN KEY (`AGENT_PROFILE_ID`) REFERENCES `user` (`USER_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `role` (
  `ROLE_ID` INT(50) NOT NULL AUTO_INCREMENT,
  `ROLE_NAME` VARCHAR(126) DEFAULT NULL,
  PRIMARY KEY (`ROLE_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;



CREATE TABLE `user_role` (
  `ROLE_ID` INT(50) NOT NULL,
  `USER_ID` INT(50) NOT NULL UNIQUE,
  PRIMARY KEY (`ROLE_ID`,`USER_ID`),
  FOREIGN KEY (`USER_ID`) REFERENCES `user` (`USER_ID`),
  FOREIGN KEY (`ROLE_ID`) REFERENCES `role` (`ROLE_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;




CREATE TABLE `address` (
  `ADDRESS_ID` INT(50) NOT NULL AUTO_INCREMENT,
  `USER_ID` INT(50) NOT NULL,
  `COUNTRY` VARCHAR(126) DEFAULT NULL,
  `STATE` VARCHAR(126) DEFAULT NULL,
  `CITY` VARCHAR(126) DEFAULT NULL,
  `PINCODE` VARCHAR(126) DEFAULT NULL,
  `REGISTER_DATE` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  `FIELD1` INT(50) DEFAULT NULL,
  `FIELD2` VARCHAR(128) DEFAULT NULL,
  PRIMARY KEY (`ADDRESS_ID`),
  KEY `USER_ID` (`USER_ID`),
  FOREIGN KEY (`USER_ID`) REFERENCES `user` (`USER_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;


CREATE TABLE `commission` (
  `COMMISSION_ID` INT(50) NOT NULL AUTO_INCREMENT,
  `USER_ID` INT(50) NOT NULL,
  `COMMISSION_PRICE` BIGINT(50) NOT NULL,
  PRIMARY KEY (`COMMISSION_ID`),
  FOREIGN KEY (`USER_ID`) REFERENCES `user` (`USER_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;


CREATE TABLE `otp` (
   `OTP_ID` INT(50) NOT NULL AUTO_INCREMENT,
   `OTP` VARCHAR(126) DEFAULT NULL,
   `SENT_TIME` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
   `MOBILE_NUMBER` VARCHAR(10) DEFAULT NULL,
   PRIMARY KEY(`OTP_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;


CREATE TABLE `user_owner_scheme_rel` ( 
	`USER_ID` INT(50) NOT NULL , 
	`OWNER_ID` INT(50) NOT NULL, 
	`SCHEME` VARCHAR(126) DEFAULT NULL, 
	`FOLIO_NO` VARCHAR(126) DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8;

ALTER TABLE `go4wealthdb`.`user` CHANGE `MOBILE_NUMBER` `MOBILE_NUMBER` VARCHAR(15) NULL;
ALTER TABLE USER ADD EMAIL_VERIFIED INT(5) NOT NULL;

INSERT INTO `store_conf` (`STORE_CONF_ID`,`KEYWORD`,`KEYWORD_VALUE`) VALUES (18,'SMS_AUTH_KEY','232959AXeMBsNRmuR55b7bf5e4');
INSERT INTO `store_conf` (`STORE_CONF_ID`,`KEYWORD`,`KEYWORD_VALUE`) VALUES (19,'SENDGRID_API_KEY','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');
INSERT INTO `store_conf` (`STORE_CONF_ID`,`KEYWORD`,`KEYWORD_VALUE`) VALUES (20,'SENDGRID_SENDER_EMAIL','gaurav.pandey@moptra.com');