package com.moptra.go4wealth.prs.navapi.icra.authentication;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2018-09-26T14:13:35.500+05:30
 * Generated source version: 2.7.5
 * 
 */
@WebServiceClient(name = "AuthService", 
                  wsdlLocation = "classpath:wsdl/AuthService.xml",
                  targetNamespace = "http://ICRA.SOAP.DataProdiver/Authentication") 
public class AuthService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ICRA.SOAP.DataProdiver/Authentication", "AuthService");
    public final static QName BasicHttpBindingIAuthenticationService = new QName("http://ICRA.SOAP.DataProdiver/Authentication", "BasicHttpBinding_IAuthenticationService");
    static {
        URL url = AuthService.class.getClassLoader().getResource("wsdl/AuthService.xml");
        if (url == null) {
            java.util.logging.Logger.getLogger(AuthService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/AuthService.xml");
        }       
        WSDL_LOCATION = url;   
    }

    public AuthService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AuthService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuthService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AuthService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AuthService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AuthService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IAuthenticationService
     */
    @WebEndpoint(name = "BasicHttpBinding_IAuthenticationService")
    public IAuthenticationService getBasicHttpBindingIAuthenticationService() {
        return super.getPort(BasicHttpBindingIAuthenticationService, IAuthenticationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IAuthenticationService
     */
    @WebEndpoint(name = "BasicHttpBinding_IAuthenticationService")
    public IAuthenticationService getBasicHttpBindingIAuthenticationService(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIAuthenticationService, IAuthenticationService.class, features);
    }

}
