package com.moptra.go4wealth.prs.navapi.icra.authentication;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2018-09-26T14:13:35.494+05:30
 * Generated source version: 2.7.5
 * 
 */
@WebService(targetNamespace = "http://ICRA.SOAP.DataProdiver/Authentication", name = "IAuthenticationService")
@XmlSeeAlso({com.moptra.go4wealth.prs.navapi.serialization.ObjectFactory.class, ObjectFactory.class, com.moptra.go4wealth.prs.navapi.icra.datacontracts.ObjectFactory.class})
public interface IAuthenticationService {

    @WebMethod(operationName = "ChangePassword", action = "http://ICRA.SOAP.DataProdiver/Authentication/ChangePassword")
    @Action(input = "http://ICRA.SOAP.DataProdiver/Authentication/ChangePassword", output = "http://ICRA.SOAP.DataProdiver/Response/Authentication/ChangePassword")
    @RequestWrapper(localName = "ChangePassword", targetNamespace = "http://ICRA.SOAP.DataProdiver/Authentication", className = "dataprodiver.soap.icra.authentication.ChangePassword")
    @ResponseWrapper(localName = "ChangePasswordResponse", targetNamespace = "http://ICRA.SOAP.DataProdiver/Authentication", className = "dataprodiver.soap.icra.authentication.ChangePasswordResponse")
    @WebResult(name = "ChangePasswordResult", targetNamespace = "http://ICRA.SOAP.DataProdiver/Authentication")
    public com.moptra.go4wealth.prs.navapi.icra.datacontracts.AuthToken changePassword(
        @WebParam(name = "AuthToken", targetNamespace = "http://ICRA.SOAP.DataProdiver/Authentication")
        com.moptra.go4wealth.prs.navapi.icra.datacontracts.AuthToken authToken,
        @WebParam(name = "OldPassword", targetNamespace = "http://ICRA.SOAP.DataProdiver/Authentication")
        byte[] oldPassword,
        @WebParam(name = "NewPassword", targetNamespace = "http://ICRA.SOAP.DataProdiver/Authentication")
        byte[] newPassword
    );

    @WebMethod(operationName = "LogIn", action = "http://ICRA.SOAP.DataProdiver/Authentication/SingInToService")
    @Action(input = "http://ICRA.SOAP.DataProdiver/Authentication/SingInToService", output = "http://ICRA.SOAP.DataProdiver/Response/Authentication/SingInToService")
    @RequestWrapper(localName = "LogIn", targetNamespace = "http://ICRA.SOAP.DataProdiver/Authentication", className = "dataprodiver.soap.icra.authentication.LogIn")
    @ResponseWrapper(localName = "LogInResponse", targetNamespace = "http://ICRA.SOAP.DataProdiver/Authentication", className = "dataprodiver.soap.icra.authentication.LogInResponse")
    @WebResult(name = "LogInResult", targetNamespace = "http://ICRA.SOAP.DataProdiver/Authentication")
    public com.moptra.go4wealth.prs.navapi.icra.datacontracts.AuthToken logIn(
        @WebParam(name = "UserName", targetNamespace = "http://ICRA.SOAP.DataProdiver/Authentication")
        java.lang.String userName,
        @WebParam(name = "Password", targetNamespace = "http://ICRA.SOAP.DataProdiver/Authentication")
        byte[] password
    );

    @WebMethod(operationName = "LogOutForcefully", action = "http://ICRA.SOAP.DataProdiver/Authentication/ForceFullyLogOut")
    @Action(input = "http://ICRA.SOAP.DataProdiver/Authentication/ForceFullyLogOut", output = "http://ICRA.SOAP.DataProdiver/Response/Authentication/ForceFullyLogOut")
    @RequestWrapper(localName = "LogOutForcefully", targetNamespace = "http://ICRA.SOAP.DataProdiver/Authentication", className = "dataprodiver.soap.icra.authentication.LogOutForcefully")
    @ResponseWrapper(localName = "LogOutForcefullyResponse", targetNamespace = "http://ICRA.SOAP.DataProdiver/Authentication", className = "dataprodiver.soap.icra.authentication.LogOutForcefullyResponse")
    @WebResult(name = "LogOutForcefullyResult", targetNamespace = "http://ICRA.SOAP.DataProdiver/Authentication")
    public java.lang.Boolean logOutForcefully(
        @WebParam(name = "UserName", targetNamespace = "http://ICRA.SOAP.DataProdiver/Authentication")
        java.lang.String userName,
        @WebParam(name = "Password", targetNamespace = "http://ICRA.SOAP.DataProdiver/Authentication")
        byte[] password
    );

    @WebMethod(operationName = "LogOut", action = "http://ICRA.SOAP.DataProdiver/Authentication/LogOut")
    @Action(input = "http://ICRA.SOAP.DataProdiver/Authentication/LogOut", output = "http://ICRA.SOAP.DataProdiver/Response/Authentication/LogOut")
    @RequestWrapper(localName = "LogOut", targetNamespace = "http://ICRA.SOAP.DataProdiver/Authentication", className = "dataprodiver.soap.icra.authentication.LogOut")
    @ResponseWrapper(localName = "LogOutResponse", targetNamespace = "http://ICRA.SOAP.DataProdiver/Authentication", className = "dataprodiver.soap.icra.authentication.LogOutResponse")
    @WebResult(name = "LogOutResult", targetNamespace = "http://ICRA.SOAP.DataProdiver/Authentication")
    public com.moptra.go4wealth.prs.navapi.icra.datacontracts.AuthToken logOut(
        @WebParam(name = "AuthToken", targetNamespace = "http://ICRA.SOAP.DataProdiver/Authentication")
        com.moptra.go4wealth.prs.navapi.icra.datacontracts.AuthToken authToken
    );
}
