package com.moptra.go4wealth.prs.orderapi.tempuri;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import com.moptra.go4wealth.prs.orderapi.in.bsestarmf.MFOrderEntry;

import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2018-07-24T18:38:41.914+05:30
 * Generated source version: 2.7.5
 * 
 */
@WebServiceClient(name = "MFOrder", 
                  wsdlLocation = "classpath:wsdl/MFOrder.xml",
                  targetNamespace = "http://tempuri.org/") 
public class MFOrder extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "MFOrder");
    public final static QName WSHttpBindingMFOrderEntry = new QName("http://tempuri.org/", "WSHttpBinding_MFOrderEntry");
    public final static QName WSHttpBindingMFOrderEntry1 = new QName("http://tempuri.org/", "WSHttpBinding_MFOrderEntry1");
    static {
        URL url = MFOrder.class.getClassLoader().getResource("wsdl/MFOrder.xml");
        if (url == null) {
            java.util.logging.Logger.getLogger(MFOrder.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/MFOrder.xml");
        }       
        WSDL_LOCATION = url;   
    }

    public MFOrder(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MFOrder(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MFOrder() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MFOrder(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MFOrder(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MFOrder(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns MFOrderEntry
     */
    @WebEndpoint(name = "WSHttpBinding_MFOrderEntry")
    public MFOrderEntry getWSHttpBindingMFOrderEntry() {
        return super.getPort(WSHttpBindingMFOrderEntry, MFOrderEntry.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MFOrderEntry
     */
    @WebEndpoint(name = "WSHttpBinding_MFOrderEntry")
    public MFOrderEntry getWSHttpBindingMFOrderEntry(WebServiceFeature... features) {
        return super.getPort(WSHttpBindingMFOrderEntry, MFOrderEntry.class, features);
    }
    /**
     *
     * @return
     *     returns MFOrderEntry
     */
    @WebEndpoint(name = "WSHttpBinding_MFOrderEntry1")
    public MFOrderEntry getWSHttpBindingMFOrderEntry1() {
        return super.getPort(WSHttpBindingMFOrderEntry1, MFOrderEntry.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MFOrderEntry
     */
    @WebEndpoint(name = "WSHttpBinding_MFOrderEntry1")
    public MFOrderEntry getWSHttpBindingMFOrderEntry1(WebServiceFeature... features) {
        return super.getPort(WSHttpBindingMFOrderEntry1, MFOrderEntry.class, features);
    }

}
