
package com.moptra.go4wealth.prs.imageupload.tempuri;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2018-06-12T12:17:28.036+05:30
 * Generated source version: 2.7.5
 * 
 */
public final class IStarMFFileUploadService_WSHttpBindingIStarMFFileUploadService1_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "StarMFFileUploadService");

    private IStarMFFileUploadService_WSHttpBindingIStarMFFileUploadService1_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = StarMFFileUploadService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        StarMFFileUploadService ss = new StarMFFileUploadService(wsdlURL, SERVICE_NAME);
        IStarMFFileUploadService port = ss.getWSHttpBindingIStarMFFileUploadService1();  
        
        {
        System.out.println("Invoking uploadFile...");
        com.moptra.go4wealth.prs.imageupload.starmffileuploadservice.FileData _uploadFile_data = null;
        com.moptra.go4wealth.prs.imageupload.starmffileuploadservice.Response _uploadFile__return = port.uploadFile(_uploadFile_data);
        System.out.println("uploadFile.result=" + _uploadFile__return);


        }
        {
        System.out.println("Invoking uploadMandateScanFile...");
        com.moptra.go4wealth.prs.imageupload.starmffileuploadservice.MandateScanFileData _uploadMandateScanFile_data = null;
        com.moptra.go4wealth.prs.imageupload.starmffileuploadservice.Response _uploadMandateScanFile__return = port.uploadMandateScanFile(_uploadMandateScanFile_data);
        System.out.println("uploadMandateScanFile.result=" + _uploadMandateScanFile__return);


        }
        {
        System.out.println("Invoking jsonData...");
        java.lang.String _jsonData_data = "";
        port.jsonData(_jsonData_data);


        }
        {
        System.out.println("Invoking getPassword...");
        com.moptra.go4wealth.prs.imageupload.starmffileuploadservice.PasswordRequest _getPassword_param = null;
        com.moptra.go4wealth.prs.imageupload.starmffileuploadservice.Response _getPassword__return = port.getPassword(_getPassword_param);
        System.out.println("getPassword.result=" + _getPassword__return);


        }

        System.exit(0);
    }

}
