package com.moptra.go4wealth.prs.imageupload.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2018-06-12T12:17:28.052+05:30
 * Generated source version: 2.7.5
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IStarMFFileUploadService")
@XmlSeeAlso({com.moptra.go4wealth.prs.imageupload.starmffileuploadservice.ObjectFactory.class, ObjectFactory.class, com.moptra.go4wealth.prs.imageupload.starmffileuploadservice.ObjectFactory.class})
public interface IStarMFFileUploadService {

    @WebMethod(operationName = "UploadFile", action = "http://tempuri.org/IStarMFFileUploadService/UploadFile")
    @Action(input = "http://tempuri.org/IStarMFFileUploadService/UploadFile", output = "http://tempuri.org/IStarMFFileUploadService/UploadFileResponse")
    @RequestWrapper(localName = "UploadFile", targetNamespace = "http://tempuri.org/", className = "com.moptra.go4wealth.prs.imageupload.tempuri.UploadFile")
    @ResponseWrapper(localName = "UploadFileResponse", targetNamespace = "http://tempuri.org/", className = "com.moptra.go4wealth.prs.imageupload.tempuri.UploadFileResponse")
    @WebResult(name = "UploadFileResult", targetNamespace = "http://tempuri.org/")
    public com.moptra.go4wealth.prs.imageupload.starmffileuploadservice.Response uploadFile(
        @WebParam(name = "data", targetNamespace = "http://tempuri.org/")
        com.moptra.go4wealth.prs.imageupload.starmffileuploadservice.FileData data
    );

    @WebMethod(operationName = "UploadMandateScanFile", action = "http://tempuri.org/IStarMFFileUploadService/UploadMandateScanFile")
    @Action(input = "http://tempuri.org/IStarMFFileUploadService/UploadMandateScanFile", output = "http://tempuri.org/IStarMFFileUploadService/UploadMandateScanFileResponse")
    @RequestWrapper(localName = "UploadMandateScanFile", targetNamespace = "http://tempuri.org/", className = "com.moptra.go4wealth.prs.imageupload.tempuri.UploadMandateScanFile")
    @ResponseWrapper(localName = "UploadMandateScanFileResponse", targetNamespace = "http://tempuri.org/", className = "com.moptra.go4wealth.prs.imageupload.tempuri.UploadMandateScanFileResponse")
    @WebResult(name = "UploadMandateScanFileResult", targetNamespace = "http://tempuri.org/")
    public com.moptra.go4wealth.prs.imageupload.starmffileuploadservice.Response uploadMandateScanFile(
        @WebParam(name = "Data", targetNamespace = "http://tempuri.org/")
        com.moptra.go4wealth.prs.imageupload.starmffileuploadservice.MandateScanFileData data
    );

    @WebMethod(operationName = "JsonData", action = "http://tempuri.org/IStarMFFileUploadService/JsonData")
    @Action(input = "http://tempuri.org/IStarMFFileUploadService/JsonData", output = "http://tempuri.org/IStarMFFileUploadService/JsonDataResponse")
    @RequestWrapper(localName = "JsonData", targetNamespace = "http://tempuri.org/", className = "com.moptra.go4wealth.prs.imageupload.tempuri.JsonData")
    @ResponseWrapper(localName = "JsonDataResponse", targetNamespace = "http://tempuri.org/", className = "com.moptra.go4wealth.prs.imageupload.tempuri.JsonDataResponse")
    public void jsonData(
        @WebParam(name = "Data", targetNamespace = "http://tempuri.org/")
        java.lang.String data
    );

    @WebMethod(operationName = "GetPassword", action = "http://tempuri.org/IStarMFFileUploadService/GetPassword")
    @Action(input = "http://tempuri.org/IStarMFFileUploadService/GetPassword", output = "http://tempuri.org/IStarMFFileUploadService/GetPasswordResponse")
    @RequestWrapper(localName = "GetPassword", targetNamespace = "http://tempuri.org/", className = "com.moptra.go4wealth.prs.imageupload.tempuri.GetPassword")
    @ResponseWrapper(localName = "GetPasswordResponse", targetNamespace = "http://tempuri.org/", className = "com.moptra.go4wealth.prs.imageupload.tempuri.GetPasswordResponse")
    @WebResult(name = "GetPasswordResult", targetNamespace = "http://tempuri.org/")
    public com.moptra.go4wealth.prs.imageupload.starmffileuploadservice.Response getPassword(
        @WebParam(name = "Param", targetNamespace = "http://tempuri.org/")
        com.moptra.go4wealth.prs.imageupload.starmffileuploadservice.PasswordRequest param
    );
}
