package com.moptra.go4wealth.prs.imageupload.tempuri;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2018-06-12T12:17:28.064+05:30
 * Generated source version: 2.7.5
 * 
 */
@WebServiceClient(name = "StarMFFileUploadService", 
                  wsdlLocation = "classpath:wsdl/StarMFFileUploadService.xml",
                  targetNamespace = "http://tempuri.org/") 
public class StarMFFileUploadService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "StarMFFileUploadService");
    public final static QName WSHttpBindingIStarMFFileUploadService = new QName("http://tempuri.org/", "WSHttpBinding_IStarMFFileUploadService");
    public final static QName WSHttpBindingIStarMFFileUploadService1 = new QName("http://tempuri.org/", "WSHttpBinding_IStarMFFileUploadService1");
    static {
        URL url = StarMFFileUploadService.class.getClassLoader().getResource("wsdl/StarMFFileUploadService.xml");
        if (url == null) {
            java.util.logging.Logger.getLogger(StarMFFileUploadService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/StarMFFileUploadService.xml");
        }       
        WSDL_LOCATION = url;   
    }

    public StarMFFileUploadService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public StarMFFileUploadService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StarMFFileUploadService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public StarMFFileUploadService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public StarMFFileUploadService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public StarMFFileUploadService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IStarMFFileUploadService
     */
    @WebEndpoint(name = "WSHttpBinding_IStarMFFileUploadService")
    public IStarMFFileUploadService getWSHttpBindingIStarMFFileUploadService() {
        return super.getPort(WSHttpBindingIStarMFFileUploadService, IStarMFFileUploadService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IStarMFFileUploadService
     */
    @WebEndpoint(name = "WSHttpBinding_IStarMFFileUploadService")
    public IStarMFFileUploadService getWSHttpBindingIStarMFFileUploadService(WebServiceFeature... features) {
        return super.getPort(WSHttpBindingIStarMFFileUploadService, IStarMFFileUploadService.class, features);
    }
    /**
     *
     * @return
     *     returns IStarMFFileUploadService
     */
    @WebEndpoint(name = "WSHttpBinding_IStarMFFileUploadService1")
    public IStarMFFileUploadService getWSHttpBindingIStarMFFileUploadService1() {
        return super.getPort(WSHttpBindingIStarMFFileUploadService1, IStarMFFileUploadService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IStarMFFileUploadService
     */
    @WebEndpoint(name = "WSHttpBinding_IStarMFFileUploadService1")
    public IStarMFFileUploadService getWSHttpBindingIStarMFFileUploadService1(WebServiceFeature... features) {
        return super.getPort(WSHttpBindingIStarMFFileUploadService1, IStarMFFileUploadService.class, features);
    }

}
