package com.moptra.go4wealth.bean;
// Generated Aug 1, 2018 7:26:48 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AddressState generated by hbm2java
 */
@Entity
@Table(name = "address_state", catalog = "go4wealthdb")
public class AddressState implements java.io.Serializable {

	private Integer addressStateId;
	private String addressStatename;
	private String addressStateCode;
	private Set<AddressCity> addressCities = new HashSet<AddressCity>(0);

	public AddressState() {
	}

	public AddressState(String addressStatename,String addressStateCode) {
		this.addressStatename = addressStatename;
		this.addressStateCode = addressStateCode;
	}

	public AddressState(String addressStatename,String addressStateCode, Set<AddressCity> addressCities) {
		this.addressStatename = addressStatename;
		this.addressCities = addressCities;
		this.addressStateCode = addressStateCode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ADDRESS_STATE_ID", unique = true, nullable = false)
	public Integer getAddressStateId() {
		return this.addressStateId;
	}

	public void setAddressStateId(Integer addressStateId) {
		this.addressStateId = addressStateId;
	}

	@Column(name = "ADDRESS_STATENAME", nullable = false, length = 50)
	public String getAddressStatename() {
		return this.addressStatename;
	}
	
	public void setAddressStatename(String addressStatename) {
		this.addressStatename = addressStatename;
	}
	public void setAddressStateCode(String addressStateCode) {
		this.addressStateCode = addressStateCode;
	}
	
	@Column(name = "ADDRESS_STATE_CODE", nullable = false, length = 5)
	public String getAddressStateCode() {
		return addressStateCode;
	}


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "addressState")
	public Set<AddressCity> getAddressCities() {
		return this.addressCities;
	}

	public void setAddressCities(Set<AddressCity> addressCities) {
		this.addressCities = addressCities;
	}

}
