package com.moptra.go4wealth.bean;
// Generated 10 May, 2018 6:49:49 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AddressProof generated by hbm2java
 */
@Entity
@Table(name = "address_proof", catalog = "go4wealthdb", uniqueConstraints = @UniqueConstraint(columnNames = "ADDRESS_PROOF_NO"))
public class AddressProof implements java.io.Serializable {

	private Integer addressProofId;
	private User user;
	private String addressProofName;
	private String addressProofNo;
	private String frontImage;
	private String backImage;
	private String address;
	private String pincode;
	private String city;
	private String state;
	private Integer field1;
	private String field2;
	private String field3;
	private String mobileWithAadhaar;
	private String verified;
	private String addressType;
	private String incomeSlab;
	private String pep;

	public AddressProof() {
	}

	public AddressProof(User user, String addressProofName,String addressType,String incomeSlab,String pep) {
		this.user = user;
		this.addressProofName = addressProofName;
		this.addressType = addressType;
		this.incomeSlab = incomeSlab;
		this.pep = pep;
	}

	public AddressProof(User user, String addressProofName, String addressProofNo, String frontImage, String backImage,
			String address, String pincode, String city, String state, Integer field1, String field2, String field3,String mobileWithAadhaar,
			String verified,String addressType,String incomeSlab,String pep) {
		this.user = user;
		this.addressProofName = addressProofName;
		this.addressProofNo = addressProofNo;
		this.frontImage = frontImage;
		this.backImage = backImage;
		this.address = address;
		this.pincode = pincode;
		this.city = city;
		this.state = state;
		this.field1 = field1;
		this.field2 = field2;
		this.field3 = field3;
		this.mobileWithAadhaar = mobileWithAadhaar;
		this.verified = verified;
		this.addressType = addressType;
		this.incomeSlab = incomeSlab;
		this.pep = pep;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ADDRESS_PROOF_ID", unique = true, nullable = false)
	public Integer getAddressProofId() {
		return this.addressProofId;
	}

	public void setAddressProofId(Integer addressProofId) {
		this.addressProofId = addressProofId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "USER_ID", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "ADDRESS_PROOF_NAME", nullable = false, length = 50)
	public String getAddressProofName() {
		return this.addressProofName;
	}

	public void setAddressProofName(String addressProofName) {
		this.addressProofName = addressProofName;
	}

	@Column(name = "ADDRESS_PROOF_NO", unique = true, length = 512)
	public String getAddressProofNo() {
		return this.addressProofNo;
	}

	public void setAddressProofNo(String addressProofNo) {
		this.addressProofNo = addressProofNo;
	}

	@Column(name = "FRONT_IMAGE", length = 256)
	public String getFrontImage() {
		return this.frontImage;
	}

	public void setFrontImage(String frontImage) {
		this.frontImage = frontImage;
	}

	@Column(name = "BACK_IMAGE", length = 256)
	public String getBackImage() {
		return this.backImage;
	}

	public void setBackImage(String backImage) {
		this.backImage = backImage;
	}

	@Column(name = "ADDRESS", length = 512)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "PINCODE", length = 10)
	public String getPincode() {
		return this.pincode;
	}

	public void setPincode(String pincode) {
		this.pincode = pincode;
	}

	@Column(name = "CITY", length = 100)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "STATE", length = 100)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "FIELD1")
	public Integer getField1() {
		return this.field1;
	}

	public void setField1(Integer field1) {
		this.field1 = field1;
	}

	@Column(name = "FIELD2", length = 512)
	public String getField2() {
		return this.field2;
	}

	public void setField2(String field2) {
		this.field2 = field2;
	}

	@Column(name = "FIELD3", length = 512)
	public String getField3() {
		return this.field3;
	}

	public void setField3(String field3) {
		this.field3 = field3;
	}

	@Column(name = "MOBILE_WITH_AADHAAR", length = 50)
	public String getMobileWithAadhaar() {
		return mobileWithAadhaar;
	}

	public void setMobileWithAadhaar(String mobileWithAadhaar) {
		this.mobileWithAadhaar = mobileWithAadhaar;
	}

	@Column(name = "VERIFIED", length = 50)
	public String getVerified() {
		return verified;
	}

	public void setVerified(String verified) {
		this.verified = verified;
	}

	@Column(name = "ADDRESS_TYPE", length = 50)
	public String getAddressType() {
		return addressType;
	}

	public void setAddressType(String addressType) {
		this.addressType = addressType;
	}

	@Column(name = "INCOME_SLAB", length = 50)
	public String getIncomeSlab() {
		return incomeSlab;
	}

	public void setIncomeSlab(String incomeSlab) {
		this.incomeSlab = incomeSlab;
	}

	@Column(name = "PEP", length = 50)
	public String getPep() {
		return pep;
	}

	public void setPep(String pep) {
		this.pep = pep;
	}

}
