package com.moptra.go4wealth.bean;
// Generated Aug 1, 2018 7:26:48 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AddressCity generated by hbm2java
 */
@Entity
@Table(name = "address_city", catalog = "go4wealthdb")
public class AddressCity implements java.io.Serializable {

	private Integer addressCityId;
	private AddressState addressState;
	private String addressCityname;
	private String field1;
	private String field2;
	private String field3;

	public AddressCity() {
	}

	public AddressCity(AddressState addressState, String addressCityname) {
		this.addressState = addressState;
		this.addressCityname = addressCityname;
	}

	public AddressCity(AddressState addressState, String addressCityname, String field1, String field2, String field3) {
		this.addressState = addressState;
		this.addressCityname = addressCityname;
		this.field1 = field1;
		this.field2 = field2;
		this.field3 = field3;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ADDRESS_CITY_ID", unique = true, nullable = false)
	public Integer getAddressCityId() {
		return this.addressCityId;
	}

	public void setAddressCityId(Integer addressCityId) {
		this.addressCityId = addressCityId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ADDRESS_STATE_ID", nullable = false)
	public AddressState getAddressState() {
		return this.addressState;
	}

	public void setAddressState(AddressState addressState) {
		this.addressState = addressState;
	}

	@Column(name = "ADDRESS_CITYNAME", nullable = false, length = 50)
	public String getAddressCityname() {
		return this.addressCityname;
	}

	public void setAddressCityname(String addressCityname) {
		this.addressCityname = addressCityname;
	}

	@Column(name = "FIELD1", length = 50)
	public String getField1() {
		return this.field1;
	}

	public void setField1(String field1) {
		this.field1 = field1;
	}

	@Column(name = "FIELD2", length = 50)
	public String getField2() {
		return this.field2;
	}

	public void setField2(String field2) {
		this.field2 = field2;
	}

	@Column(name = "FIELD3", length = 50)
	public String getField3() {
		return this.field3;
	}

	public void setField3(String field3) {
		this.field3 = field3;
	}

}
