package com.moptra.go4wealth.bean;
// Generated May 14, 2018 1:41:21 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.annotations.UpdateTimestamp;

/**
 * AgentProfile generated by hbm2java
 */
@Entity
@Table(name = "agent_profile", catalog = "go4wealthdb")
public class AgentProfile implements java.io.Serializable {

	private int agentProfileId;
	private User user;
	private String arnCode;
	private String aadhaarNumber;
	private String panNumber;
	private Date createdTimestamp;
	private Date updatedDateTime;
	private Integer field1;
	private String field2;

	public AgentProfile() {
	}

	public AgentProfile(User user, Date createdTimestamp, Date updatedDateTime) {
		this.user = user;
		this.createdTimestamp = createdTimestamp;
		this.updatedDateTime = updatedDateTime;
	}

	public AgentProfile(User user, String arnCode, String aadhaarNumber, String panNumber, Date createdTimestamp,
			Date updatedDateTime, Integer field1, String field2) {
		this.user = user;
		this.arnCode = arnCode;
		this.aadhaarNumber = aadhaarNumber;
		this.panNumber = panNumber;
		this.createdTimestamp = createdTimestamp;
		this.updatedDateTime = updatedDateTime;
		this.field1 = field1;
		this.field2 = field2;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "user"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "AGENT_PROFILE_ID", unique = true, nullable = false)
	public int getAgentProfileId() {
		return this.agentProfileId;
	}

	public void setAgentProfileId(int agentProfileId) {
		this.agentProfileId = agentProfileId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "ARN_CODE", length = 128)
	public String getArnCode() {
		return this.arnCode;
	}

	public void setArnCode(String arnCode) {
		this.arnCode = arnCode;
	}

	@Column(name = "AADHAAR_NUMBER", length = 128)
	public String getAadhaarNumber() {
		return this.aadhaarNumber;
	}

	public void setAadhaarNumber(String aadhaarNumber) {
		this.aadhaarNumber = aadhaarNumber;
	}

	@Column(name = "PAN_NUMBER", length = 128)
	public String getPanNumber() {
		return this.panNumber;
	}

	public void setPanNumber(String panNumber) {
		this.panNumber = panNumber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIMESTAMP", nullable = false, length = 19)
	public Date getCreatedTimestamp() {
		return this.createdTimestamp;
	}

	public void setCreatedTimestamp(Date createdTimestamp) {
		this.createdTimestamp = createdTimestamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@UpdateTimestamp
	@Column(name = "UPDATED_DATE_TIME", nullable = false, length = 19)
	public Date getUpdatedDateTime() {
		return this.updatedDateTime;
	}

	public void setUpdatedDateTime(Date updatedDateTime) {
		this.updatedDateTime = updatedDateTime;
	}

	@Column(name = "FIELD1")
	public Integer getField1() {
		return this.field1;
	}

	public void setField1(Integer field1) {
		this.field1 = field1;
	}

	@Column(name = "FIELD2", length = 128)
	public String getField2() {
		return this.field2;
	}

	public void setField2(String field2) {
		this.field2 = field2;
	}

}
