package com.moptra.go4wealth.bean;
// Generated May 14, 2018 1:41:21 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AgeSlabs generated by hbm2java
 */
@Entity
@Table(name = "age_slabs", catalog = "go4wealthdb")
public class AgeSlabs implements java.io.Serializable {

	private Integer ageSlabId;
	private String ageSlabName;
	private Integer ageFrom;
	private Integer ageTo;
	private String ageSlabCode;

	public AgeSlabs() {
	}

	public AgeSlabs(String ageSlabName, Integer ageFrom, Integer ageTo, String ageSlabCode) {
		this.ageSlabName = ageSlabName;
		this.ageFrom = ageFrom;
		this.ageTo = ageTo;
		this.ageSlabCode = ageSlabCode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "AGE_SLAB_ID", unique = true, nullable = false)
	public Integer getAgeSlabId() {
		return this.ageSlabId;
	}

	public void setAgeSlabId(Integer ageSlabId) {
		this.ageSlabId = ageSlabId;
	}

	@Column(name = "AGE_SLAB_NAME", length = 126)
	public String getAgeSlabName() {
		return this.ageSlabName;
	}

	public void setAgeSlabName(String ageSlabName) {
		this.ageSlabName = ageSlabName;
	}

	@Column(name = "AGE_FROM")
	public Integer getAgeFrom() {
		return this.ageFrom;
	}

	public void setAgeFrom(Integer ageFrom) {
		this.ageFrom = ageFrom;
	}

	@Column(name = "AGE_TO")
	public Integer getAgeTo() {
		return this.ageTo;
	}

	public void setAgeTo(Integer ageTo) {
		this.ageTo = ageTo;
	}

	@Column(name = "AGE_SLAB_CODE", length = 5)
	public String getAgeSlabCode() {
		return this.ageSlabCode;
	}

	public void setAgeSlabCode(String ageSlabCode) {
		this.ageSlabCode = ageSlabCode;
	}

}
