package com.moptra.go4wealth.bean;
// Generated May 15, 2018 4:33:52 PM by Hibernate Tools 5.1.0.Alpha1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AssetClassInternal generated by hbm2java
 */
@Entity
@Table(name = "asset_class_internal", catalog = "go4wealthdb")
public class AssetClassInternal implements java.io.Serializable {

	private Integer assetClassInternalId;
	private String fundType;
	private String fundTypeCode;
	private BigDecimal roiExptd;
	private BigDecimal inflAdjustedReturn;

	public AssetClassInternal() {
	}

	public AssetClassInternal(String fundType, String fundTypeCode) {
		this.fundType = fundType;
		this.fundTypeCode = fundTypeCode;
	}

	public AssetClassInternal(String fundType, String fundTypeCode, BigDecimal roiExptd,
			BigDecimal inflAdjustedReturn) {
		this.fundType = fundType;
		this.fundTypeCode = fundTypeCode;
		this.roiExptd = roiExptd;
		this.inflAdjustedReturn = inflAdjustedReturn;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ASSET_CLASS_INTERNAL_ID", unique = true, nullable = false)
	public Integer getAssetClassInternalId() {
		return this.assetClassInternalId;
	}

	public void setAssetClassInternalId(Integer assetClassInternalId) {
		this.assetClassInternalId = assetClassInternalId;
	}

	@Column(name = "FUND_TYPE", nullable = false, length = 126)
	public String getFundType() {
		return this.fundType;
	}

	public void setFundType(String fundType) {
		this.fundType = fundType;
	}

	@Column(name = "FUND_TYPE_CODE", nullable = false, length = 10)
	public String getFundTypeCode() {
		return this.fundTypeCode;
	}

	public void setFundTypeCode(String fundTypeCode) {
		this.fundTypeCode = fundTypeCode;
	}

	@Column(name = "ROI_EXPTD", precision = 10, scale = 5)
	public BigDecimal getRoiExptd() {
		return this.roiExptd;
	}

	public void setRoiExptd(BigDecimal roiExptd) {
		this.roiExptd = roiExptd;
	}

	@Column(name = "INFL_ADJUSTED_RETURN", precision = 10, scale = 5)
	public BigDecimal getInflAdjustedReturn() {
		return this.inflAdjustedReturn;
	}

	public void setInflAdjustedReturn(BigDecimal inflAdjustedReturn) {
		this.inflAdjustedReturn = inflAdjustedReturn;
	}

}
