package com.moptra.go4wealth.bean;
// Generated May 14, 2018 1:41:21 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Authority generated by hbm2java
 */
@Entity
@Table(name = "authority", catalog = "go4wealthdb")
public class Authority implements java.io.Serializable {

	private Integer authorityId;
	private String authorityType;
	private Set<UserAuthority> userAuthorities = new HashSet<UserAuthority>(0);

	public Authority() {
	}

	public Authority(String authorityType, Set<UserAuthority> userAuthorities) {
		this.authorityType = authorityType;
		this.userAuthorities = userAuthorities;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "AUTHORITY_ID", unique = true, nullable = false)
	public Integer getAuthorityId() {
		return this.authorityId;
	}

	public void setAuthorityId(Integer authorityId) {
		this.authorityId = authorityId;
	}

	@Column(name = "AUTHORITY_TYPE", length = 126)
	public String getAuthorityType() {
		return this.authorityType;
	}

	public void setAuthorityType(String authorityType) {
		this.authorityType = authorityType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "authority")
	public Set<UserAuthority> getUserAuthorities() {
		return this.userAuthorities;
	}

	public void setUserAuthorities(Set<UserAuthority> userAuthorities) {
		this.userAuthorities = userAuthorities;
	}

}
