package com.moptra.go4wealth.bean;
// Generated 2 Jul, 2018 4:39:40 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * BankCodes generated by hbm2java
 */
@Entity
@Table(name = "bank_codes", catalog = "go4wealthdb", uniqueConstraints = @UniqueConstraint(columnNames = "bank_name"))
public class BankCodes implements java.io.Serializable {

	private Integer bankCodeId;
	private String bankMode;
	private String bankName;
	private String bankCode;
	private Integer field1;
	private String field2;

	public BankCodes() {
	}

	public BankCodes(String bankMode, String bankName, String bankCode) {
		this.bankMode = bankMode;
		this.bankName = bankName;
		this.bankCode = bankCode;
	}

	public BankCodes(String bankMode, String bankName, String bankCode, Integer field1, String field2) {
		this.bankMode = bankMode;
		this.bankName = bankName;
		this.bankCode = bankCode;
		this.field1 = field1;
		this.field2 = field2;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "bank_code_id", unique = true, nullable = false)
	public Integer getBankCodeId() {
		return this.bankCodeId;
	}

	public void setBankCodeId(Integer bankCodeId) {
		this.bankCodeId = bankCodeId;
	}

	@Column(name = "bank_mode", nullable = false, length = 50)
	public String getBankMode() {
		return this.bankMode;
	}

	public void setBankMode(String bankMode) {
		this.bankMode = bankMode;
	}

	@Column(name = "bank_name", unique = true, nullable = false, length = 125)
	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	@Column(name = "bank_code", nullable = false, length = 50)
	public String getBankCode() {
		return this.bankCode;
	}

	public void setBankCode(String bankCode) {
		this.bankCode = bankCode;
	}

	@Column(name = "FIELD1")
	public Integer getField1() {
		return this.field1;
	}

	public void setField1(Integer field1) {
		this.field1 = field1;
	}

	@Column(name = "FIELD2", length = 128)
	public String getField2() {
		return this.field2;
	}

	public void setField2(String field2) {
		this.field2 = field2;
	}

}
