package com.moptra.go4wealth.bean;
// Generated 5 Jul, 2018 12:07:47 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.CreationTimestamp;

/**
 * Blog generated by hbm2java
 */
@Entity
@Table(name = "blog", catalog = "go4wealthdb")
public class Blog implements java.io.Serializable {

	private Integer blogId;
	private BlogCategory blogCategory;
	private String title;
	private String url;
	private String mediaType;
	private String finalWords;
	private String postedBy;
	private String keyWords;
	private String categoryName;
	private String shortDescription;
	private String longDescription;
	private Date postDate;

	public Blog() {
	}

	public Blog(BlogCategory blogCategory, Date postDate) {
		this.blogCategory = blogCategory;
		this.postDate = postDate;
	}

	public Blog(BlogCategory blogCategory, String title, String url, String mediaType, String finalWords,
			String postedBy, String keyWords, String categoryName, String shortDescription, String longDescription,
			Date postDate) {
		this.blogCategory = blogCategory;
		this.title = title;
		this.url = url;
		this.mediaType = mediaType;
		this.finalWords = finalWords;
		this.postedBy = postedBy;
		this.keyWords = keyWords;
		this.categoryName = categoryName;
		this.shortDescription = shortDescription;
		this.longDescription = longDescription;
		this.postDate = postDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "BLOG_ID", unique = true, nullable = false)
	public Integer getBlogId() {
		return this.blogId;
	}

	public void setBlogId(Integer blogId) {
		this.blogId = blogId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BLOG_CATEGORY_ID", nullable = false)
	public BlogCategory getBlogCategory() {
		return this.blogCategory;
	}

	public void setBlogCategory(BlogCategory blogCategory) {
		this.blogCategory = blogCategory;
	}

	@Column(name = "TITLE", length = 126)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "URL", length = 126)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "MEDIA_TYPE", length = 126)
	public String getMediaType() {
		return this.mediaType;
	}

	public void setMediaType(String mediaType) {
		this.mediaType = mediaType;
	}

	@Column(name = "FINAL_WORDS", length = 126)
	public String getFinalWords() {
		return this.finalWords;
	}

	public void setFinalWords(String finalWords) {
		this.finalWords = finalWords;
	}

	@Column(name = "POSTED_BY", length = 126)
	public String getPostedBy() {
		return this.postedBy;
	}

	public void setPostedBy(String postedBy) {
		this.postedBy = postedBy;
	}

	@Column(name = "KEY_WORDS", length = 126)
	public String getKeyWords() {
		return this.keyWords;
	}

	public void setKeyWords(String keyWords) {
		this.keyWords = keyWords;
	}

	@Column(name = "CATEGORY_NAME", length = 126)
	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	@Column(name = "SHORT_DESCRIPTION", length = 5000)
	public String getShortDescription() {
		return this.shortDescription;
	}

	public void setShortDescription(String shortDescription) {
		this.shortDescription = shortDescription;
	}

	@Column(name = "LONG_DESCRIPTION", length = 8000)
	public String getLongDescription() {
		return this.longDescription;
	}

	public void setLongDescription(String longDescription) {
		this.longDescription = longDescription;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@CreationTimestamp
	@Column(name = "POST_DATE", nullable = false, length = 19)
	public Date getPostDate() {
		return this.postDate;
	}

	public void setPostDate(Date postDate) {
		this.postDate = postDate;
	}

}
