package com.moptra.go4wealth.bean;
// Generated 5 Jul, 2018 12:07:47 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BlogCategory generated by hbm2java
 */
@Entity
@Table(name = "blog_category", catalog = "go4wealthdb")
public class BlogCategory implements java.io.Serializable {

	private Integer blogCategoryId;
	private String blogCategoryName;
	private Set<Blog> blogs = new HashSet<Blog>(0);

	public BlogCategory() {
	}

	public BlogCategory(String blogCategoryName, Set<Blog> blogs) {
		this.blogCategoryName = blogCategoryName;
		this.blogs = blogs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "BLOG_CATEGORY_ID", unique = true, nullable = false)
	public Integer getBlogCategoryId() {
		return this.blogCategoryId;
	}

	public void setBlogCategoryId(Integer blogCategoryId) {
		this.blogCategoryId = blogCategoryId;
	}

	@Column(name = "BLOG_CATEGORY_NAME", length = 126)
	public String getBlogCategoryName() {
		return this.blogCategoryName;
	}

	public void setBlogCategoryName(String blogCategoryName) {
		this.blogCategoryName = blogCategoryName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "blogCategory")
	public Set<Blog> getBlogs() {
		return this.blogs;
	}

	public void setBlogs(Set<Blog> blogs) {
		this.blogs = blogs;
	}

}
