package com.moptra.go4wealth.bean;
// Generated May 14, 2018 1:41:21 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cities generated by hbm2java
 */
@Entity
@Table(name = "cities", catalog = "go4wealthdb")
public class Cities implements java.io.Serializable {

	private Integer cityId;
	private String cityName;
	private String cityCode;
	private String mfClassification;

	public Cities() {
	}

	public Cities(String cityName, String cityCode, String mfClassification) {
		this.cityName = cityName;
		this.cityCode = cityCode;
		this.mfClassification = mfClassification;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CITY_ID", unique = true, nullable = false)
	public Integer getCityId() {
		return this.cityId;
	}

	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	@Column(name = "CITY_NAME", length = 126)
	public String getCityName() {
		return this.cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	@Column(name = "CITY_CODE", length = 10)
	public String getCityCode() {
		return this.cityCode;
	}

	public void setCityCode(String cityCode) {
		this.cityCode = cityCode;
	}

	@Column(name = "MF_CLASSIFICATION", length = 50)
	public String getMfClassification() {
		return this.mfClassification;
	}

	public void setMfClassification(String mfClassification) {
		this.mfClassification = mfClassification;
	}

}
