package com.moptra.go4wealth.bean;
// Generated May 14, 2018 1:41:21 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Commission generated by hbm2java
 */
@Entity
@Table(name = "commission", catalog = "go4wealthdb")
public class Commission implements java.io.Serializable {

	private Integer commissionId;
	private User user;
	private long commissionPrice;

	public Commission() {
	}

	public Commission(User user, long commissionPrice) {
		this.user = user;
		this.commissionPrice = commissionPrice;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "COMMISSION_ID", unique = true, nullable = false)
	public Integer getCommissionId() {
		return this.commissionId;
	}

	public void setCommissionId(Integer commissionId) {
		this.commissionId = commissionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "COMMISSION_PRICE", nullable = false)
	public long getCommissionPrice() {
		return this.commissionPrice;
	}

	public void setCommissionPrice(long commissionPrice) {
		this.commissionPrice = commissionPrice;
	}

}
