package com.moptra.go4wealth.bean;
//Generated 22 Feb, 2019 1:21:51 PM by Hibernate Tools 5.1.0.Alpha1

import static javax.persistence.GenerationType.IDENTITY;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.CreationTimestamp;

/**
 * ConsolidatedPortfollio generated by hbm2java
 */
@Entity
@Table(name = "consolidated_portfollio", catalog = "go4wealthdb")
public class ConsolidatedPortfollio implements java.io.Serializable {

	private Integer consolidatedPortfollioId;
	private Integer orderId;
	private BigDecimal currentAmount;
	private String schemeCode;
	private Integer userId;
	private String clientCode;
	private String status;
	private Integer statusCode;
	private String lastNavUpdatedDate;
	private String folioNo;
	private Long sipRegNo;
	private BigDecimal investedAmount;
	private BigDecimal allotedUnit;
	private Date lastRedumptionUpdatedDate;
	private String field1;
	private String field2;
	private Integer tranferInId;
	private BigDecimal field4;
	private Integer goalId;
	private String goalName;
		
	public ConsolidatedPortfollio() {
	}

	public ConsolidatedPortfollio(Integer orderId, BigDecimal currentAmount, String schemeCode, Integer userId,String clientCode, String status,
			Integer statusCode, String lastNavUpdatedDate,String folioNo,Long sipRegNo, BigDecimal investedAmount, 
			BigDecimal allotedUnit, Date lastRedumptionUpdatedDate,String field1, String field2, Integer tranferInId, BigDecimal field4,Integer goalId,String goalName) {
		this.orderId = orderId;
		this.currentAmount = currentAmount;
		this.schemeCode = schemeCode;
		this.userId = userId;
		this.clientCode = clientCode;
		this.status = status;
		this.statusCode = statusCode;
		this.lastNavUpdatedDate = lastNavUpdatedDate;
		this.folioNo = folioNo;
		this.sipRegNo = sipRegNo;
		this.investedAmount = investedAmount;
		this.allotedUnit = allotedUnit;
		this.lastRedumptionUpdatedDate = lastRedumptionUpdatedDate;
		this.field1 = field1;
		this.field2 = field2;
		this.tranferInId = tranferInId;
		this.field4 = field4;
		this.goalId = goalId;
		this.goalName = goalName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Consolidated_Portfollio_Id", unique = true, nullable = false)
	public Integer getConsolidatedPortfollioId() {
		return consolidatedPortfollioId;
	}

	public void setConsolidatedPortfollioId(Integer consolidatedPortfollioId) {
		this.consolidatedPortfollioId = consolidatedPortfollioId;
	}

	@Column(name = "Order_Id")
	public Integer getOrderId() {
		return orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	@Column(name = "Current_Amount", nullable = false, precision = 20, scale = 5)
	public BigDecimal getCurrentAmount() {
		return currentAmount;
	}

	public void setCurrentAmount(BigDecimal currentAmount) {
		this.currentAmount = currentAmount;
	}

	@Column(name = "Scheme_Code")
	public String getSchemeCode() {
		return schemeCode;
	}

	public void setSchemeCode(String schemeCode) {
		this.schemeCode = schemeCode;
	}

	@Column(name = "User_Id")
	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "Client_Code")
	public String getClientCode() {
		return clientCode;
	}

	public void setClientCode(String clientCode) {
		this.clientCode = clientCode;
	}

	@Column(name = "STATUS")
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "STATUS_CODE")
	public Integer getStatusCode() {
		return statusCode;
	}

	public void setStatusCode(Integer statusCode) {
		this.statusCode = statusCode;
	}

	@Column(name = "Last_Nav_Updated_date")
	public String getLastNavUpdatedDate() {
		return lastNavUpdatedDate;
	}

	public void setLastNavUpdatedDate(String lastNavUpdatedDate) {
		this.lastNavUpdatedDate = lastNavUpdatedDate;
	}

	@Column(name = "FOLIO_NO", length = 126)
	public String getFolioNo() {
		return folioNo;
	}

	public void setFolioNo(String folioNo) {
		this.folioNo = folioNo;
	}

	@Column(name = "SIP_Regn_No", length = 50)
	public Long getSipRegNo() {
		return sipRegNo;
	}

	public void setSipRegNo(Long sipRegNo) {
		this.sipRegNo = sipRegNo;
	}

	@Column(name = "INVESTED_AMOUNT", nullable = false, precision = 20, scale = 3)
	public BigDecimal getInvestedAmount() {
		return investedAmount;
	}

	public void setInvestedAmount(BigDecimal investedAmount) {
		this.investedAmount = investedAmount;
	}

	@Column(name = "ALLOTED_UNIT", nullable = false, precision = 20, scale = 3)
	public BigDecimal getAllotedUnit() {
		return allotedUnit;
	}
		
	public void setAllotedUnit(BigDecimal allotedUnit) {
		this.allotedUnit = allotedUnit;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@CreationTimestamp
	@Column(name = "Last_Redumption_Updated_date", nullable = false)
	public Date getLastRedumptionUpdatedDate() {
		return lastRedumptionUpdatedDate;
	}

	public void setLastRedumptionUpdatedDate(Date lastRedumptionUpdatedDate) {
		this.lastRedumptionUpdatedDate = lastRedumptionUpdatedDate;
	}

	@Column(name = "FIELD1", length = 126)
	public String getField1() {
		return field1;
	}

	public void setField1(String field1) {
		this.field1 = field1;
	}

	@Column(name = "FIELD2", length = 126)
	public String getField2() {
		return field2;
	}

	public void setField2(String field2) {
		this.field2 = field2;
	}

	@Column(name = "TRANFER_IN_ID", length = 50)
	public Integer getTranferInId() {
		return tranferInId;
	}

	public void setTranferInId(Integer tranferInId) {
		this.tranferInId = tranferInId;
	}

	@Column(name = "FIELD4", nullable = false, precision = 20, scale = 3)
	public BigDecimal getField4() {
		return field4;
	}

	public void setField4(BigDecimal field4) {
		this.field4 = field4;
	}
	
	@Column(name = "GOAL_ID")
	public Integer getGoalId() {
		return goalId;
	}
	
	public void setGoalId(Integer goalId) {
		this.goalId = goalId;
	}
	
	@Column(name = "GOAL_NAME")
	public String getGoalName() {
		return goalName;
	}
	public void setGoalName(String goalName) {
		this.goalName = goalName;
	}


}