package com.moptra.go4wealth.bean;
// Generated 6 Jul, 2018 5:42:10 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ContactUs generated by hbm2java
 */
@Entity
@Table(name = "contact_us", catalog = "go4wealthdb")
public class ContactUs implements java.io.Serializable {

	private Integer contactUsId;
	private String name;
	private String email;
	private String message;
	private String subject;
	private String field1;
	private String field2;
	private Integer field3;

	public ContactUs() {
	}

	public ContactUs(String name, String email, String message, String subject) {
		this.name = name;
		this.email = email;
		this.message = message;
		this.subject = subject;
	}

	public ContactUs(String name, String email, String message, String subject, String field1, String field2,
			Integer field3) {
		this.name = name;
		this.email = email;
		this.message = message;
		this.subject = subject;
		this.field1 = field1;
		this.field2 = field2;
		this.field3 = field3;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CONTACT_US_ID", unique = true, nullable = false)
	public Integer getContactUsId() {
		return this.contactUsId;
	}

	public void setContactUsId(Integer contactUsId) {
		this.contactUsId = contactUsId;
	}

	@Column(name = "NAME", nullable = false, length = 126)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "EMAIL", nullable = false, length = 126)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "MESSAGE", nullable = false, length = 500)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Column(name = "SUBJECT", nullable = false, length = 126)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "FIELD1", length = 126)
	public String getField1() {
		return this.field1;
	}

	public void setField1(String field1) {
		this.field1 = field1;
	}

	@Column(name = "FIELD2", length = 126)
	public String getField2() {
		return this.field2;
	}

	public void setField2(String field2) {
		this.field2 = field2;
	}

	@Column(name = "FIELD3")
	public Integer getField3() {
		return this.field3;
	}

	public void setField3(Integer field3) {
		this.field3 = field3;
	}

}
