package com.moptra.go4wealth.bean;
// Generated 22 May, 2018 5:18:39 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.CreationTimestamp;

/**
 * FundHouses generated by hbm2java
 */
@Entity
@Table(name = "fund_houses", catalog = "go4wealthdb")
public class FundHouses implements java.io.Serializable {

	private Integer fundHouseId;
	private String fundHouseName;
	private String fundName;
	private String fundSponsor;
	private Date fundReleaseDate;
	private String amcAddress;
	private String website;
	private String field1;
	private String fiel23;

	public FundHouses() {
	}

	public FundHouses(Date fundReleaseDate) {
		this.fundReleaseDate = fundReleaseDate;
	}

	public FundHouses(String fundHouseName, String fundName, String fundSponsor, Date fundReleaseDate,
			String amcAddress, String website, String field1, String fiel23) {
		this.fundHouseName = fundHouseName;
		this.fundName = fundName;
		this.fundSponsor = fundSponsor;
		this.fundReleaseDate = fundReleaseDate;
		this.amcAddress = amcAddress;
		this.website = website;
		this.field1 = field1;
		this.fiel23 = fiel23;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "FUND_HOUSE_ID", unique = true, nullable = false)
	public Integer getFundHouseId() {
		return this.fundHouseId;
	}

	public void setFundHouseId(Integer fundHouseId) {
		this.fundHouseId = fundHouseId;
	}

	@Column(name = "FUND_HOUSE_NAME", length = 126)
	public String getFundHouseName() {
		return this.fundHouseName;
	}

	public void setFundHouseName(String fundHouseName) {
		this.fundHouseName = fundHouseName;
	}

	@Column(name = "FUND_NAME", length = 126)
	public String getFundName() {
		return this.fundName;
	}

	public void setFundName(String fundName) {
		this.fundName = fundName;
	}

	@Column(name = "FUND_SPONSOR", length = 126)
	public String getFundSponsor() {
		return this.fundSponsor;
	}

	public void setFundSponsor(String fundSponsor) {
		this.fundSponsor = fundSponsor;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@CreationTimestamp
	@Column(name = "FUND_RELEASE_DATE", nullable = false, length = 19)
	public Date getFundReleaseDate() {
		return this.fundReleaseDate;
	}

	public void setFundReleaseDate(Date fundReleaseDate) {
		this.fundReleaseDate = fundReleaseDate;
	}

	@Column(name = "AMC_ADDRESS", length = 126)
	public String getAmcAddress() {
		return this.amcAddress;
	}

	public void setAmcAddress(String amcAddress) {
		this.amcAddress = amcAddress;
	}

	@Column(name = "WEBSITE", length = 126)
	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	@Column(name = "FIELD1", length = 128)
	public String getField1() {
		return this.field1;
	}

	public void setField1(String field1) {
		this.field1 = field1;
	}

	@Column(name = "FIEL23", length = 128)
	public String getFiel23() {
		return this.fiel23;
	}

	public void setFiel23(String fiel23) {
		this.fiel23 = fiel23;
	}
}