package com.moptra.go4wealth.bean;
// Generated 14 Aug, 2018 1:19:07 PM by Hibernate Tools 5.1.0.Alpha1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.CreationTimestamp;

/**
 * GoalsOrder generated by hbm2java
 */
@Entity
@Table(name = "goals_order", catalog = "go4wealthdb")
public class GoalsOrder implements java.io.Serializable {

	private Integer goalsOrderId;
	private User user;
	private String description;
	private String riskProfile;
	private String fundType;
	private BigDecimal inflation;
	private BigDecimal roi;
	private BigDecimal totalMonthlySaving;
	private BigDecimal totalLumpsumSaving;
	private BigDecimal totalMonthlyAdjustment;
	private BigDecimal totalLumpsumAdjusment;
	private BigDecimal totalFutureValue;
	private BigDecimal totalAssetValue;
	private String status;
	private Date createdTimestamp;
	private Date updatedDateTime;
	private Integer field1;
	private String field2;
	private String field4;
	private Set<GoalOrderItems> goalOrderItemses = new HashSet<GoalOrderItems>(0);
	private Set<UserAssetItems> userAssetItemses = new HashSet<UserAssetItems>(0);

	public GoalsOrder() {
	}

	public GoalsOrder(User user, BigDecimal inflation, BigDecimal roi, BigDecimal totalMonthlySaving,
			BigDecimal totalLumpsumSaving, BigDecimal totalMonthlyAdjustment, BigDecimal totalLumpsumAdjusment,
			BigDecimal totalFutureValue, BigDecimal totalAssetValue, Date createdTimestamp, Date updatedDateTime, String status) {
		this.user = user;
		this.inflation = inflation;
		this.roi = roi;
		this.totalMonthlySaving = totalMonthlySaving;
		this.totalLumpsumSaving = totalLumpsumSaving;
		this.totalMonthlyAdjustment = totalMonthlyAdjustment;
		this.totalLumpsumAdjusment = totalLumpsumAdjusment;
		this.totalFutureValue = totalFutureValue;
		this.totalAssetValue = totalAssetValue;
		this.createdTimestamp = createdTimestamp;
		this.updatedDateTime = updatedDateTime;
		this.status = status;
	}

	public GoalsOrder(User user, String description, String riskProfile, String fundType, BigDecimal inflation,
			BigDecimal roi, BigDecimal totalMonthlySaving, BigDecimal totalLumpsumSaving,
			BigDecimal totalMonthlyAdjustment, BigDecimal totalLumpsumAdjusment, BigDecimal totalFutureValue,
			BigDecimal totalAssetValue, Date createdTimestamp, Date updatedDateTime, Integer field1, String field2,
			String field4, Set<GoalOrderItems> goalOrderItemses, Set<UserAssetItems> userAssetItemses, String status) {
		this.user = user;
		this.description = description;
		this.riskProfile = riskProfile;
		this.fundType = fundType;
		this.inflation = inflation;
		this.roi = roi;
		this.totalMonthlySaving = totalMonthlySaving;
		this.totalLumpsumSaving = totalLumpsumSaving;
		this.totalMonthlyAdjustment = totalMonthlyAdjustment;
		this.totalLumpsumAdjusment = totalLumpsumAdjusment;
		this.totalFutureValue = totalFutureValue;
		this.totalAssetValue = totalAssetValue;
		this.status = status;
		this.createdTimestamp = createdTimestamp;
		this.updatedDateTime = updatedDateTime;
		this.field1 = field1;
		this.field2 = field2;
		this.field4 = field4;
		this.goalOrderItemses = goalOrderItemses;
		this.userAssetItemses = userAssetItemses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "GOALS_ORDER_ID", unique = true, nullable = false)
	public Integer getGoalsOrderId() {
		return this.goalsOrderId;
	}

	public void setGoalsOrderId(Integer goalsOrderId) {
		this.goalsOrderId = goalsOrderId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "DESCRIPTION", length = 128)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "RISK_PROFILE", length = 126)
	public String getRiskProfile() {
		return this.riskProfile;
	}

	public void setRiskProfile(String riskProfile) {
		this.riskProfile = riskProfile;
	}

	@Column(name = "FUND_TYPE", length = 126)
	public String getFundType() {
		return this.fundType;
	}

	public void setFundType(String fundType) {
		this.fundType = fundType;
	}

	@Column(name = "INFLATION", nullable = false, precision = 10, scale = 5)
	public BigDecimal getInflation() {
		return this.inflation;
	}

	public void setInflation(BigDecimal inflation) {
		this.inflation = inflation;
	}

	@Column(name = "ROI", nullable = false, precision = 10, scale = 5)
	public BigDecimal getRoi() {
		return this.roi;
	}

	public void setRoi(BigDecimal roi) {
		this.roi = roi;
	}

	@Column(name = "TOTAL_MONTHLY_SAVING", nullable = false, precision = 20, scale = 5)
	public BigDecimal getTotalMonthlySaving() {
		return this.totalMonthlySaving;
	}

	public void setTotalMonthlySaving(BigDecimal totalMonthlySaving) {
		this.totalMonthlySaving = totalMonthlySaving;
	}

	@Column(name = "TOTAL_LUMPSUM_SAVING", nullable = false, precision = 20, scale = 5)
	public BigDecimal getTotalLumpsumSaving() {
		return this.totalLumpsumSaving;
	}

	public void setTotalLumpsumSaving(BigDecimal totalLumpsumSaving) {
		this.totalLumpsumSaving = totalLumpsumSaving;
	}

	@Column(name = "TOTAL_MONTHLY_ADJUSTMENT", nullable = false, precision = 20, scale = 5)
	public BigDecimal getTotalMonthlyAdjustment() {
		return this.totalMonthlyAdjustment;
	}

	public void setTotalMonthlyAdjustment(BigDecimal totalMonthlyAdjustment) {
		this.totalMonthlyAdjustment = totalMonthlyAdjustment;
	}

	@Column(name = "TOTAL_LUMPSUM_ADJUSMENT", nullable = false, precision = 20, scale = 5)
	public BigDecimal getTotalLumpsumAdjusment() {
		return this.totalLumpsumAdjusment;
	}

	public void setTotalLumpsumAdjusment(BigDecimal totalLumpsumAdjusment) {
		this.totalLumpsumAdjusment = totalLumpsumAdjusment;
	}

	@Column(name = "TOTAL_FUTURE_VALUE", nullable = false, precision = 20, scale = 5)
	public BigDecimal getTotalFutureValue() {
		return this.totalFutureValue;
	}

	public void setTotalFutureValue(BigDecimal totalFutureValue) {
		this.totalFutureValue = totalFutureValue;
	}

	@Column(name = "TOTAL_ASSET_VALUE", nullable = false, precision = 20, scale = 5)
	public BigDecimal getTotalAssetValue() {
		return this.totalAssetValue;
	}

	public void setTotalAssetValue(BigDecimal totalAssetValue) {
		this.totalAssetValue = totalAssetValue;
	}

	@Column(name = "STATUS", nullable = false, columnDefinition="char(3)")
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@CreationTimestamp
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIMESTAMP", nullable = false, length = 19)
	public Date getCreatedTimestamp() {
		return this.createdTimestamp;
	}

	public void setCreatedTimestamp(Date createdTimestamp) {
		this.createdTimestamp = createdTimestamp;
	}

	@CreationTimestamp
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE_TIME", nullable = false, length = 19)
	public Date getUpdatedDateTime() {
		return this.updatedDateTime;
	}

	public void setUpdatedDateTime(Date updatedDateTime) {
		this.updatedDateTime = updatedDateTime;
	}

	@Column(name = "FIELD1")
	public Integer getField1() {
		return this.field1;
	}

	public void setField1(Integer field1) {
		this.field1 = field1;
	}

	@Column(name = "FIELD2", length = 128)
	public String getField2() {
		return this.field2;
	}

	public void setField2(String field2) {
		this.field2 = field2;
	}

	@Column(name = "FIELD4", length = 128)
	public String getField4() {
		return this.field4;
	}

	public void setField4(String field4) {
		this.field4 = field4;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "goalsOrder")
	public Set<GoalOrderItems> getGoalOrderItemses() {
		return this.goalOrderItemses;
	}

	public void setGoalOrderItemses(Set<GoalOrderItems> goalOrderItemses) {
		this.goalOrderItemses = goalOrderItemses;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "goalsOrder")
	public Set<UserAssetItems> getUserAssetItemses() {
		return this.userAssetItemses;
	}

	public void setUserAssetItemses(Set<UserAssetItems> userAssetItemses) {
		this.userAssetItemses = userAssetItemses;
	}
}
