package com.moptra.go4wealth.bean;
// Generated May 15, 2018 4:33:52 PM by Hibernate Tools 5.1.0.Alpha1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Inflation generated by hbm2java
 */
@Entity
@Table(name = "inflation", catalog = "go4wealthdb")
public class Inflation implements java.io.Serializable {

	private Integer inflationId;
	private String inflationType;
	private String locationOfSpend;
	private BigDecimal inflation;

	public Inflation() {
	}

	public Inflation(String inflationType, String locationOfSpend) {
		this.inflationType = inflationType;
		this.locationOfSpend = locationOfSpend;
	}

	public Inflation(String inflationType, String locationOfSpend, BigDecimal inflation) {
		this.inflationType = inflationType;
		this.locationOfSpend = locationOfSpend;
		this.inflation = inflation;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "INFLATION_ID", unique = true, nullable = false)
	public Integer getInflationId() {
		return this.inflationId;
	}

	public void setInflationId(Integer inflationId) {
		this.inflationId = inflationId;
	}

	@Column(name = "INFLATION_TYPE", nullable = false, length = 126)
	public String getInflationType() {
		return this.inflationType;
	}

	public void setInflationType(String inflationType) {
		this.inflationType = inflationType;
	}

	@Column(name = "LOCATION_OF_SPEND", nullable = false, length = 126)
	public String getLocationOfSpend() {
		return this.locationOfSpend;
	}

	public void setLocationOfSpend(String locationOfSpend) {
		this.locationOfSpend = locationOfSpend;
	}

	@Column(name = "INFLATION", precision = 10, scale = 5)
	public BigDecimal getInflation() {
		return this.inflation;
	}

	public void setInflation(BigDecimal inflation) {
		this.inflation = inflation;
	}

}
