package com.moptra.go4wealth.bean;

//Generated 1 Aug, 2018 2:49:44 PM by Hibernate Tools 5.1.0.Alpha1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
* IsipAllowedBankList generated by hbm2java
*/
@Entity
@Table(name = "isip_allowed_bank_list", catalog = "go4wealthdb")
public class IsipAllowedBankList {
	
	private Integer isipAllowedBankListId;
	private String bankId;
	private String bankName;
	private String remarks;
	private String paymentMode;
	private String field1;
	private String field2;
	private String field3;
	private Integer field4;
	private Integer field5;
	
	public IsipAllowedBankList(){
	}
	
	public IsipAllowedBankList(String bankId,String bankName,String remarks,String paymentMode,String field1,String field2,String field3,Integer field4,Integer field5) {
		this.bankId = bankId;
		this.bankName = bankName;
		this.remarks = remarks;
		this.paymentMode = paymentMode;
		this.field1 = field1;
		this.field2 = field2;
		this.field3 = field3;
		this.field4 = field4;
		this.field5 = field5;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ISIP_ALLOWED_BANK_LIST_ID", unique = true, nullable = false)
	public Integer getIsipAllowedBankListId() {
		return isipAllowedBankListId;
	}

	public void setIsipAllowedBankListId(Integer isipAllowedBankListId) {
		this.isipAllowedBankListId = isipAllowedBankListId;
	}

	@Column(name="BANK_ID", length=512)
	public String getBankId() {
		return bankId;
	}

	public void setBankId(String bankId) {
		this.bankId = bankId;
	}

	@Column(name="BANK_NAME", length=512)
	public String getBankName() {
		return bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	@Column(name="REMARKS", length=512)
	public String getRemarks() {
		return remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "PAYMENT_MODE", length = 512)
	public String getPaymentMode() {
		return paymentMode;
	}

	public void setPaymentMode(String paymentMode) {
		this.paymentMode = paymentMode;
	}

	@Column(name = "FIELD1", length = 512)
	public String getField1() {
		return field1;
	}

	public void setField1(String field1) {
		this.field1 = field1;
	}

	@Column(name = "FIELD2", length = 512)
	public String getField2() {
		return field2;
	}

	public void setField2(String field2) {
		this.field2 = field2;
	}

	@Column(name = "FIELD3", length = 512)
	public String getField3() {
		return field3;
	}

	public void setField3(String field3) {
		this.field3 = field3;
	}

	@Column(name = "FIELD4", length = 50)
	public Integer getField4() {
		return field4;
	}

	public void setField4(Integer field4) {
		this.field4 = field4;
	}

	@Column(name = "FIELD5", length = 50)
	public Integer getField5() {
		return field5;
	}

	public void setField5(Integer field5) {
		this.field5 = field5;
	}

}