package com.moptra.go4wealth.bean;
// Generated May 14, 2018 1:41:21 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * KidsSlabs generated by hbm2java
 */
@Entity
@Table(name = "kids_slabs", catalog = "go4wealthdb")
public class KidsSlabs implements java.io.Serializable {

	private Integer kidsSlabId;
	private String kidsSlabName;
	private Integer kidsSlabValue;
	private String kidsSlabCode;

	public KidsSlabs() {
	}

	public KidsSlabs(String kidsSlabName, Integer kidsSlabValue, String kidsSlabCode) {
		this.kidsSlabName = kidsSlabName;
		this.kidsSlabValue = kidsSlabValue;
		this.kidsSlabCode = kidsSlabCode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "KIDS_SLAB_ID", unique = true, nullable = false)
	public Integer getKidsSlabId() {
		return this.kidsSlabId;
	}

	public void setKidsSlabId(Integer kidsSlabId) {
		this.kidsSlabId = kidsSlabId;
	}

	@Column(name = "KIDS_SLAB_NAME", length = 126)
	public String getKidsSlabName() {
		return this.kidsSlabName;
	}

	public void setKidsSlabName(String kidsSlabName) {
		this.kidsSlabName = kidsSlabName;
	}

	@Column(name = "KIDS_SLAB_VALUE")
	public Integer getKidsSlabValue() {
		return this.kidsSlabValue;
	}

	public void setKidsSlabValue(Integer kidsSlabValue) {
		this.kidsSlabValue = kidsSlabValue;
	}

	@Column(name = "KIDS_SLAB_CODE", length = 5)
	public String getKidsSlabCode() {
		return this.kidsSlabCode;
	}

	public void setKidsSlabCode(String kidsSlabCode) {
		this.kidsSlabCode = kidsSlabCode;
	}

}
