package com.moptra.go4wealth.bean;
// Generated 10 May, 2018 6:49:49 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * KycDetails generated by hbm2java
 */
@Entity
@Table(name = "kyc_details", catalog = "go4wealthdb")
public class KycDetails implements java.io.Serializable {

	private int userId;
	private User user;
	private String motherName;
	private String maritalStatus;
	private String photograph;
	private String panCardImage;
	private Integer field1;
	private String field2;
	private String field3;
	private String fatherName;

	public KycDetails() {
	}

	public KycDetails(User user) {
		this.user = user;
	}

	public KycDetails(User user, String motherName, String maritalStatus, String photograph, String panCardImage,
			Integer field1, String field2, String field3, String fatherName) {
		this.user = user;
		this.motherName = motherName;
		this.maritalStatus = maritalStatus;
		this.photograph = photograph;
		this.panCardImage = panCardImage;
		this.field1 = field1;
		this.field2 = field2;
		this.field3 = field3;
		this.fatherName = fatherName;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "user"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "USER_ID", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "MOTHER_NAME", length = 50)
	public String getMotherName() {
		return this.motherName;
	}

	public void setMotherName(String motherName) {
		this.motherName = motherName;
	}

	@Column(name = "MARITAL_STATUS", length = 20)
	public String getMaritalStatus() {
		return this.maritalStatus;
	}

	public void setMaritalStatus(String maritalStatus) {
		this.maritalStatus = maritalStatus;
	}

	@Column(name = "PHOTOGRAPH", length = 256)
	public String getPhotograph() {
		return this.photograph;
	}

	public void setPhotograph(String photograph) {
		this.photograph = photograph;
	}

	@Column(name = "PAN_CARD_IMAGE", length = 256)
	public String getPanCardImage() {
		return this.panCardImage;
	}

	public void setPanCardImage(String panCardImage) {
		this.panCardImage = panCardImage;
	}

	@Column(name = "FIELD1")
	public Integer getField1() {
		return this.field1;
	}

	public void setField1(Integer field1) {
		this.field1 = field1;
	}

	@Column(name = "FIELD2", length = 128)
	public String getField2() {
		return this.field2;
	}

	public void setField2(String field2) {
		this.field2 = field2;
	}

	@Column(name = "FIELD3", length = 256)
	public String getField3() {
		return this.field3;
	}

	public void setField3(String field3) {
		this.field3 = field3;
	}

	@Column(name = "FATHER_NAME", length = 50)
	public String getFatherName() {
		return fatherName;
	}

	public void setFatherName(String fatherName) {
		this.fatherName = fatherName;
	}
	
	

}
