package com.moptra.go4wealth.bean;
// Generated 8 Oct, 2018 4:54:16 PM by Hibernate Tools 5.1.0.Alpha1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.CreationTimestamp;

/**
 * MaintainCurrentNavCurrentValueForOrders generated by hbm2java
 */
@Entity
@Table(name = "maintain_current_nav_current_value_for_orders", catalog = "go4wealthdb")
public class MaintainCurrentNavCurrentValueForOrders implements java.io.Serializable {

	private Integer maintainCurrentNavCurrentValueForOrdersId;
	private Integer orderId;
	private BigDecimal currentAmount;
	private Integer userId;
	private String clientCode;
	private String status;
	private String lastNavUpdatedDate;
	private String folioNo;
	private Long sipRegnNo;
	private BigDecimal investedAmount;
	private BigDecimal currentUnit;
	private Date lastRedumptionUpdateDate;
	private String schemeCode;

	public MaintainCurrentNavCurrentValueForOrders() {
	}

	public MaintainCurrentNavCurrentValueForOrders(Integer orderId, BigDecimal currentAmount, String schemeCode,
			Integer userId, String clientCode, String status, String lastNavUpdatedDate, String folioNo, Long sipRegnNo,
			BigDecimal investedAmount, BigDecimal currentUnit,Date lastRedumptionUpdateDate) {
		this.orderId = orderId;
		this.currentAmount = currentAmount;
		this.schemeCode = schemeCode;
		this.userId = userId;
		this.clientCode = clientCode;
		this.status = status;
		this.lastNavUpdatedDate = lastNavUpdatedDate;
		this.folioNo = folioNo;
		this.sipRegnNo = sipRegnNo;
		this.investedAmount = investedAmount;
		this.currentUnit = currentUnit;
		this.lastRedumptionUpdateDate = lastRedumptionUpdateDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Maintain_Current_Nav_Current_Value_For_Orders_Id", unique = true, nullable = false)
	public Integer getMaintainCurrentNavCurrentValueForOrdersId() {
		return this.maintainCurrentNavCurrentValueForOrdersId;
	}

	public void setMaintainCurrentNavCurrentValueForOrdersId(Integer maintainCurrentNavCurrentValueForOrdersId) {
		this.maintainCurrentNavCurrentValueForOrdersId = maintainCurrentNavCurrentValueForOrdersId;
	}

	@Column(name = "Order_Id")
	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	@Column(name = "Current_Amount", precision = 20, scale = 5)
	public BigDecimal getCurrentAmount() {
		return this.currentAmount;
	}

	public void setCurrentAmount(BigDecimal currentAmount) {
		this.currentAmount = currentAmount;
	}

	@Column(name = "Scheme_Code")
	public String getSchemeCode() {
		return schemeCode;
	}
	
	public void setSchemeCode(String schemeCode) {
		this.schemeCode = schemeCode;
	}

	@Column(name = "User_Id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "Client_Code", length = 126)
	public String getClientCode() {
		return this.clientCode;
	}

	public void setClientCode(String clientCode) {
		this.clientCode = clientCode;
	}

	@Column(name = "STATUS", length = 126)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "Last_Nav_Updated_date", length = 126)
	public String getLastNavUpdatedDate() {
		return lastNavUpdatedDate;
	}
	
	public void setLastNavUpdatedDate(String lastNavUpdatedDate) {
		this.lastNavUpdatedDate = lastNavUpdatedDate;
	}

	@Column(name = "FOLIO_NO", length = 126)
	public String getFolioNo() {
		return folioNo;
	}
	
	public void setFolioNo(String folioNo) {
		this.folioNo = folioNo;
	}

	@Column(name = "SIP_Regn_No")
	public Long getSipRegnNo() {
		return sipRegnNo;
	}
	
	public void setSipRegnNo(Long sipRegnNo) {
		this.sipRegnNo = sipRegnNo;
	}

	@Column(name = "INVESTED_AMOUNT")
	public BigDecimal getInvestedAmount() {
		return investedAmount;
	}
	
	public void setInvestedAmount(BigDecimal investedAmount) {
		this.investedAmount = investedAmount;
	}
	

	@Column(name = "CURRENT_UNIT")
	public BigDecimal getCurrentUnit() {
		return currentUnit;
	}
	
	public void setCurrentUnit(BigDecimal currentUnit) {
		this.currentUnit = currentUnit;
	}
	
	@CreationTimestamp
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Last_Redumption_Updated_date", nullable = false, length = 19)
	public Date getLastRedumptionUpdateDate() {
		return lastRedumptionUpdateDate;
	}
	
	public void setLastRedumptionUpdateDate(Date lastRedumptionUpdateDate) {
		this.lastRedumptionUpdateDate = lastRedumptionUpdateDate;
	}

}
