package com.moptra.go4wealth.bean;
// Generated May 14, 2018 1:41:21 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MaritalStatus generated by hbm2java
 */
@Entity
@Table(name = "marital_status", catalog = "go4wealthdb")
public class MaritalStatus implements java.io.Serializable {

	private Integer maritalStatusId;
	private String maritalStatusName;
	private String maritalStatusValue;
	private String maritalStatusCode;

	public MaritalStatus() {
	}

	public MaritalStatus(String maritalStatusName, String maritalStatusValue, String maritalStatusCode) {
		this.maritalStatusName = maritalStatusName;
		this.maritalStatusValue = maritalStatusValue;
		this.maritalStatusCode = maritalStatusCode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MARITAL_STATUS_ID", unique = true, nullable = false)
	public Integer getMaritalStatusId() {
		return this.maritalStatusId;
	}

	public void setMaritalStatusId(Integer maritalStatusId) {
		this.maritalStatusId = maritalStatusId;
	}

	@Column(name = "MARITAL_STATUS_NAME", length = 126)
	public String getMaritalStatusName() {
		return this.maritalStatusName;
	}

	public void setMaritalStatusName(String maritalStatusName) {
		this.maritalStatusName = maritalStatusName;
	}

	@Column(name = "MARITAL_STATUS_VALUE", length = 3)
	public String getMaritalStatusValue() {
		return this.maritalStatusValue;
	}

	public void setMaritalStatusValue(String maritalStatusValue) {
		this.maritalStatusValue = maritalStatusValue;
	}

	@Column(name = "MARITAL_STATUS_CODE", length = 5)
	public String getMaritalStatusCode() {
		return this.maritalStatusCode;
	}

	public void setMaritalStatusCode(String maritalStatusCode) {
		this.maritalStatusCode = maritalStatusCode;
	}

}
