package com.moptra.go4wealth.bean;
//Generated May 14, 2018 1:41:21 PM by Hibernate Tools 5.1.0.Alpha1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
* NavMaster generated by hbm2java
*/
@Entity
@Table(name = "nav_master", catalog = "go4wealthdb")
public class NavMaster implements java.io.Serializable {
	
	private Integer navMasterId;
	private String schemeCode;
	private String schemeName;
	private String rtaSchemeCode;
	private String rtaCode;
	private String isinCode;
	private String navDate;
	private String navValue;
	private String dividendReinvestFlag;
	
	public NavMaster() {
	}

	public NavMaster(String schemeCode, String schemeName, String rtaSchemeCode, String rtaCode, String isinCode, String navDate, String navValue, String dividendReinvestFlag) {
		this.schemeCode = schemeCode;
		this.schemeName = schemeName;
		this.rtaSchemeCode = rtaSchemeCode;
		this.rtaCode = rtaCode;
		this.isinCode = isinCode;
		this.navDate = navDate;
		this.navValue = navValue;
		this.dividendReinvestFlag = dividendReinvestFlag;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "NAV_MASTER_ID", unique = true, nullable = false)
	public Integer getNavMasterId() {
		return navMasterId;
	}

	public void setNavMasterId(Integer navMasterId) {
		this.navMasterId = navMasterId;
	}

	@Column(name = "SCHEME_CODE", length = 126)
	public String getSchemeCode() {
		return schemeCode;
	}

	public void setSchemeCode(String schemeCode) {
		this.schemeCode = schemeCode;
	}

	@Column(name = "SCHEME_NAME", length = 126)
	public String getSchemeName() {
		return schemeName;
	}

	public void setSchemeName(String schemeName) {
		this.schemeName = schemeName;
	}

	@Column(name = "RTA_SCHEME_CODE", length = 126)
	public String getRtaSchemeCode() {
		return rtaSchemeCode;
	}

	public void setRtaSchemeCode(String rtaSchemeCode) {
		this.rtaSchemeCode = rtaSchemeCode;
	}

	@Column(name = "RTA_CODE", length = 126)
	public String getRtaCode() {
		return rtaCode;
	}

	public void setRtaCode(String rtaCode) {
		this.rtaCode = rtaCode;
	}

	@Column(name = "ISIN_CODE", length = 126)
	public String getIsinCode() {
		return isinCode;
	}

	public void setIsinCode(String isinCode) {
		this.isinCode = isinCode;
	}

	@Column(name ="NAV_DATE", length=126)
	public String getNavDate() {
		return navDate;
	}

	public void setNavDate(String navDate) {
		this.navDate = navDate;
	}

	@Column(name = "NAV_VALUE", length=126)
	public String getNavValue() {
		return navValue;
	}

	public void setNavValue(String navValue) {
		this.navValue = navValue;
	}

	@Column(name = "DIVIDEND_REINVEST_FLAG", length = 126)
	public String getDividendReinvestFlag() {
		return dividendReinvestFlag;
	}

	public void setDividendReinvestFlag(String dividendReinvestFlag) {
		this.dividendReinvestFlag = dividendReinvestFlag;
	}
}