package com.moptra.go4wealth.bean;
// Generated 12 Jun, 2018 6:42:31 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * OnboardingStatus generated by hbm2java
 */
@Entity
@Table(name = "onboarding_status", catalog = "go4wealthdb")
public class OnboardingStatus implements java.io.Serializable {

	private int userId;
	private User user;
	private int kycStatus;
	private int mandateStatus;
	private int uccStatus;
	private int fatcaStatus;
	private int aofStatus;
	private String kycResponse;
	private String mandateResponse;
	private String uccResponse;
	private String fatcaResponse;
	private String aofResponse;
	private int overallStatus;
	private String clientCode;
	private String mandateNumber;
	private Date lastUpdated;
	private Integer isipMandateStatus;
	private String isipMandateResponse;
	private String isipMandateNumber;
	private String billerStatus;
	private String field2;
	private String uploadMandateStatus;
	private String enachStatus;

	
	@Column(name = "ISIP_MANDATE_STATUS",length=50)
	public Integer getIsipMandateStatus() {
		return isipMandateStatus;
	}

	public void setIsipMandateStatus(Integer isipMandateStatus) {
		this.isipMandateStatus = isipMandateStatus;
	}

	@Column(name = "ISIP_MANDATE_RESPONSE", length = 128)
	public String getIsipMandateResponse() {
		return isipMandateResponse;
	}

	public void setIsipMandateResponse(String isipMandateResponse) {
		this.isipMandateResponse = isipMandateResponse;
	}

	@Column(name = "ISIP_MANDATE_NUMBER", length = 512)
	public String getIsipMandateNumber() {
		return isipMandateNumber;
	}

	public void setIsipMandateNumber(String isipMandateNumber) {
		this.isipMandateNumber = isipMandateNumber;
	}

	public OnboardingStatus() {
	}

	public OnboardingStatus(User user, int kycStatus, int mandateStatus, int uccStatus, int fatcaStatus, int aofStatus,
			int overallStatus, Date lastUpdated) {
		this.user = user;
		this.kycStatus = kycStatus;
		this.mandateStatus = mandateStatus;
		this.uccStatus = uccStatus;
		this.fatcaStatus = fatcaStatus;
		this.aofStatus = aofStatus;
		this.overallStatus = overallStatus;
		this.lastUpdated = lastUpdated;
	}

	public OnboardingStatus(User user, int kycStatus, int mandateStatus, int uccStatus, int fatcaStatus, int aofStatus,
			String kycResponse, String mandateResponse, String uccResponse, String fatcaResponse, String aofResponse,
			int overallStatus, String clientCode, String mandateNumber, Date lastUpdated, Integer isipMandateStatus, String isipMandateResponse,
			String isipMandateNumber, String billerStatus) {
		this.user = user;
		this.kycStatus = kycStatus;
		this.mandateStatus = mandateStatus;
		this.uccStatus = uccStatus;
		this.fatcaStatus = fatcaStatus;
		this.aofStatus = aofStatus;
		this.kycResponse = kycResponse;
		this.mandateResponse = mandateResponse;
		this.uccResponse = uccResponse;
		this.fatcaResponse = fatcaResponse;
		this.aofResponse = aofResponse;
		this.overallStatus = overallStatus;
		this.clientCode = clientCode;
		this.mandateNumber = mandateNumber;
		this.lastUpdated = lastUpdated;
		this.isipMandateStatus = isipMandateStatus;
		this.isipMandateResponse = isipMandateResponse;
		this.isipMandateNumber = isipMandateNumber;
		this.billerStatus = billerStatus;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "user"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "USER_ID", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "KYC_STATUS", nullable = false)
	public int getKycStatus() {
		return this.kycStatus;
	}

	public void setKycStatus(int kycStatus) {
		this.kycStatus = kycStatus;
	}

	@Column(name = "MANDATE_STATUS", nullable = false)
	public int getMandateStatus() {
		return this.mandateStatus;
	}

	public void setMandateStatus(int mandateStatus) {
		this.mandateStatus = mandateStatus;
	}

	@Column(name = "UCC_STATUS", nullable = false)
	public int getUccStatus() {
		return this.uccStatus;
	}

	public void setUccStatus(int uccStatus) {
		this.uccStatus = uccStatus;
	}

	@Column(name = "FATCA_STATUS", nullable = false)
	public int getFatcaStatus() {
		return this.fatcaStatus;
	}

	public void setFatcaStatus(int fatcaStatus) {
		this.fatcaStatus = fatcaStatus;
	}

	@Column(name = "AOF_STATUS", nullable = false)
	public int getAofStatus() {
		return this.aofStatus;
	}

	public void setAofStatus(int aofStatus) {
		this.aofStatus = aofStatus;
	}

	@Column(name = "KYC_RESPONSE", length = 256)
	public String getKycResponse() {
		return this.kycResponse;
	}

	public void setKycResponse(String kycResponse) {
		this.kycResponse = kycResponse;
	}

	@Column(name = "MANDATE_RESPONSE", length = 256)
	public String getMandateResponse() {
		return this.mandateResponse;
	}

	public void setMandateResponse(String mandateResponse) {
		this.mandateResponse = mandateResponse;
	}

	@Column(name = "UCC_RESPONSE", length = 256)
	public String getUccResponse() {
		return this.uccResponse;
	}

	public void setUccResponse(String uccResponse) {
		this.uccResponse = uccResponse;
	}

	@Column(name = "FATCA_RESPONSE", length = 256)
	public String getFatcaResponse() {
		return this.fatcaResponse;
	}

	public void setFatcaResponse(String fatcaResponse) {
		this.fatcaResponse = fatcaResponse;
	}

	@Column(name = "AOF_RESPONSE", length = 256)
	public String getAofResponse() {
		return this.aofResponse;
	}

	public void setAofResponse(String aofResponse) {
		this.aofResponse = aofResponse;
	}

	@Column(name = "OVERALL_STATUS", nullable = false)
	public int getOverallStatus() {
		return this.overallStatus;
	}

	public void setOverallStatus(int overallStatus) {
		this.overallStatus = overallStatus;
	}

	@Column(name = "CLIENT_CODE", length = 15)
	public String getClientCode() {
		return this.clientCode;
	}

	public void setClientCode(String clientCode) {
		this.clientCode = clientCode;
	}

	@Column(name = "MANDATE_NUMBER", length = 15)
	public String getMandateNumber() {
		return this.mandateNumber;
	}

	public void setMandateNumber(String mandateNumber) {
		this.mandateNumber = mandateNumber;
	}

	@CreationTimestamp
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED", nullable = false, length = 19)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@Column(name = "BILLER_STATUS", length = 128)
	public String getBillerStatus() {
		return billerStatus;
	}
	
	public void setBillerStatus(String billerStatus) {
		this.billerStatus = billerStatus;
	}
	

	@Column(name="FIELD2", length=512)
	public String getField2() {
		return field2;
	}

	public void setField2(String field2) {
		this.field2 = field2;
	}

	@Column(name="UPLOAD_MANDATE_STATUS", length=512)
	public String getUploadMandateStatus() {
		return uploadMandateStatus;
	}
	public void setUploadMandateStatus(String uploadMandateStatus) {
		this.uploadMandateStatus = uploadMandateStatus;
	}

	@Column(name="ENACH_STATUS", length=512)
	public String getEnachStatus() {
		return enachStatus;
	}

	public void setEnachStatus(String enachStatus) {
		this.enachStatus = enachStatus;
	}

}
