package com.moptra.go4wealth.bean;
// Generated 1 Sep, 2018 6:25:25 PM by Hibernate Tools 5.1.0.Alpha1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.CreationTimestamp;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name = "orders", catalog = "go4wealthdb")
public class Orders implements java.io.Serializable {

	private Integer ordersId;
	private User user;
	private BigDecimal totalproduct;
	private BigDecimal totaltax;
	private String description;
	private Character locked;
	private Date timeplaced;
	private Date lastupdate;
	private String status;
	private BigDecimal totaladjustment;
	private String type;
	private Long csrMemberId;
	private Date expiredate;
	private Integer field1;
	private String field2;
	private String field3;
	private Date startdate;
	private String bseOrderId;
	private Integer goalId;
	private String goalName;
	private String modelPortfolioCategory;
	private String orderCategory;
	private Integer mPBundleId;
	private String paymentOptions;
	private String mandateId;
	private String follioNo;
	private Integer tranferInId;
	private Set<Ppcpayinst> ppcpayinsts = new HashSet<Ppcpayinst>(0);
	private Set<OrderItem> orderItems = new HashSet<OrderItem>(0);

	public Orders() {
	}

	public Orders(User user, BigDecimal totalproduct, BigDecimal totaltax, Date timeplaced, Date lastupdate,
			String status, BigDecimal totaladjustment, Date expiredate, Date startdate,String modelPortfolioCategory,String orderCategory,
			Integer mPBundleId,String paymentOptions,String mandateId,String follioNo,Integer tranferInId) {
		this.user = user;
		this.totalproduct = totalproduct;
		this.totaltax = totaltax;
		this.timeplaced = timeplaced;
		this.lastupdate = lastupdate;
		this.status = status;
		this.totaladjustment = totaladjustment;
		this.expiredate = expiredate;
		this.startdate = startdate;
		this.modelPortfolioCategory = modelPortfolioCategory;
		this.orderCategory = orderCategory;
		this.mPBundleId = mPBundleId;
		this.paymentOptions = paymentOptions;
		this.mandateId = mandateId;
		this.follioNo = follioNo;
		this.tranferInId =tranferInId;
	}

	public Orders(User user, BigDecimal totalproduct, BigDecimal totaltax, String description, Character locked,
			Date timeplaced, Date lastupdate, String status, BigDecimal totaladjustment, String type, Long csrMemberId,
			Date expiredate, Integer field1, String field2, String field3, Date startdate, String bseOrderId,
			Integer goalId, String goalName,String modelPortfolioCategory,String orderCategory,Integer mPBundleId,
			String paymentOptions,String mandateId,String follioNo,Integer tranferInId, Set<Ppcpayinst> ppcpayinsts, Set<OrderItem> orderItems) {
		this.user = user;
		this.totalproduct = totalproduct;
		this.totaltax = totaltax;
		this.description = description;
		this.locked = locked;
		this.timeplaced = timeplaced;
		this.lastupdate = lastupdate;
		this.status = status;
		this.totaladjustment = totaladjustment;
		this.type = type;
		this.csrMemberId = csrMemberId;
		this.expiredate = expiredate;
		this.field1 = field1;
		this.field2 = field2;
		this.field3 = field3;
		this.startdate = startdate;
		this.bseOrderId = bseOrderId;
		this.goalId = goalId;
		this.goalName = goalName;
		this.modelPortfolioCategory = modelPortfolioCategory;
		this.orderCategory = orderCategory;
		this.mPBundleId = mPBundleId;
		this.paymentOptions = paymentOptions;
		this.ppcpayinsts = ppcpayinsts;
		this.orderItems = orderItems;
		this.mandateId = mandateId;
		this.follioNo = follioNo;
		this.tranferInId =tranferInId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ORDERS_ID", unique = true, nullable = false)
	public Integer getOrdersId() {
		return this.ordersId;
	}

	public void setOrdersId(Integer ordersId) {
		this.ordersId = ordersId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "USER_ID", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "TOTALPRODUCT", nullable = false, precision = 20, scale = 5)
	public BigDecimal getTotalproduct() {
		return this.totalproduct;
	}

	public void setTotalproduct(BigDecimal totalproduct) {
		this.totalproduct = totalproduct;
	}

	@Column(name = "TOTALTAX", nullable = false, precision = 20, scale = 5)
	public BigDecimal getTotaltax() {
		return this.totaltax;
	}

	public void setTotaltax(BigDecimal totaltax) {
		this.totaltax = totaltax;
	}

	@Column(name = "DESCRIPTION", length = 254)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "LOCKED", length = 1)
	public Character getLocked() {
		return this.locked;
	}

	public void setLocked(Character locked) {
		this.locked = locked;
	}

	@CreationTimestamp
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TIMEPLACED", nullable = false, length = 19)
	public Date getTimeplaced() {
		return this.timeplaced;
	}

	public void setTimeplaced(Date timeplaced) {
		this.timeplaced = timeplaced;
	}

	@CreationTimestamp
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LASTUPDATE", nullable = false, length = 19)
	public Date getLastupdate() {
		return this.lastupdate;
	}

	public void setLastupdate(Date lastupdate) {
		this.lastupdate = lastupdate;
	}

	@Column(name = "STATUS", nullable = false, length = 3)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "TOTALADJUSTMENT", nullable = false, precision = 20, scale = 5)
	public BigDecimal getTotaladjustment() {
		return this.totaladjustment;
	}

	public void setTotaladjustment(BigDecimal totaladjustment) {
		this.totaladjustment = totaladjustment;
	}

	@Column(name = "type", length = 7)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "CSR_MEMBER_ID")
	public Long getCsrMemberId() {
		return this.csrMemberId;
	}

	public void setCsrMemberId(Long csrMemberId) {
		this.csrMemberId = csrMemberId;
	}

	@CreationTimestamp
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EXPIREDATE", nullable = false, length = 19)
	public Date getExpiredate() {
		return this.expiredate;
	}

	public void setExpiredate(Date expiredate) {
		this.expiredate = expiredate;
	}

	@Column(name = "FIELD1")
	public Integer getField1() {
		return this.field1;
	}

	public void setField1(Integer field1) {
		this.field1 = field1;
	}

	@Column(name = "FIELD2", length = 128)
	public String getField2() {
		return this.field2;
	}

	public void setField2(String field2) {
		this.field2 = field2;
	}

	@Column(name = "FIELD3", length = 512)
	public String getField3() {
		return this.field3;
	}

	public void setField3(String field3) {
		this.field3 = field3;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "startdate", nullable = false, length = 19)
	public Date getStartdate() {
		return this.startdate;
	}

	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}

	@Column(name = "BSE_ORDER_ID", length = 50)
	public String getBseOrderId() {
		return this.bseOrderId;
	}

	public void setBseOrderId(String bseOrderId) {
		this.bseOrderId = bseOrderId;
	}

	@Column(name = "GOAL_ID",length=50)
	public Integer getGoalId() {
		return this.goalId;
	}

	public void setGoalId(Integer goalId) {
		this.goalId = goalId;
	}

	@Column(name = "GOAL_NAME", length = 128)
	public String getGoalName() {
		return this.goalName;
	}

	public void setGoalName(String goalName) {
		this.goalName = goalName;
	}

	@Column(name = "MODEL_PORTFOLIO_CATEGORY", length = 50)
	public String getModelPortfolioCategory() {
		return modelPortfolioCategory;
	}
	public void setModelPortfolioCategory(String modelPortfolioCategory) {
		this.modelPortfolioCategory = modelPortfolioCategory;
	}
	
	@Column(name = "ORDER_CATEGORY", length = 50)
	public String getOrderCategory() {
		return orderCategory;
	}
	public void setOrderCategory(String orderCategory) {
		this.orderCategory = orderCategory;
	}
	
	@Column(name = "M_P_BUNDLE_ID", length = 50)
	public Integer getmPBundleId() {
		return mPBundleId;
	}
	public void setmPBundleId(Integer mPBundleId) {
		this.mPBundleId = mPBundleId;
	}
	
	@Column(name = "PAYMENT_OPTIONS", length = 50)
	public String getPaymentOptions() {
		return paymentOptions;
	}
	public void setPaymentOptions(String paymentOptions) {
		this.paymentOptions = paymentOptions;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orders")
	public Set<Ppcpayinst> getPpcpayinsts() {
		return this.ppcpayinsts;
	}

	public void setPpcpayinsts(Set<Ppcpayinst> ppcpayinsts) {
		this.ppcpayinsts = ppcpayinsts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orders",cascade=CascadeType.ALL)
	public Set<OrderItem> getOrderItems() {
		return this.orderItems;
	}

	public void setOrderItems(Set<OrderItem> orderItems) {
		this.orderItems = orderItems;
	}
	
	@Column(name = "MANDATE_ID", length = 50)
	public String getMandateId() {
		return mandateId;
	}
	public void setMandateId(String mandateId) {
		this.mandateId = mandateId;
	}

	@Column(name = "FOLLIO_No",length = 126)
	public String getFollioNo() {
		return follioNo;
	}
	public void setFollioNo(String follioNo) {
		this.follioNo = follioNo;
	}
	
	@Column(name = "TRANFER_IN_ID",length = 50)
	public Integer getTranferInId() {
		return tranferInId;
	}
	
	public void setTranferInId(Integer tranferInId) {
		this.tranferInId = tranferInId;
	}
	
}
