package com.moptra.go4wealth.bean;
// Generated 18 Jun, 2018 2:26:18 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OrderUniqueRef generated by hbm2java
 */
@Entity
@Table(name = "order_unique_ref", catalog = "go4wealthdb")
public class OrderUniqueRef implements java.io.Serializable {

	private int orderUniqueRefId;
	private String orderUniqueRefNo;
	private Integer field1;
	private String field2;
	private String field3;

	public OrderUniqueRef() {
	}

	public OrderUniqueRef(int orderUniqueRefId, String orderUniqueRefNo) {
		this.orderUniqueRefId = orderUniqueRefId;
		this.orderUniqueRefNo = orderUniqueRefNo;
	}

	public OrderUniqueRef(int orderUniqueRefId, String orderUniqueRefNo, Integer field1, String field2, String field3) {
		this.orderUniqueRefId = orderUniqueRefId;
		this.orderUniqueRefNo = orderUniqueRefNo;
		this.field1 = field1;
		this.field2 = field2;
		this.field3 = field3;
	}

	@Id

	@Column(name = "ORDER_UNIQUE_REF_ID", unique = true, nullable = false)
	public int getOrderUniqueRefId() {
		return this.orderUniqueRefId;
	}

	public void setOrderUniqueRefId(int orderUniqueRefId) {
		this.orderUniqueRefId = orderUniqueRefId;
	}

	@Column(name = "ORDER_UNIQUE_REF_NO", nullable = false, length = 50)
	public String getOrderUniqueRefNo() {
		return this.orderUniqueRefNo;
	}

	public void setOrderUniqueRefNo(String orderUniqueRefNo) {
		this.orderUniqueRefNo = orderUniqueRefNo;
	}

	@Column(name = "FIELD1")
	public Integer getField1() {
		return this.field1;
	}

	public void setField1(Integer field1) {
		this.field1 = field1;
	}

	@Column(name = "FIELD2", length = 128)
	public String getField2() {
		return this.field2;
	}

	public void setField2(String field2) {
		this.field2 = field2;
	}

	@Column(name = "FIELD3", length = 256)
	public String getField3() {
		return this.field3;
	}

	public void setField3(String field3) {
		this.field3 = field3;
	}

}
