package com.moptra.go4wealth.bean;
// Generated May 14, 2018 1:41:21 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.CreationTimestamp;

/**
 * Otp generated by hbm2java
 */
@Entity
@Table(name = "otp", catalog = "go4wealthdb")
public class Otp implements java.io.Serializable {

	private Integer otpId;
	private String otp;
	private Date sentTime;
	private String mobileNumber;

	public Otp() {
	}

	public Otp(Date sentTime) {
		this.sentTime = sentTime;
	}

	public Otp(String otp, Date sentTime, String mobileNumber) {
		this.otp = otp;
		this.sentTime = sentTime;
		this.mobileNumber = mobileNumber;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "OTP_ID", unique = true, nullable = false)
	public Integer getOtpId() {
		return this.otpId;
	}

	public void setOtpId(Integer otpId) {
		this.otpId = otpId;
	}

	@Column(name = "OTP", length = 126)
	public String getOtp() {
		return this.otp;
	}

	public void setOtp(String otp) {
		this.otp = otp;
	}

	@CreationTimestamp
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SENT_TIME", nullable = false, length = 19)
	public Date getSentTime() {
		return this.sentTime;
	}

	public void setSentTime(Date sentTime) {
		this.sentTime = sentTime;
	}

	@Column(name = "MOBILE_NUMBER", length = 10)
	public String getMobileNumber() {
		return this.mobileNumber;
	}

	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

}
