package com.moptra.go4wealth.bean;
// Generated 10 May, 2018 6:49:49 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * PanDetails generated by hbm2java
 */
@Entity
@Table(name = "pan_details", catalog = "go4wealthdb", uniqueConstraints = @UniqueConstraint(columnNames = "PAN_NO"))
public class PanDetails implements java.io.Serializable {

	private int userId;
	private User user;
	private String panNo;
	private Date dateOfBirth;
	private String gender;
	private String verified;
	private String panCardSelfieVideo;
	private Integer field1;
	private String field2;
	private String field3;
	private String fullName;
	private String occupation;

	public PanDetails() {
	}

	public PanDetails(User user, String panNo, Date dateOfBirth, String gender) {
		this.user = user;
		this.panNo = panNo;
		this.dateOfBirth = dateOfBirth;
		this.gender = gender;
	}

	public PanDetails(User user, String panNo, Date dateOfBirth, String gender, String verified,
			String panCardSelfieVideo, Integer field1, String field2, String field3, String fullName, String occupation) {
		this.user = user;
		this.panNo = panNo;
		this.dateOfBirth = dateOfBirth;
		this.gender = gender;
		this.verified = verified;
		this.panCardSelfieVideo = panCardSelfieVideo;
		this.field1 = field1;
		this.field2 = field2;
		this.field3 = field3;
		this.fullName = fullName;
		this.occupation = occupation;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "user"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "USER_ID", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "PAN_NO", unique = true, nullable = false, length = 126)
	public String getPanNo() {
		return this.panNo;
	}

	public void setPanNo(String panNo) {
		this.panNo = panNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_OF_BIRTH", length = 19)
	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	@Column(name = "GENDER", length = 50)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "VERIFIED", length = 50)
	public String getVerified() {
		return this.verified;
	}

	public void setVerified(String verified) {
		this.verified = verified;
	}

	@Column(name = "PAN_CARD_SELFIE_VIDEO", length = 256)
	public String getPanCardSelfieVideo() {
		return this.panCardSelfieVideo;
	}

	public void setPanCardSelfieVideo(String panCardSelfieVideo) {
		this.panCardSelfieVideo = panCardSelfieVideo;
	}

	@Column(name = "FIELD1")
	public Integer getField1() {
		return this.field1;
	}

	public void setField1(Integer field1) {
		this.field1 = field1;
	}

	@Column(name = "FIELD2", length = 128)
	public String getField2() {
		return this.field2;
	}

	public void setField2(String field2) {
		this.field2 = field2;
	}

	@Column(name = "FIELD3", length = 256)
	public String getField3() {
		return this.field3;
	}

	public void setField3(String field3) {
		this.field3 = field3;
	}
	
	@Column(name = "FULL_NAME", length = 100)
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	@Column(name = "OCCUPATION", length = 50)
	public String getOccupation() {
		return this.occupation;
	}

	public void setOccupation(String occupation) {
		this.occupation = occupation;
	}
}
