package com.moptra.go4wealth.bean;
// Generated 8 Oct, 2018 2:13:28 PM by Hibernate Tools 5.1.0.Alpha1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RedemptionStatusReportUserdata generated by hbm2java
 */
@Entity
@Table(name = "redemption_status_report_userdata", catalog = "go4wealthdb")
public class RedemptionStatusReportUserdata implements java.io.Serializable {

	private Integer redemptionStatusReportUserdataId;
	private BigDecimal amount;
	private BigDecimal amt;
	private String beneficiaryId;
	private String branchCode;
	private String clientCode;
	private String clientName;
	private String dpcFlag;
	private String dpTrans;
	private String folioNo;
	private String isin;
	private String memberCode;
	private String nav;
	private String orderDate;
	private Integer orderNo;
	private String orderType;
	private Integer qty;
	private String rtaSchemeCode;
	private String rtaTransNo;
	private String remarks;
	private String reportDate;
	private Integer stt;
	private String schemeCode;
	private String settNo;
	private String settType;
	private String subOrderType;
	private String unit;
	private Integer userId;
	private BigDecimal unitBalance;
	private BigDecimal availableBalance;
	private String redumptionDate;
	private BigDecimal redumptionAmount;
	private BigDecimal redumptionUnit;
	private String status;
	private String field1;
	private String field2;
	private String field3;
	private Integer field4;
	private BigDecimal field5;

	public RedemptionStatusReportUserdata() {
	}

	public RedemptionStatusReportUserdata(BigDecimal amount, BigDecimal amt, String beneficiaryId, String branchCode,
			String clientCode, String clientName, String dpcFlag, String dpTrans, String folioNo, String isin,
			String memberCode, String nav, String orderDate, Integer orderNo, String orderType, Integer qty,
			String rtaSchemeCode, String rtaTransNo, String remarks, String reportDate, Integer stt, String schemeCode,
			String settNo, String settType, String subOrderType, String unit, Integer userId, BigDecimal unitBalance,
			BigDecimal rupeeBalance, String redumptionDate, BigDecimal redumptionAmount, BigDecimal redumptionUnit,
			String status, String field1, String field2, String field3, Integer field4, BigDecimal field5) {
		this.amount = amount;
		this.amt = amt;
		this.beneficiaryId = beneficiaryId;
		this.branchCode = branchCode;
		this.clientCode = clientCode;
		this.clientName = clientName;
		this.dpcFlag = dpcFlag;
		this.dpTrans = dpTrans;
		this.folioNo = folioNo;
		this.isin = isin;
		this.memberCode = memberCode;
		this.nav = nav;
		this.orderDate = orderDate;
		this.orderNo = orderNo;
		this.orderType = orderType;
		this.qty = qty;
		this.rtaSchemeCode = rtaSchemeCode;
		this.rtaTransNo = rtaTransNo;
		this.remarks = remarks;
		this.reportDate = reportDate;
		this.stt = stt;
		this.schemeCode = schemeCode;
		this.settNo = settNo;
		this.settType = settType;
		this.subOrderType = subOrderType;
		this.unit = unit;
		this.userId = userId;
		this.unitBalance = unitBalance;
		this.availableBalance = rupeeBalance;
		this.redumptionDate = redumptionDate;
		this.redumptionAmount = redumptionAmount;
		this.redumptionUnit = redumptionUnit;
		this.status = status;
		this.field1 = field1;
		this.field2 = field2;
		this.field3 = field3;
		this.field4 = field4;
		this.field5 = field5;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Redemption_Status_Report_Userdata_Id", unique = true, nullable = false)
	public Integer getRedemptionStatusReportUserdataId() {
		return this.redemptionStatusReportUserdataId;
	}

	public void setRedemptionStatusReportUserdataId(Integer redemptionStatusReportUserdataId) {
		this.redemptionStatusReportUserdataId = redemptionStatusReportUserdataId;
	}

	@Column(name = "Amount", precision = 20, scale = 5)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "Amt", precision = 20, scale = 5)
	public BigDecimal getAmt() {
		return this.amt;
	}

	public void setAmt(BigDecimal amt) {
		this.amt = amt;
	}

	@Column(name = "Beneficiary_Id", length = 126)
	public String getBeneficiaryId() {
		return this.beneficiaryId;
	}

	public void setBeneficiaryId(String beneficiaryId) {
		this.beneficiaryId = beneficiaryId;
	}

	@Column(name = "Branch_Code", length = 126)
	public String getBranchCode() {
		return this.branchCode;
	}

	public void setBranchCode(String branchCode) {
		this.branchCode = branchCode;
	}

	@Column(name = "Client_Code", length = 126)
	public String getClientCode() {
		return this.clientCode;
	}

	public void setClientCode(String clientCode) {
		this.clientCode = clientCode;
	}

	@Column(name = "Client_Name", length = 126)
	public String getClientName() {
		return this.clientName;
	}

	public void setClientName(String clientName) {
		this.clientName = clientName;
	}

	@Column(name = "DPC_Flag", length = 126)
	public String getDpcFlag() {
		return this.dpcFlag;
	}

	public void setDpcFlag(String dpcFlag) {
		this.dpcFlag = dpcFlag;
	}

	@Column(name = "DP_Trans", length = 126)
	public String getDpTrans() {
		return this.dpTrans;
	}

	public void setDpTrans(String dpTrans) {
		this.dpTrans = dpTrans;
	}

	@Column(name = "Folio_No", length = 126)
	public String getFolioNo() {
		return this.folioNo;
	}

	public void setFolioNo(String folioNo) {
		this.folioNo = folioNo;
	}

	@Column(name = "ISIN", length = 126)
	public String getIsin() {
		return this.isin;
	}

	public void setIsin(String isin) {
		this.isin = isin;
	}

	@Column(name = "Member_Code", length = 126)
	public String getMemberCode() {
		return this.memberCode;
	}

	public void setMemberCode(String memberCode) {
		this.memberCode = memberCode;
	}

	@Column(name = "Nav", length = 126)
	public String getNav() {
		return this.nav;
	}

	public void setNav(String nav) {
		this.nav = nav;
	}

	@Column(name = "Order_Date", length = 126)
	public String getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(String orderDate) {
		this.orderDate = orderDate;
	}

	@Column(name = "Order_No")
	public Integer getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(Integer orderNo) {
		this.orderNo = orderNo;
	}

	@Column(name = "Order_Type", length = 126)
	public String getOrderType() {
		return this.orderType;
	}

	public void setOrderType(String orderType) {
		this.orderType = orderType;
	}

	@Column(name = "Qty")
	public Integer getQty() {
		return this.qty;
	}

	public void setQty(Integer qty) {
		this.qty = qty;
	}

	@Column(name = "RTA_Scheme_Code", length = 126)
	public String getRtaSchemeCode() {
		return this.rtaSchemeCode;
	}

	public void setRtaSchemeCode(String rtaSchemeCode) {
		this.rtaSchemeCode = rtaSchemeCode;
	}

	@Column(name = "RTA_Trans_No", length = 126)
	public String getRtaTransNo() {
		return this.rtaTransNo;
	}

	public void setRtaTransNo(String rtaTransNo) {
		this.rtaTransNo = rtaTransNo;
	}

	@Column(name = "Remarks", length = 126)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "Report_Date", length = 126)
	public String getReportDate() {
		return this.reportDate;
	}

	public void setReportDate(String reportDate) {
		this.reportDate = reportDate;
	}

	@Column(name = "STT")
	public Integer getStt() {
		return this.stt;
	}

	public void setStt(Integer stt) {
		this.stt = stt;
	}

	@Column(name = "Scheme_Code", length = 126)
	public String getSchemeCode() {
		return this.schemeCode;
	}

	public void setSchemeCode(String schemeCode) {
		this.schemeCode = schemeCode;
	}

	@Column(name = "Sett_No", length = 126)
	public String getSettNo() {
		return this.settNo;
	}

	public void setSettNo(String settNo) {
		this.settNo = settNo;
	}

	@Column(name = "Sett_Type", length = 126)
	public String getSettType() {
		return this.settType;
	}

	public void setSettType(String settType) {
		this.settType = settType;
	}

	@Column(name = "Sub_Order_Type", length = 126)
	public String getSubOrderType() {
		return this.subOrderType;
	}

	public void setSubOrderType(String subOrderType) {
		this.subOrderType = subOrderType;
	}

	@Column(name = "Unit", length = 126)
	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	@Column(name = "User_Id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "UNIT_BALANCE", precision = 20, scale = 5)
	public BigDecimal getUnitBalance() {
		return this.unitBalance;
	}

	public void setUnitBalance(BigDecimal unitBalance) {
		this.unitBalance = unitBalance;
	}

	@Column(name = "AVAILABLE_BALANCE", precision = 20, scale = 5)
	public BigDecimal getAvailableBalance() {
		return availableBalance;
	}
	public void setAvailableBalance(BigDecimal availableBalance) {
		this.availableBalance = availableBalance;
	}

	@Column(name = "REDUMPTION_DATE", length = 126)
	public String getRedumptionDate() {
		return this.redumptionDate;
	}

	public void setRedumptionDate(String redumptionDate) {
		this.redumptionDate = redumptionDate;
	}

	@Column(name = "REDUMPTION_AMOUNT", precision = 20, scale = 5)
	public BigDecimal getRedumptionAmount() {
		return this.redumptionAmount;
	}

	public void setRedumptionAmount(BigDecimal redumptionAmount) {
		this.redumptionAmount = redumptionAmount;
	}

	@Column(name = "REDUMPTION_UNIT", precision = 20, scale = 5)
	public BigDecimal getRedumptionUnit() {
		return this.redumptionUnit;
	}

	public void setRedumptionUnit(BigDecimal redumptionUnit) {
		this.redumptionUnit = redumptionUnit;
	}

	@Column(name = "STATUS", length = 126)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "FIELD1", length = 126)
	public String getField1() {
		return this.field1;
	}

	public void setField1(String field1) {
		this.field1 = field1;
	}

	@Column(name = "FIELD2", length = 126)
	public String getField2() {
		return this.field2;
	}

	public void setField2(String field2) {
		this.field2 = field2;
	}

	@Column(name = "FIELD3", length = 126)
	public String getField3() {
		return this.field3;
	}

	public void setField3(String field3) {
		this.field3 = field3;
	}

	@Column(name = "FIELD4")
	public Integer getField4() {
		return this.field4;
	}

	public void setField4(Integer field4) {
		this.field4 = field4;
	}

	@Column(name = "FIELD5", precision = 20, scale = 5)
	public BigDecimal getField5() {
		return this.field5;
	}

	public void setField5(BigDecimal field5) {
		this.field5 = field5;
	}

}
