package com.moptra.go4wealth.bean;
// Generated May 15, 2018 4:33:52 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ReturnsType generated by hbm2java
 */
@Entity
@Table(name = "returns_type", catalog = "go4wealthdb")
public class ReturnsType implements java.io.Serializable {

	private Integer returnsTypeId;
	private String returnsType;

	public ReturnsType() {
	}

	public ReturnsType(String returnsType) {
		this.returnsType = returnsType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "RETURNS_TYPE_ID", unique = true, nullable = false)
	public Integer getReturnsTypeId() {
		return this.returnsTypeId;
	}

	public void setReturnsTypeId(Integer returnsTypeId) {
		this.returnsTypeId = returnsTypeId;
	}

	@Column(name = "RETURNS_TYPE", nullable = false, length = 126)
	public String getReturnsType() {
		return this.returnsType;
	}

	public void setReturnsType(String returnsType) {
		this.returnsType = returnsType;
	}

}
