package com.moptra.go4wealth.bean;
// Generated May 15, 2018 4:33:52 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RiskType generated by hbm2java
 */
@Entity
@Table(name = "risk_type", catalog = "go4wealthdb")
public class RiskType implements java.io.Serializable {

	private Integer riskTypeId;
	private String riskType;

	public RiskType() {
	}

	public RiskType(String riskType) {
		this.riskType = riskType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "RISK_TYPE_ID", unique = true, nullable = false)
	public Integer getRiskTypeId() {
		return this.riskTypeId;
	}

	public void setRiskTypeId(Integer riskTypeId) {
		this.riskTypeId = riskTypeId;
	}

	@Column(name = "RISK_TYPE", nullable = false, length = 126)
	public String getRiskType() {
		return this.riskType;
	}

	public void setRiskType(String riskType) {
		this.riskType = riskType;
	}

}
