package com.moptra.go4wealth.bean;
// Generated May 15, 2018 4:33:52 PM by Hibernate Tools 5.1.0.Alpha1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RiskBearingCapacity generated by hbm2java
 */
@Entity
@Table(name = "risk_bearing_capacity", catalog = "go4wealthdb")
public class RiskBearingCapacity implements java.io.Serializable {

	private Integer riskBearingCapacityId;
	private String return_;
	private String risk;
	private String fundType;
	private BigDecimal nominalReturn;
	private BigDecimal inflAdjustedReturn;

	public RiskBearingCapacity() {
	}

	public RiskBearingCapacity(String return_, String risk, String fundType) {
		this.return_ = return_;
		this.risk = risk;
		this.fundType = fundType;
	}

	public RiskBearingCapacity(String return_, String risk, String fundType, BigDecimal nominalReturn,
			BigDecimal inflAdjustedReturn) {
		this.return_ = return_;
		this.risk = risk;
		this.fundType = fundType;
		this.nominalReturn = nominalReturn;
		this.inflAdjustedReturn = inflAdjustedReturn;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "RISK_BEARING_CAPACITY_ID", unique = true, nullable = false)
	public Integer getRiskBearingCapacityId() {
		return this.riskBearingCapacityId;
	}

	public void setRiskBearingCapacityId(Integer riskBearingCapacityId) {
		this.riskBearingCapacityId = riskBearingCapacityId;
	}

	@Column(name = "RETURN", nullable = false, length = 126)
	public String getReturn_() {
		return this.return_;
	}

	public void setReturn_(String return_) {
		this.return_ = return_;
	}

	@Column(name = "RISK", nullable = false, length = 126)
	public String getRisk() {
		return this.risk;
	}

	public void setRisk(String risk) {
		this.risk = risk;
	}

	@Column(name = "FUND_TYPE", nullable = false, length = 126)
	public String getFundType() {
		return this.fundType;
	}

	public void setFundType(String fundType) {
		this.fundType = fundType;
	}

	@Column(name = "NOMINAL_RETURN", precision = 10, scale = 5)
	public BigDecimal getNominalReturn() {
		return this.nominalReturn;
	}

	public void setNominalReturn(BigDecimal nominalReturn) {
		this.nominalReturn = nominalReturn;
	}

	@Column(name = "INFL_ADJUSTED_RETURN", precision = 10, scale = 5)
	public BigDecimal getInflAdjustedReturn() {
		return this.inflAdjustedReturn;
	}

	public void setInflAdjustedReturn(BigDecimal inflAdjustedReturn) {
		this.inflAdjustedReturn = inflAdjustedReturn;
	}

}
