package com.moptra.go4wealth.bean;
// Generated 19 Jun, 2018 6:56:42 PM by Hibernate Tools 5.1.0.Alpha1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.CreationTimestamp;

/**
 * SchemeRecentView generated by hbm2java
 */
@Entity
@Table(name = "scheme_recent_view", catalog = "go4wealthdb")
public class SchemeRecentView implements java.io.Serializable {

	private int recentViewId;
	private Scheme scheme;
	private Date lastUpdated;

	public SchemeRecentView() {
	}

	public SchemeRecentView(int recentViewId, Scheme scheme, Date lastUpdated) {
		this.recentViewId = recentViewId;
		this.scheme = scheme;
		this.lastUpdated = lastUpdated;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "RECENT_VIEW_ID", unique = true, nullable = false)
	public int getRecentViewId() {
		return this.recentViewId;
	}

	public void setRecentViewId(int recentViewId) {
		this.recentViewId = recentViewId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SCHEME_ID", nullable = false)
	public Scheme getScheme() {
		return this.scheme;
	}

	public void setScheme(Scheme scheme) {
		this.scheme = scheme;
	}
	
	@CreationTimestamp
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED", nullable = false, length = 19)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

}
