package com.moptra.go4wealth.bean;
// Generated 27 Jun, 2018 12:07:48 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * StoreConf generated by hbm2java
 */
@Entity
@Table(name = "store_conf", catalog = "go4wealthdb", uniqueConstraints = @UniqueConstraint(columnNames = "KEYWORD"))
public class StoreConf implements java.io.Serializable {

	private int storeConfId;
	private String keyword;
	private String keywordValue;
	private Integer field1;
	private String field2;
	private String field3;

	public StoreConf() {
	}

	public StoreConf(int storeConfId, String keyword, String keywordValue) {
		this.storeConfId = storeConfId;
		this.keyword = keyword;
		this.keywordValue = keywordValue;
	}

	public StoreConf(int storeConfId, String keyword, String keywordValue, Integer field1, String field2,
			String field3) {
		this.storeConfId = storeConfId;
		this.keyword = keyword;
		this.keywordValue = keywordValue;
		this.field1 = field1;
		this.field2 = field2;
		this.field3 = field3;
	}

	@Id

	@Column(name = "STORE_CONF_ID", unique = true, nullable = false)
	public int getStoreConfId() {
		return this.storeConfId;
	}

	public void setStoreConfId(int storeConfId) {
		this.storeConfId = storeConfId;
	}

	@Column(name = "KEYWORD", unique = true, nullable = false, length = 100)
	public String getKeyword() {
		return this.keyword;
	}

	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	@Column(name = "KEYWORD_VALUE", nullable = false, length = 256)
	public String getKeywordValue() {
		return this.keywordValue;
	}

	public void setKeywordValue(String keywordValue) {
		this.keywordValue = keywordValue;
	}

	@Column(name = "FIELD1")
	public Integer getField1() {
		return this.field1;
	}

	public void setField1(Integer field1) {
		this.field1 = field1;
	}

	@Column(name = "FIELD2", length = 128)
	public String getField2() {
		return this.field2;
	}

	public void setField2(String field2) {
		this.field2 = field2;
	}

	@Column(name = "FIELD3", length = 256)
	public String getField3() {
		return this.field3;
	}

	public void setField3(String field3) {
		this.field3 = field3;
	}

}
