package com.moptra.go4wealth.bean;
// Generated 21 May, 2018 2:13:51 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SystemPropertiesId generated by hbm2java
 */
@Embeddable
public class SystemPropertiesId implements java.io.Serializable {

	private String propertyKey;
	private String propertyValue;

	public SystemPropertiesId() {
	}

	public SystemPropertiesId(String propertyKey, String propertyValue) {
		this.propertyKey = propertyKey;
		this.propertyValue = propertyValue;
	}

	@Column(name = "PROPERTY_KEY", nullable = false, length = 50)
	public String getPropertyKey() {
		return this.propertyKey;
	}

	public void setPropertyKey(String propertyKey) {
		this.propertyKey = propertyKey;
	}

	@Column(name = "PROPERTY_VALUE", nullable = false, length = 50)
	public String getPropertyValue() {
		return this.propertyValue;
	}

	public void setPropertyValue(String propertyValue) {
		this.propertyValue = propertyValue;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SystemPropertiesId))
			return false;
		SystemPropertiesId castOther = (SystemPropertiesId) other;

		return ((this.getPropertyKey() == castOther.getPropertyKey()) || (this.getPropertyKey() != null
				&& castOther.getPropertyKey() != null && this.getPropertyKey().equals(castOther.getPropertyKey())))
				&& ((this.getPropertyValue() == castOther.getPropertyValue())
						|| (this.getPropertyValue() != null && castOther.getPropertyValue() != null
								&& this.getPropertyValue().equals(castOther.getPropertyValue())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPropertyKey() == null ? 0 : this.getPropertyKey().hashCode());
		result = 37 * result + (getPropertyValue() == null ? 0 : this.getPropertyValue().hashCode());
		return result;
	}

}
