package com.moptra.go4wealth.bean;
// Generated 21 May, 2018 2:13:51 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SystemProperties generated by hbm2java
 */
@Entity
@Table(name = "system_properties", catalog = "go4wealthdb")
public class SystemProperties implements java.io.Serializable {

	private SystemPropertiesId id;

	public SystemProperties() {
	}

	public SystemProperties(SystemPropertiesId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "propertyKey", column = @Column(name = "PROPERTY_KEY", nullable = false, length = 50)),
			@AttributeOverride(name = "propertyValue", column = @Column(name = "PROPERTY_VALUE", nullable = false, length = 50)) })
	public SystemPropertiesId getId() {
		return this.id;
	}

	public void setId(SystemPropertiesId id) {
		this.id = id;
	}

}
