package com.moptra.go4wealth.bean;
// Generated 6 Jul, 2018 5:42:10 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Testimonial generated by hbm2java
 */
@Entity
@Table(name = "testimonial", catalog = "go4wealthdb")
public class Testimonial implements java.io.Serializable {

	private Integer testimonialId;
	private String name;
	private String designation;
	private String companyName;
	private String imageUrl;
	private String comments;
	private String field1;
	private String field2;
	private Integer field3;

	public Testimonial() {
	}

	public Testimonial(String name, String designation, String companyName, String imageUrl) {
		this.name = name;
		this.designation = designation;
		this.companyName = companyName;
		this.imageUrl = imageUrl;
	}

	public Testimonial(String name, String designation, String companyName, String imageUrl, String comments,
			String field1, String field2, Integer field3) {
		this.name = name;
		this.designation = designation;
		this.companyName = companyName;
		this.imageUrl = imageUrl;
		this.comments = comments;
		this.field1 = field1;
		this.field2 = field2;
		this.field3 = field3;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "TESTIMONIAL_ID", unique = true, nullable = false)
	public Integer getTestimonialId() {
		return this.testimonialId;
	}

	public void setTestimonialId(Integer testimonialId) {
		this.testimonialId = testimonialId;
	}

	@Column(name = "NAME", length = 126)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DESIGNATION", length = 126)
	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	@Column(name = "COMPANY_NAME", length = 126)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name = "IMAGE_URL", length = 126)
	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	@Column(name = "COMMENTS", length = 5000)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Column(name = "FIELD1", length = 500)
	public String getField1() {
		return this.field1;
	}

	public void setField1(String field1) {
		this.field1 = field1;
	}

	@Column(name = "FIELD2", length = 126)
	public String getField2() {
		return this.field2;
	}

	public void setField2(String field2) {
		this.field2 = field2;
	}

	@Column(name = "FIELD3")
	public Integer getField3() {
		return this.field3;
	}

	public void setField3(Integer field3) {
		this.field3 = field3;
	}

}
