
package com.moptra.go4wealth.bean;
// Generated 5 Jun, 2018 8:42:02 PM by Hibernate Tools 5.1.0.Alpha1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TopSchemes generated by hbm2java
 */
@Entity
@Table(name = "top_schemes", catalog = "go4wealthdb")
public class TopSchemes implements java.io.Serializable {

	private Integer topSchemeId;
	private String schemeCode;
	private String schemeName;
	private String status;
	private Date createdDate;
	private Date deactivatedDate;
	private String schemeCategory;
	private int sequence;

	public TopSchemes() {
	}

	public TopSchemes(String schemeCode) {
		this.schemeCode = schemeCode;
	}

	public TopSchemes(String schemeCode, String schemeName,String status, Date createdDate, Date deactivatedDate,String schemeCategory,int sequence) {
		this.schemeCode = schemeCode;
		this.schemeName=schemeName;
		this.status = status;
		this.createdDate = createdDate;
		this.deactivatedDate = deactivatedDate;
		this.schemeCategory = schemeCategory;
		this.sequence = sequence;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "TOP_SCHEME_ID", unique = true, nullable = false)
	public Integer getTopSchemeId() {
		return this.topSchemeId;
	}

	public void setTopSchemeId(Integer topSchemeId) {
		this.topSchemeId = topSchemeId;
	}

	@Column(name = "SCHEME_CODE", length = 126)
	public String getSchemeCode() {
		return this.schemeCode;
	}

	public void setSchemeCode(String schemeCode) {
		this.schemeCode = schemeCode;
	}

	@Column(name = "SCHEME_NAME", length = 256)
	public String getSchemeName() {
		return this.schemeName;
	}

	public void setSchemeName(String schemeName) {
		this.schemeName = schemeName;
	}
	
	@Column(name = "STATUS", length = 50)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "CREATED_DATE")
	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "DEACTIVATED_DATE")
	public Date getDeactivatedDate() {
		return deactivatedDate;
	}

	public void setDeactivatedDate(Date deactivatedDate) {
		this.deactivatedDate = deactivatedDate;
	}

	@Column(name = "SCHEME_CATEGORY")
	public String getSchemeCategory() {
		return schemeCategory;
	}

	public void setSchemeCategory(String schemeCategory) {
		this.schemeCategory = schemeCategory;
	}

	@Column(name = "SEQUENCE")
	public int getSequence() {
		return sequence;
	}

	public void setSequence(int sequence) {
		this.sequence = sequence;
	}

}
