package com.moptra.go4wealth.bean;
// Generated 22 Feb, 2019 1:21:51 PM by Hibernate Tools 5.1.0.Alpha1

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.CreationTimestamp;

/**
 * TransferIn generated by hbm2java
 */
@Entity
@Table(name = "transfer_in", catalog = "go4wealthdb")
public class TransferIn implements java.io.Serializable {

	private Integer transferInId;
	private String folioNumber;
	private String schemeCode;
	private Integer uniqueId;
	private String investerName;
	private BigDecimal unit;
	private BigDecimal amount;
	private String pan;
	private String transactionType;
	private String startedOn;
	private Date timeCreated;
	private Date lastUpdated;
	private String status;
	private Integer statusCode;
	private BigDecimal field1;
	private int userId;
	private String field3;
	private String field4;
	private String investmentType;
	private String sipRegNo;
	private BigDecimal availableUnit;
	private String rtaAgent;
	private String redumptionStatus;

	public TransferIn() {
	}

	public TransferIn(BigDecimal unit, BigDecimal amount, Date timeCreated, Date lastUpdated,BigDecimal field1, int userId, String redumptionStatus) {
		this.unit = unit;
		this.amount = amount;
		this.timeCreated = timeCreated;
		this.lastUpdated = lastUpdated;
		this.field1 = field1;
		this.userId = userId;
		this.redumptionStatus = redumptionStatus;
	}

	public TransferIn(String folioNumber, String schemeCode, Integer uniqueId, String investerName,
			BigDecimal unit, BigDecimal amount,
			String pan, String transactionType,String startedOn,
			Date timeCreated, Date lastUpdated, String status, Integer statusCode,
			BigDecimal field1, int userId, String field3, String field4, String investmentType,String sipRegNo,BigDecimal availableUnit,String rtaAgent
			,String redumptionStatus) {
		this.folioNumber = folioNumber;
		this.schemeCode = schemeCode;
		this.uniqueId = uniqueId;
		this.investerName = investerName;
		this.startedOn = startedOn;
		this.unit = unit;
		this.amount = amount;
		this.pan = pan;
		this.transactionType = transactionType;
		this.timeCreated = timeCreated;
		this.lastUpdated = lastUpdated;
		this.status = status;
		this.statusCode = statusCode;
		this.field1 = field1;
		this.userId = userId;
		this.field3 = field3;
		this.field4 = field4;
		this.investmentType = investmentType;
		this.sipRegNo = sipRegNo;
		this.availableUnit = availableUnit;
		this.rtaAgent = rtaAgent;
		this.redumptionStatus = redumptionStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "TRANSFER_IN_ID", unique = true, nullable = false)
	public Integer getTransferInId() {
		return this.transferInId;
	}

	public void setTransferInId(Integer transferInId) {
		this.transferInId = transferInId;
	}

	@Column(name = "FOLIO_NUMBER", length = 126)
	public String getFolioNumber() {
		return this.folioNumber;
	}

	public void setFolioNumber(String folioNumber) {
		this.folioNumber = folioNumber;
	}

	@Column(name = "SCHEME_CODE", length = 512)
	public String getSchemeCode() {
		return this.schemeCode;
	}

	public void setSchemeCode(String schemeCode) {
		this.schemeCode = schemeCode;
	}

	@Column(name = "INVESTER_NAME", length = 128)
	public String getInvesterName() {
		return this.investerName;
	}

	public void setInvesterName(String investerName) {
		this.investerName = investerName;
	}

	@Column(name = "UNIT", nullable = false, precision = 20, scale = 5)
	public BigDecimal getUnit() {
		return this.unit;
	}

	public void setUnit(BigDecimal unit) {
		this.unit = unit;
	}

	@Column(name = "AMOUNT", nullable = false, precision = 20, scale = 5)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "PAN", length = 128)
	public String getPan() {
		return this.pan;
	}

	public void setPan(String pan) {
		this.pan = pan;
	}

	@Column(name = "TRANSACTION_TYPE", length = 50)
	public String getTransactionType() {
		return this.transactionType;
	}

	public void setTransactionType(String transactionType) {
		this.transactionType = transactionType;
	}

	@CreationTimestamp
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TIME_CREATED", nullable = false, length = 19)
	public Date getTimeCreated() {
		return this.timeCreated;
	}

	public void setTimeCreated(Date timeCreated) {
		this.timeCreated = timeCreated;
	}

	@CreationTimestamp
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED", nullable = false, length = 19)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@Column(name = "STATUS", length = 50)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "STATUS_CODE")
	public Integer getStatusCode() {
		return this.statusCode;
	}

	public void setStatusCode(Integer statusCode) {
		this.statusCode = statusCode;
	}

	@Column(name = "FIELD1", nullable = false, precision = 20, scale = 5)
	public BigDecimal getField1() {
		return this.field1;
	}

	public void setField1(BigDecimal field1) {
		this.field1 = field1;
	}

	@Column(name = "FIELD3", length = 50)
	public String getField3() {
		return this.field3;
	}

	public void setField3(String field3) {
		this.field3 = field3;
	}

	@Column(name = "FIELD4", length = 128)
	public String getField4() {
		return this.field4;
	}

	public void setField4(String field4) {
		this.field4 = field4;
	}

	@Column(name="INVESTMENT_TYPE", length=50)
	public String getInvestmentType() {
		return investmentType;
	}

	public void setInvestmentType(String investmentType) {
		this.investmentType = investmentType;
	}

	@Column(name="SIP_REG_NO", length=126)
	public String getSipRegNo() {
		return sipRegNo;
	}

	public void setSipRegNo(String sipRegNo) {
		this.sipRegNo = sipRegNo;
	}

	@Column(name="USER_ID", length=50)
	public int getUserId() {
		return userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name="UNIQUE_ID", length=50)
	public Integer getUniqueId() {
		return uniqueId;
	}

	public void setUniqueId(Integer uniqueId) {
		this.uniqueId = uniqueId;
	}

	@Column(name="STARTED_ON", length=126)
	public String getStartedOn() {
		return startedOn;
	}

	public void setStartedOn(String startedOn) {
		this.startedOn = startedOn;
	}

	@Column(name = "AVAILABLE_UNIT", nullable = false, precision = 20, scale = 5)
	public BigDecimal getAvailableUnit() {
		return availableUnit;
	}

	public void setAvailableUnit(BigDecimal availableUnit) {
		this.availableUnit = availableUnit;
	}

	@Column(name="RTA_AGENT", length=126)
	public String getRtaAgent() {
		return rtaAgent;
	}

	public void setRtaAgent(String rtaAgent) {
		this.rtaAgent = rtaAgent;
	}

	@Column(name = "REDUMPTION_STATUS" , length = 126)
	public String getRedumptionStatus() {
		return redumptionStatus;
	}
	public void setRedumptionStatus(String redumptionStatus) {
		this.redumptionStatus = redumptionStatus;
	}
}