package com.moptra.go4wealth.bean;
// Generated 1 Aug, 2018 2:49:44 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserWatchlist generated by hbm2java
 */
@Entity
@Table(name = "user_watchlist", catalog = "go4wealthdb")
public class UserWatchlist implements java.io.Serializable {

	private Integer userWatchlistId;
	private User user;
	private String schemeCode;
	private Integer purchasedStatus;
	private Integer removedStatus;

	public UserWatchlist() {
	}

	public UserWatchlist(User user) {
		this.user = user;
	}

	public UserWatchlist(User user, String schemeCode, Integer purchasedStatus, Integer removedStatus) {
		this.user = user;
		this.schemeCode = schemeCode;
		this.purchasedStatus = purchasedStatus;
		this.removedStatus = removedStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "USER_WATCHLIST_ID", unique = true, nullable = false)
	public Integer getUserWatchlistId() {
		return this.userWatchlistId;
	}

	public void setUserWatchlistId(Integer userWatchlistId) {
		this.userWatchlistId = userWatchlistId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "SCHEME_CODE", length = 126)
	public String getSchemeCode() {
		return this.schemeCode;
	}

	public void setSchemeCode(String schemeCode) {
		this.schemeCode = schemeCode;
	}

	@Column(name = "PURCHASED_STATUS", length = 50)
	public Integer getPurchasedStatus() {
		return this.purchasedStatus;
	}

	public void setPurchasedStatus(Integer purchasedStatus) {
		this.purchasedStatus = purchasedStatus;
	}

	@Column(name = "REMOVED_STATUS", length = 50)
	public Integer getRemovedStatus() {
		return this.removedStatus;
	}

	public void setRemovedStatus(Integer removedStatus) {
		this.removedStatus = removedStatus;
	}

}
