package com.moptra.go4wealth.bean;
//Generated 1 Aug, 2018 2:49:44 PM by Hibernate Tools 5.1.0.Alpha1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.CreationTimestamp;

/**
 * UserMandateHistory generated by hbm2java
 */
@Entity
@Table(name = "user_mandate_history", catalog = "go4wealthdb")
public class UserMandateHistory  implements java.io.Serializable {
	
	private Integer userMandateHistoryId;
	private Integer userId;
	private String userBankAccount;
	private String bankIfsc;
	private String mandateType;
	private String status;
	private String mandateId;
	private Date createdDate;
	private Date mandateCreatedDate;
	private Date updatedDate;
	private String field1;
	private String field2;
	private String field3;
	private Integer field4;
	private Integer field5;
	private String orderPlaceFlag;
	
	public UserMandateHistory(){
	}
	
	public UserMandateHistory(Integer userId,String userBankAccount,String bankIfsc,String mandateType,String status,String mandateId,Date createdDate, Date mandateCreatedDate, Date updatedDate,String field1,String field2,String field3,Integer field4,Integer field5,String orderPlaceFlag) {
		this.userId = userId;
		this.userBankAccount = userBankAccount;
		this.bankIfsc = bankIfsc;
		this.mandateType = mandateType;
		this.status = status;
		this.createdDate = createdDate;
		this.mandateCreatedDate = mandateCreatedDate;
		this.updatedDate = updatedDate;
		this.mandateId = mandateId;
		this.field1 = field1;
		this.field2 = field2;
		this.field3 = field3;
		this.field4 = field4;
		this.field5 = field5;
		this.orderPlaceFlag = orderPlaceFlag;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "USER_MANDATE_HISTORY_ID", unique = true, nullable = false)
	public Integer getUserMandateHistoryId() {
		return userMandateHistoryId;
	}

	public void setUserMandateHistoryId(Integer userMandateHistoryId) {
		this.userMandateHistoryId = userMandateHistoryId;
	}

	@Column(name = "USER_ID", length = 50)
	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "USER_BANK_ACCOUNT", length = 512)
	public String getUserBankAccount() {
		return userBankAccount;
	}

	public void setUserBankAccount(String userBankAccount) {
		this.userBankAccount = userBankAccount;
	}

	@Column(name = "BANK_IFSC", length = 512)
	public String getBankIfsc() {
		return bankIfsc;
	}

	public void setBankIfsc(String bankIfsc) {
		this.bankIfsc = bankIfsc;
	}

	@CreationTimestamp
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false)
	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "FIELD1", length = 512)
	public String getField1() {
		return field1;
	}

	public void setField1(String field1) {
		this.field1 = field1;
	}

	@Column(name = "FIELD2", length = 512)
	public String getField2() {
		return field2;
	}

	public void setField2(String field2) {
		this.field2 = field2;
	}

	@Column(name = "FIELD3", length = 512)
	public String getField3() {
		return field3;
	}

	public void setField3(String field3) {
		this.field3 = field3;
	}

	@Column(name = "FIELD4", length = 50)
	public Integer getField4() {
		return field4;
	}

	public void setField4(Integer field4) {
		this.field4 = field4;
	}
	
	@Column(name = "FIELD5", length = 50)
	public Integer getField5() {
		return field5;
	}

	public void setField5(Integer field5) {
		this.field5 = field5;
	}

	@Column(name = "MANDATE_TYPE", length = 512)
	public String getMandateType() {
		return mandateType;
	}

	public void setMandateType(String mandateType) {
		this.mandateType = mandateType;
	}

	@Column(name = "STATUS", length = 512)
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "MANDATE_ID", length = 512)
	public String getMandateId() {
		return mandateId;
	}

	public void setMandateId(String mandateId) {
		this.mandateId = mandateId;
	}

	@CreationTimestamp
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MANDATE_CREATED_DATE", nullable = false)
	public Date getMandateCreatedDate() {
		return mandateCreatedDate;
	}

	public void setMandateCreatedDate(Date mandateCreatedDate) {
		this.mandateCreatedDate = mandateCreatedDate;
	}

	@CreationTimestamp
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", nullable = false)
	public Date getUpdatedDate() {
		return updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "ORDER_PLACE_FLAG", length = 512)
	public String getOrderPlaceFlag() {
		return orderPlaceFlag;
	}

	public void setOrderPlaceFlag(String orderPlaceFlag) {
		this.orderPlaceFlag = orderPlaceFlag;
	}

}