package com.moptra.go4wealth.bean;
// Generated May 14, 2018 1:41:21 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserAuthority generated by hbm2java
 */
@Entity
@Table(name = "user_authority", catalog = "go4wealthdb")
public class UserAuthority implements java.io.Serializable {

	private UserAuthorityId id;
	private Authority authority;
	private User user;

	public UserAuthority() {
	}

	public UserAuthority(UserAuthorityId id, Authority authority, User user) {
		this.id = id;
		this.authority = authority;
		this.user = user;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "userId", column = @Column(name = "USER_ID", nullable = false)),
			@AttributeOverride(name = "authorityId", column = @Column(name = "AUTHORITY_ID", nullable = false)) })
	public UserAuthorityId getId() {
		return this.id;
	}

	public void setId(UserAuthorityId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AUTHORITY_ID", nullable = false, insertable = false, updatable = false)
	public Authority getAuthority() {
		return this.authority;
	}

	public void setAuthority(Authority authority) {
		this.authority = authority;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID", nullable = false, insertable = false, updatable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
